# -*- coding: utf-8 -*-
"""서비스 속 구조 데이터(2026-10-07 코드 조사, 파일:줄 근거). 형식: INTERNAL[키] = dict(runtime, parts, links, ext, notes)."""
INTERNAL = {}

# ceco_demo 내부 구조 — sim · plc · edge · router · hub (읽기 전용 조사, 2026-10-07 작업 트리 기준)
# INTERNAL 은 호출 측에서 dict 로 준비한다.

INTERNAL["sim"] = dict(
  runtime="Python 3.12(python:3.12-slim) · 1프로세스 · asyncio 이벤트 루프 1개(스레드 없음): 스캔 루프 태스크 + pymodbus 비동기 TCP 서버 :502 + aiohttp 앱 3개(:8080 강사·:8081 패널·:8082 정비팀). 잠금 없음(같은 루프에서 차례로 실행). 경로 기준 0_plant/simulator/",
  parts=[
    ("s_boot", "기동·설정 적재", "sim.py:377-405", "plant.yaml·환경변수 읽고 HTTP 3개·스캔 태스크·Modbus 서버 기동"),
    ("s_scan", "스캔 루프", "sim.py:97-119·393-404", "1초마다 명령 읽기 → 물리 1스캔 → 계측값 쓰기"),
    ("s_store", "Modbus 데이터 저장소·서버", "sim.py:48-58·75-95·405", "코일 64·HR 512 메모리 맵, PLC 마스터가 읽고 씀"),
    ("s_plant", "물리 모델 ReactorPlant", "plant.py:43-140·205-399·468-470", "질량·에너지·압력 오일러 적분(배속·소구간)"),
    ("s_fault", "고장·열화 엔진", "plant.py:21-41·142-203·472-491", "고장 주입·만료·열화 진행·계측 효과(노이즈·결측)"),
    ("s_instr", "강사 API(:8080)", "sim.py:194-306", "고장 주입·해제·진값 스냅샷·강사 화면"),
    ("s_panel", "현장 패널(:8081)", "sim.py:121-152·309-374", "모드·현장 기동정지·정비·비상정지 → HR300..308"),
    ("s_crew", "가상 정비팀(:8082)", "sim.py:154-192·335-352·plant.py:401-466", "작업 지시 1회 수행: 안전확인→격리→대기→효과·소견"),
  ],
  links=[
    ("s_boot", "s_scan", "asyncio 태스크(create_task)", "스캔 루프 시작", "sim.py:393-404"),
    ("s_boot", "s_store", "함수 호출(StartAsyncTcpServer)", "ModbusServerContext 로 :502 서버 기동", "sim.py:405"),
    ("s_scan", "s_store", "함수 호출(getValues)", "코일0..3 구동 명령·HR100..102 설정값(min/max 클램프)·HR307 비상정지", "sim.py:103-113"),
    ("s_scan", "s_plant", "함수 호출(step)", "cmd_*·sp_*·estop 속성 설정 후 step(dt=1 s)", "sim.py:98-113, plant.py:310-358"),
    ("s_plant", "s_fault", "함수 호출", "소구간마다 _expire_faults·_degrade, 계측마다 _measure", "plant.py:221·319·355"),
    ("s_scan", "s_store", "함수 호출(setValues)", "계측 17점 float32(HR0..23·28..37)·순번 HR24-25·설비 시각 HR26-27", "sim.py:115-119, plant.yaml:17-35·51-52"),
    ("s_instr", "s_fault", "함수 호출", "inject(scenario, duration_s)·clear_faults()", "sim.py:256·262"),
    ("s_instr", "s_plant", "공유 메모리(같은 루프, 잠금 없음)", "readings·명령·열화·고장 상태 스냅샷 읽기", "sim.py:195-219"),
    ("s_panel", "s_store", "함수 호출(setValues/getValues)", "HR300..308 패널 레지스터 쓰기(seq 카운터 +1)", "sim.py:122-152"),
    ("s_crew", "s_plant", "공유 메모리(isolated 집합) + 함수 호출", "field_check·격리 추가/해제·field_apply", "sim.py:168-179"),
    ("s_crew", "s_fault", "함수 호출(field_apply 안 drop)", "원인과 맞는 작업이면 고장·열화 상태 해제", "plant.py:415-463"),
    ("s_crew", "s_panel", "함수 호출(panel_action)", "release_maintenance 이면 정비 해제 키(HR305 +1)", "sim.py:183-184"),
  ],
  ext=[
    ("s_store", "both", "Modbus/TCP :502 단일 유닛(single=True) · 상대 PLC(OpenPLC 마스터)", "읽기: HR0..37 계측·순번·시각, HR300..308 패널 / 쓰기: 코일0..3(FC15), HR100..102(FC16)", "sim.py:75-84·405, 1_control/plc-openplc/project/project.json:41-119"),
    ("s_instr", "in", "HTTP :8080 Basic(INSTRUCTOR_*) · GET / ·/state·/faults, POST /fault·/fault/clear · 호스트는 라우터 28080 경유", "고장 시나리오 JSON, 상태 스냅샷", "sim.py:238-275, shared/network-router/rules.sh:36"),
    ("s_instr", "in", "HTTP GET :8080/health(인증 면제) · compose healthcheck", "{status, seq}", "sim.py:229-230·241-242, compose.yml:103-104"),
    ("s_panel", "in", "HTTP :8081 Basic(FIELD_PANEL_*) · GET / ·/panel, POST /panel · 호스트는 라우터 28081 경유", "패널 동작 {action, ...} → 패널 상태", "sim.py:355-374, shared/network-router/rules.sh:37"),
    ("s_crew", "in", "HTTP :8082 Basic(FIELD_CREW_*) · POST /tasks, GET /health · 엣지 OT 수신기만 호출(호스트 공개 경로 없음)", "{job_order_id, task, release_maintenance} → {status, reason, finding, effective, plant_duration_s, wall_s}", "sim.py:335-352, 2_ot/edge-nodered/src/crew_request.js:5-7"),
    ("s_boot", "in", "파일 /app/plant.yaml(PLANT_CONFIG) · 환경변수 SCAN_INTERVAL_MS·PHYSICS_TIME_SCALE·MODBUS_PORT·API_*_PORT·계정 3쌍", "태그·레지스터 지도·물리·고장·정비 작업 정의", "sim.py:39-46·65-66·378-381"),
    ("s_boot", "out", "stdout 로그(logging)", "고장 주입·패널 동작·정비 시작/완료 경고", "sim.py:33-37·151·174·186·257"),
  ],
  notes=[
    "스캔 주기 1초(scan_interval_ms 1000). 기준 시각 누적(nxt += interval)으로 밀림 없이 돌고, 스캔 예외는 기록만 하고 다음 스캔 계속 (plant.yaml:7, sim.py:393-402)",
    "물리 배속 600: 1스캔 = 설비 600초를 physics_max_substep_s 5초 이하 소구간 120개로 적분. 고장 만료·autopilot·열화는 소구간마다 갱신 (plant.yaml:11-12, plant.py:310-321)",
    "고장 시계: kind process 는 설비 시계(sim_time), event 는 스캔 시계(wall_time)로 만료 (plant.py:143-150·196-200)",
    "열화 고장(strainer·jacket·shaft·pt_drift·outlet_valve_stick·bearing)은 설비 1년 유지, 강사 초기화(clear_faults) 또는 정비 작업(field_apply)만 되돌린다 (plant.yaml:190-238, plant.py:164-175·413-466)",
    "스레드·잠금이 없다: Modbus 요청 처리·HTTP 핸들러·스캔이 같은 이벤트 루프에서 번갈아 실행되며 같은 ModbusSlaveContext·ReactorPlant 객체를 직접 읽고 쓴다 (sim.py:75-84·387-405)",
    "정비 작업은 job_order_id 당 1회: 진행 중이면 Future 를 shield 로 기다려 같은 결과를 돌려주고, 256건 넘으면 최근 128건만 남긴다. 대기 = duration_s ÷ 배속(실제 초), job_order_id 길이 8~80 아니면 400 (sim.py:158-191·345-346)",
    "정비 격리(isolated)는 작업 중에만 걸리고 finally 에서 풀린다. P-101 격리=펌프 정지, M-101=교반기 정지, CV-101=배출 밸브 닫힘, PT-101=지시값 BAD(-999999) (sim.py:172-179, plant.py:220·233·356-357·379)",
    "비상정지는 HR307 래치(패널 reset 전까지)이고, 가상설비가 PLC 명령과 무관하게 모든 구동기를 끈다 (sim.py:113·144-148, plant.py:220·258·278·379)",
    "릴리프 밸브 상한 7.5 barg: 물리 압력이 그 이상 오르지 않는다(PLC 인터록 6.5 barg 보다 높음) (plant.yaml:111-114, plant.py:55·368)",
    "Basic 인증 계정이 비어 있으면 /health 외 모든 요청 401(기본값으로 열리지 않음) (sim.py:222-235)",
    "PLC 가 붙기 전 초기값: 구동기 코일 4개 켬, 설정값 기본, 모드 스위치 REMOTE (sim.py:90-95)",
    "BAD_QUALITY(-999999.0) 센티널은 dropout 고장·PT-101 격리 때 float32 그대로 레지스터에 실린다 (plant.py:15·356-357·477-478)",
  ],
)

INTERNAL["plc"] = dict(
  runtime="OpenPLC Runtime v4.2.4(공식 이미지) · 프로그램은 이미지 빌드 때 OpenPLC Editor 4.3.2 CLI → C++ 컴파일로 설치 · 순환 태스크 task0 100 ms 1개(프로그램 main) · 플러그인 modbus_master(가상설비)·modbus_slave(:502) · REST/HTTPS :8443 · entrypoint.sh(bash)가 런타임 기동·계정·재적재. 경로 기준 1_control/plc-openplc/ (main.st.tmpl 과 생성본 project/pous/programs/main.st 는 줄 번호 같음)",
  parts=[
    ("p_master", "Modbus 마스터(원격 장치 plant)", "project/project.json:41-122", "100 ms 마다 HR0..37·HR300..308 읽고 코일0..3·HR100..102 씀"),
    ("p_slave", "Modbus 슬레이브(edge_server :502)", "project/project.json:30-40", "엣지에 %IW·%QW 읽기와 %MW 쓰기를 연다"),
    ("p_input", "1~3 입력 해독·통신/시각 감시·기동 초기화", "main.st.tmpl:114-141·project/pous/functions/words_to_real.st", "워드→REAL, 순번·시각 정지 감시, 첫 스캔 기준값"),
    ("p_field", "4~7 비상정지·모드 스위치·정비 모드·현장 버튼", "main.st.tmpl:144-180", "현장 패널 입력으로 mode·maint·cmd_* 갱신"),
    ("p_ilk", "8·9-1 고압 인터록", "main.st.tmpl:182-190·293-296", "PT-101≥6.5 트립 기억, ≤5.2 + 리셋 때만 해제"),
    ("p_cmd", "9 명령 두 채널(운전원·외부 요청)", "main.st.tmpl:192-291", "순번 변화 감지→범위·만료·중복·모드·물리 검사→반영·ACK"),
    ("p_sched", "10 생산 스케줄", "main.st.tmpl:298-326", "설비 시각으로 설정값 재추첨·완만 이동, 수동 유지 3000스캔"),
    ("p_out", "11~13 출력·되읽기 감시·상태", "main.st.tmpl:329-356", "구동기·설정값 출력, 전류 무반응 정지, 상태·하트비트"),
    ("p_retain", "RETAIN 영속", "main.st.tmpl:72-75·Dockerfile:34-41·project/devices/configuration.json", "maint·maint_op 를 retain.bin 에 저장(flush 5 s)"),
    ("p_loader", "런타임 기동·적재기", "entrypoint.sh:1-44", "런타임 실행, 관리자 계정 생성, 해시 다르면 REST 로 재적재·RUN"),
  ],
  links=[
    ("p_master", "p_input", "공유 메모리(OpenPLC 이미지 테이블 %IW)", "HR0..37→%IW0..37(계측·순번·설비 시각), HR300..308→%IW300..308(패널)", "project/project.json:52-85, main.st.tmpl:24-38"),
    ("p_out", "p_master", "공유 메모리(이미지 테이블 %QX·%QW)", "%QX0.0..0.3→코일0..3(FC15), %QW100..102→HR100..102(FC16)", "project/project.json:86-119, main.st.tmpl:330-336"),
    ("p_slave", "p_input", "공유 메모리(%MW0..1)", "엣지가 쓴 epoch 초 → now_s·time_ok", "main.st.tmpl:65·121·127-129"),
    ("p_slave", "p_cmd", "공유 메모리(%MW10..12·%MW20..27)", "운전원 순번·코드·값 / 요청 순번·코드·값·만료·수락·해시", "main.st.tmpl:66-70·193-203"),
    ("p_out", "p_slave", "공유 메모리(%QW100..118·%IW0..37)", "설정값·상태·ACK·하트비트(FC3), 계측 사본(FC4)을 엣지가 읽음", "main.st.tmpl:44-63·344-356"),
    ("p_input", "p_cmd", "프로그램 변수", "time_ok·now_s, 초기화 때 잡은 last_op_seq/last_rq_seq", "main.st.tmpl:121-139·225-227"),
    ("p_field", "p_cmd", "프로그램 변수", "mode·maint·estop(더 제한적인 쪽이 이김)", "main.st.tmpl:145-166·236-254"),
    ("p_field", "p_ilk", "프로그램 변수", "패널 리셋 카운터(%IW308) 변화 → ilk_reset", "main.st.tmpl:185-186"),
    ("p_cmd", "p_ilk", "프로그램 변수", "운전원 코드 12 → ilk_reset, 트립 중이면 펌프 기동 거부(5)", "main.st.tmpl:255-260·277·294"),
    ("p_cmd", "p_sched", "프로그램 변수", "설정값 수동 변경 시 hold_* := 3000스캔 동안 스케줄 제외", "main.st.tmpl:272-274·319-326"),
    ("p_field", "p_out", "프로그램 변수", "cmd_pump/agitator/heater/cooler·estop", "main.st.tmpl:147·173-176·330-333"),
    ("p_ilk", "p_out", "프로그램 변수", "interlock → q_pump 차단, cmd_pump := FALSE", "main.st.tmpl:187-190·330"),
    ("p_cmd", "p_out", "프로그램 변수", "cmd_*·sp_*·mode·maint·ACK 레지스터 값", "main.st.tmpl:267-289"),
    ("p_out", "p_field", "프로그램 변수(되먹임)", "되읽기 고장 시 cmd_pump/cmd_agitator := FALSE, fb_fault 기록", "main.st.tmpl:339-342"),
    ("p_retain", "p_field", "OpenPLC RETAIN(retain.bin)", "재시작 뒤 maint·maint_op 복원", "main.st.tmpl:72-75, Dockerfile:41"),
  ],
  ext=[
    ("p_master", "out", "Modbus/TCP plant-sim:502 unit 1 · 그룹 4개 각 cycleTime 100 ms · timeout 1000 ms · 오류 시 keep-last-value", "FC3 HR0..37·HR300..308 읽기, FC15 코일0..3·FC16 HR100..102 쓰기", "project/project.json:43-119"),
    ("p_slave", "in", "Modbus/TCP 0.0.0.0:502(엣지가 plc:502, unit 1)", "FC4 IR0..37(%IW), FC3 HR100..118(%QW), FC16 HR1024..1025(%MW0..1)·1034..1036(%MW10..12)·1044..1051(%MW20..27)", "project/project.json:30-40, shared/registry/generated/tags.json(plc.write 1024/1034/1044)"),
    ("p_loader", "both", "HTTPS 127.0.0.1:8443 /api(version·create-user·login·upload-file·compilation-status·start-plc) · 호스트 편집기는 라우터 28443 경유", "관리자 계정 생성, 프로그램 묶음 업로드·RUN", "entrypoint.sh:9-41, shared/network-router/rules.sh:40"),
    ("p_loader", "in", "파일 /opt/ar100/program.zip·program.sha256 ↔ build/.ar100_program.sha256", "설치 프로그램 해시 비교", "entrypoint.sh:10-11·22·40, Dockerfile:30·42"),
    ("p_retain", "out", "파일 /var/run/runtime/retain.bin(볼륨 plc-data)", "RETAIN 변수", "Dockerfile:34·41, compose.yml:118"),
  ],
  notes=[
    "한 스캔 순서: 1 입력 해독 → 2 현장 통신·시각 감시 → 3 기동 초기화 → (init_done 이후) 4 비상정지 → 5 모드 스위치 → 6 정비 모드 → 7 현장 버튼 → 8 인터록 트립 → 9 명령 채널(운전원 먼저, 외부 요청 다음) → 9-1 인터록 리셋 → 10 스케줄·hold 감소 → 11 출력 → 12 되읽기 감시 → 13 상태. 11~13 은 초기화 전에도 매 스캔 실행 (main.st.tmpl:114-356)",
    "Modbus 입출력과 프로그램 스캔은 이미지 테이블로만 만난다. 마스터 오류 때 keep-last-value 로 값이 굳으므로 PLC 는 순번(seq) 3초 정지로 현장 통신 끊김을 판단한다 (project/project.json:59·76, project/pous/programs/main.st:124-126)",
    "명령은 순번 레지스터가 바뀔 때만 새 명령. 엣지는 코드·값을 먼저 쓰고 그 쓰기 완료 뒤 순번을 쓴다 (main.st.tmpl:195·199, 2_ot/edge-nodered/src/operator_cmd.js:30-32, src/request_cmd.js:17-19)",
    "검사 우선순위: 코드(8)·범위(4) → 외부 요청만 시각 동기(10)·만료(6)·중복(7, 최근 해시 8개 고리) → LOCAL(1)·정비(2)·모드(3) → 비상정지(9) → 인터록(5) → 건조운전 LT-101<5.0(11). 결과는 ACK 로 %QW111..116 (main.st.tmpl:206-289)",
    "모드: 기동 시 REMOTE_MANUAL, 패널 스위치 LOCAL 이면 LOCAL, REMOTE 로 돌아오면 늘 REMOTE_MANUAL. REMOTE_AUTO 에선 운전원 채널은 모드·정비·리셋만, REMOTE_MANUAL 에선 외부 요청에 운전원 수락(%MW25) 필요 (main.st.tmpl:78·151-156·245-249)",
    "외부 요청 만료는 엣지가 1초마다 쓰는 epoch 초(%MW0..1)로 검사. 하위 워드가 5초 안 바뀌면 시각 동기 실패(10) (project/pous/programs/main.st:127-128·225-228)",
    "고압 인터록 6.5 barg 트립은 래치이고 펌프 명령도 끄므로 자동 재기동 없음. 해제는 PT-101≤5.2 이면서 패널 리셋 또는 운전원 코드 12 일 때만. -1000 이하(결측)는 판단 제외 (project/pous/programs/main.st:187·255·294)",
    "되읽기 감시: 기동 출력인데 IT-101/IT-102 < 1.0 A 가 5초 이어지면(현장 통신 정상일 때만) 명령을 끄고 fb_fault 세움 (project/pous/programs/main.st:339-342)",
    "생산 스케줄: 설비 시각(pts) 86400 s 마다 LCG 난수로 목표 재추첨, 5 s 소구간 복리(램프 7200 s)로 이동. 수동 설정 후 3000스캔(100 ms × 3000 = 300 s) 제외 (project/pous/programs/main.st:272-274·305-321, project/project.json:16)",
    "상수(트립·리셋·범위·타이머·스케줄)는 shared/registry/generate.py 가 템플릿 {{…}} 자리에 넣어 project/pous/programs/main.st 를 만든다 (main.st.tmpl:3, shared/registry/generate.py:400-468)",
    "entrypoint: /api/version 응답을 최대 180초 기다리고, 설치 해시가 이미지 묶음과 같으면 그대로, 다르면 업로드·컴파일(최대 300초)·start-plc. 실패 시 런타임 종료 (entrypoint.sh:14-43)",
  ],
)

INTERNAL["edge"] = dict(
  runtime="Node.js · Node-RED 5.0.7 1프로세스(단일 이벤트 루프) + node-red-contrib-modbus 5.60.2 · 흐름 탭 2개(edge 수집·명령, receiver OT 작업 요청 수신기) · Modbus 클라이언트 1개(plc:502) · MQTT 연결 2개(mqe: edge 계정 MQTT 3.1.1 clean session, mqr: ot-receiver 계정 MQTT 5 세션 유지 3600 s) · 컨텍스트: 탭별 flow 메모리 + 디스크 store(localfilesystem, flush 5 s) · V8 힙 128 MB. 경로 기준 2_ot/edge-nodered/ (flows.json 함수 본문 = src/*.js 와 동일)",
  parts=[
    ("e_poll", "Modbus 폴링·PLC 통신 상태", "flows.json:17-46·97-160·201-237·src/comm.js", "250 ms 마다 FC4 IR0..37·FC3 HR100..118 읽기, 끊기면 STALE"),
    ("e_values", "계측값 → UNS·edgex", "flows.json:161-180·src/values.js", "새 스캔만, deadband·최대간격으로 태그 발행, EdgeX 묶음"),
    ("e_status", "상태·ACK → UNS", "flows.json:181-200·src/status.js", "바뀐 상태 retain 발행, 48 s 전체 재발행, ACK 순번 변화 시 ACK"),
    ("e_saf", "끊김 버퍼·OT 허브 출력", "flows.json:238-311·src/saf.js·src/mqtt_state.js", "허브 끊기면 디스크 큐(최대 72000), 붙으면 순서대로 먼저 발행"),
    ("e_write", "PLC 쓰기(운전원·요청 명령·시각)", "flows.json:312-579·src/operator_cmd.js·src/request_cmd.js·src/time_sync.js·src/write_seq.js", "명령 토픽 → %MW 코드·값 쓰고 이어 순번, 1초 시각 동기"),
    ("e_metrics", "지표 /metrics", "flows.json:580-627·src/metrics.js", "발행 수·버퍼 길이·버린 수·PLC/허브 연결 Prometheus 텍스트"),
    ("r_intake", "요청 접수·스키마·수용 결정", "flows.json:628-748·src/receiver_request.js·src/receiver_invalid.js", "스키마 재검사→중복·허용·범위·만료·모드·정비 검사→자동/대기/거부"),
    ("r_state", "PLC 상태·ACK 구독", "flows.json:749-787·868-908·src/receiver_state.js·src/receiver_plc_ack.js", "PLC 모드·정비·RUN·현장통신 기억, PLC ACK → plc 단계 응답"),
    ("r_pending", "운전원 대기·결정", "flows.json:788-867·src/receiver_decision.js·src/receiver_timer.js", "대기 목록 60 s, 운전원 수락→명령(만료 +30 s) / 거부"),
    ("r_out", "묶음 풀기·발행·정비팀 호출", "flows.json:909-1013·src/batch.js·src/crew_request.js·src/crew_response.js", "응답·명령·대기 목록 MQTT 발행, 정비 작업은 HTTP POST"),
  ],
  links=[
    ("e_poll", "e_values", "Node-RED 메시지(와이어)", "msg.payload = IR 워드 38개 배열", "flows.json:97-128"),
    ("e_poll", "e_status", "Node-RED 메시지(와이어)", "msg.payload = HR 워드 19개 배열", "flows.json:129-160"),
    ("e_poll", "e_saf", "Node-RED 메시지(status 노드 → f_comm → 와이어)", "PLC-01/state/comm(retain), 끊김 시 STALE 태그 묶음 {batch}", "flows.json:201-237, src/comm.js:13-25"),
    ("e_values", "e_saf", "Node-RED 메시지(와이어)", "{batch:[태그 토픽…, edgex/telemetry]}", "flows.json:161-180, src/values.js:41"),
    ("e_status", "e_saf", "Node-RED 메시지(와이어)", "{batch:[PLC-01/status/*·{asset}/status/* retain, ack/operator, ack/request]}", "src/status.js:37-64"),
    ("e_status", "e_values", "flow 컨텍스트(메모리, edge 탭) plcStatus", "field_comm → 계측 품질 GOOD/STALE", "src/status.js:9, src/values.js:10-11"),
    ("e_values", "e_poll", "flow 컨텍스트 lastPub·lastValues", "끊김 때 마지막 값 STALE 재발행용", "src/values.js:35-36, src/comm.js:15-23"),
    ("e_write", "e_status", "flow 컨텍스트 opBySeq·jobByHash(쓰기) / opSeq·rqSeq(status 가 첫 읽기에 PLC 값으로 씨앗)", "ACK 에 원래 명령·job_order_id 붙이기, 순번 이어받기", "src/operator_cmd.js:23-28, src/request_cmd.js:9-14, src/status.js:45-61"),
    ("e_write", "e_saf", "Node-RED 메시지(f_opcmd 출력 2)", "엣지 거부 ACK(BAD_PAYLOAD·UNKNOWN_COMMAND·RETAINED_COMMAND·STALE_COMMAND·BAD_VALUE)", "flows.json:392-414, src/operator_cmd.js:7-22"),
    ("e_saf", "e_metrics", "flow 컨텍스트 safQueue(disk)·published·safDropped·mqttUp·plcOnline", "지표 값", "src/saf.js:6-23, src/comm.js:10, src/metrics.js:2-8"),
    ("r_intake", "r_out", "Node-RED 메시지(와이어)", "{batch:[receipt 응답, 명령 또는 _crew, 대기 목록]}", "flows.json:709-748, src/receiver_request.js:57-68"),
    ("r_state", "r_intake", "flow 컨텍스트(메모리, receiver 탭) plc", "mode·maintenance·run_state·field_comm", "src/receiver_state.js:5-7, src/receiver_request.js:43-48"),
    ("r_state", "r_pending", "flow 컨텍스트 plc", "수락 시점 모드·정비 재확인", "src/receiver_decision.js:26-37"),
    ("r_intake", "r_pending", "flow 컨텍스트 pending", "REMOTE_MANUAL 요청 저장(job·명령 토픽·해시·만료)", "src/receiver_request.js:63-67"),
    ("r_pending", "r_out", "Node-RED 메시지(와이어)", "operator 단계 응답·명령(operator_accepted 1)·_crew·대기 목록(retain)", "flows.json:788-867, src/receiver_decision.js:25-40, src/receiver_timer.js:7-27"),
    ("r_state", "r_out", "Node-RED 메시지(와이어)", "plc 단계 응답(ACCEPTED/REJECTED, plc_ack_code)", "flows.json:889-908, src/receiver_plc_ack.js:6-8"),
    ("r_out", "e_write", "MQTT(OT 허브 경유, ot-receiver → edge 계정)", "…/{asset}/cmd/request {job_order_id, code, value, expires_at, operator_accepted, job_hash}", "src/receiver_request.js:58-61, flows.json:477-517"),
    ("e_saf", "r_state", "MQTT(OT 허브 경유, edge → ot-receiver 계정)", "PLC-01/status/+(retain), PLC-01/ack/request", "src/status.js:16-26·55-61, flows.json:749-769·868-888"),
  ],
  ext=[
    ("e_poll", "out", "Modbus/TCP plc:502 unit 1 · FC4 IR0..37(quantity 38)·FC3 HR100..118(19) 각 250 ms · timeout 1000 ms·재접속 2000 ms", "PLC 계측 사본·설정값·상태·ACK", "flows.json:17-46·97-160"),
    ("e_write", "out", "Modbus/TCP plc:502 FC16 · HR1024..1025(%MW0..1, 1 s) · HR1035..1036 뒤 HR1034(%MW10..12) · HR1045..1051 뒤 HR1044(%MW20..27)", "epoch 초 / 운전원 코드·값·순번 / 요청 코드·값·만료·수락·해시·순번", "src/time_sync.js:4, src/operator_cmd.js:29-32, src/request_cmd.js:15-19, shared/registry/generated/tags.json(plc.write)"),
    ("e_write", "in", "MQTT ot-hub:1883(edge 계정, QoS 1) · AR-100/reaction/reactor-line-01/+/cmd/operator · …/+/cmd/request", "FUXA 운전원 명령 {command, value, ts} / 수신기 요청 명령", "flows.json:371-391·477-497"),
    ("e_saf", "out", "MQTT ot-hub:1883(edge 계정, clientid edge-01) · …/{asset}/tag/{TAG} QoS1 · edgex/telemetry · PLC-01/status/*·{asset}/status/* retain · PLC-01/ack/operator·ack/request · PLC-01/state/comm retain · birth/will EDGE-01/state/node retain", "계측 {ts, value, quality, seq, pts}·상태·ACK·통신 상태", "flows.json:47-77·258-275, shared/registry/generated/tags.json"),
    ("e_saf", "both", "파일 /data/context(localfilesystem 디스크 컨텍스트, 볼륨 edge-data)", "끊김 버퍼 safQueue", "settings.js:28-31, src/saf.js:6·14·20"),
    ("e_metrics", "in", "HTTP :1880 GET /metrics(인증 없음) · OT Prometheus agent·compose healthcheck", "Prometheus 텍스트 지표 5개", "flows.json:580-627, src/metrics.js, compose.yml:168-169"),
    ("r_intake", "in", "MQTT ot-hub:1883(ot-receiver 계정, MQTT 5, clientid ot-receiver, 세션 유지) · AR-100/request/in QoS1(DMZ 에서 브리지 in)", "작업 요청(job_request 스키마)", "flows.json:78-96·628-648"),
    ("r_intake", "in", "파일 /opt/ar100/registry/tags.json·work_masters.ot.json·schemas/job_request.schema.json(functionGlobalContext)", "신호·명령·레지스터 지도·허용 작업 표·요청 스키마", "settings.js:3·21-26, Dockerfile:8"),
    ("r_state", "in", "MQTT ot-hub(ot-receiver) · AR-100/reaction/reactor-line-01/PLC-01/status/+ · …/PLC-01/ack/request QoS1", "PLC 상태·요청 ACK", "flows.json:749-769·868-888"),
    ("r_pending", "in", "MQTT ot-hub(ot-receiver) · AR-100/reaction/reactor-line-01/request/decision QoS1(FUXA 발행)", "{job_order_id, decision, ts}", "flows.json:788-808"),
    ("r_out", "out", "MQTT ot-hub(ot-receiver 계정) · AR-100/response/{job_order_id} · …/{asset}/cmd/request · …/request/pending(retain)", "단계별 응답(receipt·operator·plc·field)·명령·대기 목록", "flows.json:996-1013, shared/registry/generated/tags.json(request)"),
    ("r_out", "out", "HTTP plant-sim:8082 POST /tasks · Basic(FIELD_CREW_*) · 요청 시간 한도 60 s", "{job_order_id, task, release_maintenance} → 정비 결과", "src/crew_request.js:4-8, flows.json:952-975"),
  ],
  notes=[
    "두 Modbus 읽기 노드는 250 ms 마다 돌지만 계측 발행은 가상설비 순번(seq, PLC 경유)이 바뀔 때만(가상설비 스캔 1 s) (flows.json:97-160, src/values.js:6-9)",
    "태그 보고 조건: 처음·품질 변화·deadband 초과·설비 시각(pts) 기준 최대 간격 초과. 값 ≤ -1000·NaN 은 null·BAD, PLC 현장 통신 0 이면 STALE (src/values.js:20-29)",
    "상태는 바뀐 것만 retain 으로, 48 s(state_max_interval_wall_s)마다 전부 재발행. 하트비트가 2 s 넘게 그대로면 run_state STOP (src/status.js:13-24·34-42)",
    "기동 뒤 첫 상태 읽기는 ACK 를 내지 않고 PLC 의 ACK 순번으로 opSeq·rqSeq 를 이어받는다(순번 겹침 방지) (src/status.js:44-48)",
    "PLC 쓰기는 2단 체인: 코드·값 flex-write 의 성공 출력 뒤 f_opseq/f_rqseq 가 순번만 쓴다. 첫 쓰기 실패(출력 2)는 아무 데도 연결 안 됨 → 순번 미기록 (flows.json:415-576)",
    "엣지는 운전원 명령의 모양만 거른다(retain·±5 s 넘은 ts·모르는 명령·정수 아닌 값 → source edge 거부 ACK). 허용 판단은 PLC. 요청 명령 형식 오류·retain 은 경고만 하고 버림 (src/operator_cmd.js:1-22, src/request_cmd.js:4-8)",
    "끊김 버퍼: 연결 판정은 mq_out 상태 문자열('connected'). 끊긴 동안 디스크 컨텍스트에 쌓고 72000 넘으면 새 메시지를 버리고 셈. 다시 붙으면 _flush 로 쌓인 것 먼저 (src/saf.js:4-24, src/mqtt_state.js:2-7)",
    "수신기 탭 MQTT 출력에는 끊김 버퍼가 없다(OT 허브 안에서만 발행) (src/batch.js:1-2, flows.json:909-931)",
    "수신기 검사 순서: 스키마(json 노드, msg.schema) → 중복(seen, expires_at+60 s 까지) → 허용 작업 → 설비 일치 → 파라미터 범위 → 만료 → PLC RUN·현장통신 → LOCAL → 정비 필요/정비 중 → 모드별(REMOTE_AUTO 자동 수용, REMOTE_MANUAL 대기) (flows.json:649-708, src/receiver_request.js:24-68)",
    "운전원 대기: 1초 inject 로 60 s 넘으면 OPERATOR_TIMEOUT. 결정은 ts ±10 s 밖이면 무시. 수락 시 만료를 지금+30 s 로 새로 잡는다 (src/receiver_timer.js:7-13, src/receiver_decision.js:7-8·39)",
    "현장 정비 작업(kind field)은 PLC 를 거치지 않고 수신기가 가상설비 :8082 로 직접 HTTP. 응답 실패는 status UNKNOWN, 재전송 없음 (src/receiver_request.js:5·57, src/crew_response.js:1·11-12)",
    "job_hash = sha256(job_order_id) 앞 8 hex(0 이면 1) → PLC 중복 검사와 ACK 의 job_order_id 역조회에 쓴다 (src/receiver_request.js:49, src/status.js:56-57)",
    "편집기 :1880 은 로그인 필요·읽기 전용, 흐름은 기동 때마다 이미지 안 생성본으로 덮어쓴다(호스트는 라우터 21880 경유) (settings.js:12-19, start.sh:4-5, shared/network-router/rules.sh:39)",
    "수신기의 PLC 상태(plc)는 메모리 flow 컨텍스트라 재시작 뒤엔 retain 상태 토픽을 다시 받아야 채워진다 (settings.js:29, src/receiver_state.js:5-7)",
  ],
)

INTERNAL["router"] = dict(
  runtime="Alpine 3.24 · /bin/sh rules.sh 1프로세스(규칙 적재 후 60초 무한 루프) · 커널 netfilter(iptables filter·nat) · 망 3개에 붙음(it 30.2·ot 10.2·dmz 20.2, 별칭 dmz-broker·dmz-prom 등) · ip_forward=1 · NET_ADMIN. 경로 기준 shared/network-router/",
  parts=[
    ("n_base", "기본 정책·상태 추적", "rules.sh:15-20", "INPUT·FORWARD DROP, ESTABLISHED/RELATED 허용"),
    ("n_dnat", "허용 경로 DNAT(nat PREROUTING)", "rules.sh:22-23·26-40", "출발 대역·라우터 주소·포트 → 실제 목적지로 변환"),
    ("n_fwd", "허용 경로 FORWARD(filter)", "rules.sh:24·26-40", "변환된 목적지·포트의 NEW 연결만 통과"),
    ("n_snat", "MASQUERADE(nat POSTROUTING)", "rules.sh:41-42", "DMZ·OT 로 가는 패킷 출발 주소를 라우터로"),
    ("n_drop", "구역별 차단·카운터", "rules.sh:43-47", "ot·dmz·it·기타 출발 FORWARD 를 주석 달린 DROP 으로 셈"),
    ("n_log", "차단 기록 루프", "rules.sh:50-57", "60초마다 DROP 카운터가 바뀌면 stdout 기록"),
  ],
  links=[
    ("n_dnat", "n_fwd", "커널 netfilter 체인 순서(PREROUTING → FORWARD)", "목적지가 바뀐 NEW 패킷", "rules.sh:23-24"),
    ("n_fwd", "n_snat", "커널 netfilter 체인 순서(FORWARD → POSTROUTING)", "허용된 패킷 출발지 변환", "rules.sh:24·41-42"),
    ("n_base", "n_fwd", "conntrack(FORWARD 첫 규칙)", "응답·연관 패킷은 ESTABLISHED 로 먼저 통과", "rules.sh:19-20"),
    ("n_fwd", "n_drop", "FORWARD 체인 순서(허용 규칙 뒤에 붙음)", "허용에 안 걸린 패킷", "rules.sh:24·44-47"),
    ("n_drop", "n_log", "자식 프로세스 stdout(iptables -L FORWARD -v -n -x | awk)", "구역별 누적 패킷 수", "rules.sh:51-55"),
  ],
  ext=[
    ("n_dnat", "in", "OT(.10.0/24) → 10.2:1883 ⇒ DMZ 브로커 .20.11:1883", "OT 허브 브리지 MQTT", "rules.sh:27"),
    ("n_dnat", "in", "OT → 10.2:9090 ⇒ DMZ Prometheus .20.13:9090", "OT 감시 remote_write", "rules.sh:28"),
    ("n_dnat", "in", "IT(.30.0/24) → 30.2:1883·8086·9090·8088 ⇒ DMZ 브로커 .20.11·Influx .20.12·Prometheus .20.13·요청 게이트웨이 .20.14", "구독·조회·federate·작업 요청 POST", "rules.sh:30-33"),
    ("n_dnat", "in", "호스트 게이트웨이 .30.1/32 → 30.2:21881·28080·28081·21883·21880·28443 ⇒ FUXA 게이트 .10.16:1882·가상설비 .10.11:8080·8081·OT 허브 .10.12:1883·엣지 .10.13:1880·PLC .10.14:8443", "사람·도구용 OT 화면·API", "rules.sh:35-40"),
    ("n_dnat", "in", "호스트 127.0.0.1 공개 포트(PORT_FUXA 등 8개) → 라우터 21881·28080·28081·21883·21880·28443·1883·8086", "docker 포트 공개", "compose.yml:80-88"),
    ("n_dnat", "out", "Docker HEALTHCHECK 10 s(iptables -t nat -S PREROUTING | grep -q DNAT)", "규칙 적재 여부", "Dockerfile:5"),
    ("n_log", "out", "stdout", "[router] 규칙 적재 수·차단 누적(패킷)", "rules.sh:48·55"),
  ],
  notes=[
    "새 연결 허용은 OT→DMZ 2개, IT→DMZ 4개, 호스트→OT 6개뿐. DMZ→OT·DMZ→IT·IT→OT 새 연결 규칙은 없다(응답만 conntrack) (rules.sh:3-4·26-40)",
    "ot-net·dmz-net 은 internal 망이라 컨테이너는 같은 망의 라우터 주소로 접속하고(ot-net 에서 별칭 dmz-broker·dmz-prom = 10.2), 라우터가 DNAT 한다 (rules.sh:5-7, compose.yml:77-79)",
    "MASQUERADE 때문에 DMZ·OT 목적지는 출발지를 라우터 주소로 본다(호스트 요청도 가상설비·PLC 에는 라우터에서 온 것으로 보임) (rules.sh:41-42)",
    "같은 망 안 통신(엣지→PLC, PLC→가상설비, 수신기→가상설비 :8082)은 라우터를 거치지 않는다. 가상설비 :8082·:502 는 호스트 공개 경로가 없다 (rules.sh:35-40)",
    "기동 때 모든 규칙을 비우고(-F) 다시 적재, set -eu 라 명령 실패 시 종료 (rules.sh:8·16)",
    "차단 기록은 카운터가 바뀔 때만 1분 간격, 패킷 단위 LOG 규칙은 없다 (rules.sh:50-57)",
  ],
)

INTERNAL["hub"] = dict(
  runtime="Eclipse Mosquitto 2.1.2(eclipse-mosquitto:2.1.2-alpine) · 1프로세스 · shared/mosquitto/entrypoint.sh 가 계정 파일 생성·설정 치환 후 mosquitto 사용자로 exec. 경로 기준 2_ot/factory-broker-mosquitto/",
  parts=[
    ("h_entry", "기동 준비(계정·치환)", "shared/mosquitto/entrypoint.sh:1-24", "MQTT_USERS 로 passwd 생성, __VAR__ 치환, 권한 0700"),
    ("h_listener", "리스너 1883·인증", "mosquitto.conf:3-7", "익명 금지, 비밀번호 파일, ACL 파일"),
    ("h_acl", "계정별 ACL", "acl:1-36", "edge·ot-receiver·fuxa·viewer·ot-exporter 최소 권한"),
    ("h_store", "영속·대기열 한도", "mosquitto.conf:8-23", "디스크 영속 60 s, 대기열 72000건·32 MB, 세션 1 h 만료"),
    ("h_bridge", "DMZ 브리지(connection dmz)", "mosquitto.conf:25-44", "MQTT 5 브리지, out 데이터·응답, in 요청·경고"),
  ],
  links=[
    ("h_entry", "h_listener", "로컬 파일(/mosquitto/config/passwd·mosquitto.conf)", "계정 해시·치환된 설정", "shared/mosquitto/entrypoint.sh:8-20·24"),
    ("h_entry", "h_acl", "로컬 파일 복사(/cfg/acl → /mosquitto/config/acl)", "ACL", "shared/mosquitto/entrypoint.sh:21"),
    ("h_listener", "h_acl", "브로커 내부 권한 검사", "클라이언트 발행·구독 토픽 허용 여부", "mosquitto.conf:7"),
    ("h_bridge", "h_store", "브로커 내부 대기열·영속", "DMZ 끊김 동안 out 메시지 보관(cleansession false, 세션 만료 3600 s)", "mosquitto.conf:14-18·29·34"),
    ("h_bridge", "h_listener", "브로커 내부 라우팅(ACL 미적용이라고 주석)", "in 토픽 AR-100/request/in·AR-100/alert/display 를 로컬 구독자에게", "mosquitto.conf:42-44, acl:1"),
  ],
  ext=[
    ("h_listener", "in", "MQTT :1883(edge·ot-receiver·fuxa·viewer·ot-exporter) · 호스트는 라우터 21883 경유", "UNS 계측·상태·ACK·명령·요청·결정", "mosquitto.conf:4, shared/network-router/rules.sh:38, compose.yml:132"),
    ("h_bridge", "out", "MQTT 5 dmz-broker:1883(라우터 10.2 → .20.11) · remote_username bridge-ot · clientid ot-hub-bridge · out QoS1: AR-100/reaction/+/+/tag/+·status/+·ack/+·state/+, AR-100/response/#", "계측·상태·ACK·통신 상태·요청 응답", "mosquitto.conf:26-41, shared/network-router/rules.sh:27"),
    ("h_bridge", "in", "같은 브리지 in: AR-100/request/in QoS1, AR-100/alert/display QoS0", "DMZ 작업 요청·분석 경고", "mosquitto.conf:43-44"),
    ("h_store", "both", "파일 /mosquitto/data/(볼륨 ot-hub-data)", "보존 메시지·세션·대기열", "mosquitto.conf:8-10, compose.yml:139"),
    ("h_listener", "out", "$SYS 10 s 주기(viewer·ot-exporter 읽기)", "브로커 지표", "mosquitto.conf:19, acl:32·36"),
  ],
  notes=[
    "브리지는 OT 허브가 먼저 연다(DMZ→OT 새 연결 없음). 재시도 restart_timeout 1~10 s (mosquitto.conf:2·35)",
    "edgex/telemetry·request/pending·request/decision·cmd/* 는 브리지 out 대상이 아니라 OT 안에만 머문다 (mosquitto.conf:37-41)",
    "대기열 한도를 넘으면 새 메시지를 버리고 $SYS dropped 로 센다(.env MQTT_MAX_QUEUED_MESSAGES=72000, 엣지 끊김 버퍼와 같은 값) (mosquitto.conf:11-14, .env:112)",
    "ACL: edge 는 cmd/+ 읽기만·tag/status/ack/state·edgex 쓰기, ot-receiver 는 cmd/request·pending·response 쓰기와 request/in·decision·PLC-01 status/ack 읽기, fuxa 는 AR-100/reaction/# 읽기와 cmd/operator·decision 쓰기 (acl:3-26)",
  ],
)

# 주의: 문서·주석과 코드가 다른 곳
# 1. PLC 헤더(main.st.tmpl:6-7)는 '%IW0..23 계측 12점 ← HR0..23' 이지만 실제 마스터 읽기는 HR0..37(38워드, 17점: FT-103·TT-103·TT-104·PDT-103·PT-102 가 28..37) (project/project.json:57-58, plant.yaml:17-35). 엣지도 노드 이름 'FC4 0..27'·values.js:1 주석 '0..27 = 값 12점' 이지만 quantity 38 (flows.json:97-128, tags.json read_values.count 38).
# 2. PLC 헤더 명령 코드 목록(main.st.tmpl:16-17)에 코드 12(인터록 리셋, 운전원 채널 전용)가 빠져 있다 (main.st.tmpl:206·277).
# 3. plant.py:13-14 주석은 'Telegraf 브리지가 BAD_QUALITY 를 걸러 Kafka 결측' 이라 하지만, 이 다섯 서비스 경로에서는 엣지 values.js:20 이 -1000 이하를 null·BAD 로 바꾼다(Telegraf 는 이 경로에 없음).
# 4. 가상설비 Dockerfile 은 EXPOSE 502 8080 8081 이고 ENV 에 API_CREW_PORT 가 없으며 기동 로그(sim.py:384-385)도 정비팀 포트를 빼먹는다. 실제로는 기본값 8082 로 뜬다 (sim.py:43·387-388).
# 5. sim.py:3 'soft-PLC 하나만 붙는다'·plant.yaml:37 '쓰는 것은 soft-PLC 하나뿐' 은 코드가 강제하지 않는다(Modbus 서버에 출처 검사 없음, sim.py:405). OT 망 안 통제는 망 구성에 의존(라우터는 :502 를 호스트에 열지 않음).
# 6. batch.js:2 '같은 묶음 함수를 엣지·수신기가 함께 쓴다' — edge 탭에는 묶음 노드가 없고 edge 함수들은 {batch} 를 f_saf 로 바로 보낸다(saf.js:7 이 batch 를 풂). f_batch 는 receiver 탭에만 있다 (flows.json:909-931).
# 7. (조사 지시문 대비) 수신기의 결정은 PLC %MW20 을 직접 쓰지 않는다: 수신기가 …/cmd/request 를 MQTT 로 내고 edge 탭 f_rqcmd 가 받아 %MW20..27 을 쓴다 (src/receiver_request.js:4·58-61, src/request_cmd.js:1·15-19).

# ceco_demo 내부 구조 조사 F — gw · loader · coll · hist · flink · trainer · am
# 근거: D:\work\study\ceco_demo 현재 작업 트리(docs/ 제외). 경로는 저장소 루트 기준.

INTERNAL["gw"] = dict(
  runtime="Node.js · Node-RED 5.0.7(nodered/node-red:5.0.7) 1프로세스 · 단일 이벤트 루프 · 편집기 꺼짐(httpAdminRoot false) · 흐름 탭 1개(gw) · flow 컨텍스트는 기본 메모리 저장소(settings.js 에 contextStorage 없음)",
  parts=[
    ("http_in", "HTTP 입력 노드 3개(/requests·/health·/metrics)", "3_dmz/gateway-nodered/flows.json:28-45,169-186,207-224", "POST /requests 원문 본문(skipBodyParsing) 수신, GET 2개"),
    ("check", "1차 검사(function f_check)", "3_dmz/gateway-nodered/src/check.js:1-80 (flows.json:46-68)", "토큰·스키마·허용목록·나이·중복·연결 검사 후 거부 또는 발행"),
    ("mq_out", "MQTT 발행(mq_out)+브로커 설정(mqg)", "3_dmz/gateway-nodered/flows.json:9-27,69-86", "MQTT 5 QoS1 로 요청 토픽 발행, 만료 30 s"),
    ("ack", "발행 확인(complete done_pub)+수용 응답(f_ack)", "3_dmz/gateway-nodered/flows.json:87-123, src/ack.js:1-12", "발행 완료 시 pending 지우고 202 ACCEPTED"),
    ("state", "연결 상태 기억(status st_mq+f_state)", "3_dmz/gateway-nodered/flows.json:135-168, src/broker_state.js:1-3", "mq_out 상태가 초록이면 connected=true"),
    ("ctx", "flow 컨텍스트(counters·seen·pending·connected)", "3_dmz/gateway-nodered/src/check.js:8-10,54-60", "검사·응답·지표가 공유하는 메모리 상태"),
    ("glob", "전역 컨텍스트(registry·allow·validateJob·crypto)", "3_dmz/gateway-nodered/settings.js:10-16", "기동 때 등록부 JSON·Ajv 스키마 검사기 적재"),
    ("obs", "상태·지표 응답(f_health·f_metrics)", "3_dmz/gateway-nodered/src/health.js:1-2, src/metrics.js:1-8", "broker 연결 여부, Prometheus 텍스트 생성"),
    ("resp", "HTTP 응답(resp)", "3_dmz/gateway-nodered/flows.json:124-134", "msg.statusCode·payload 로 동기 응답"),
  ],
  links=[
    ("http_in", "check", "그 밖(Node-RED 와이어, 같은 이벤트 루프 안 msg 전달)", "msg.req·msg.res·원문 payload", "3_dmz/gateway-nodered/flows.json:40-44"),
    ("glob", "check", "함수 호출(global.get)", "crypto·allow·validateJob·registry.request.in_topic", "3_dmz/gateway-nodered/src/check.js:4-6,77"),
    ("check", "ctx", "공유 메모리(flow 컨텍스트, 잠금 없음·단일 이벤트 루프)", "counters 증가, seen[jid]=만료시각, pending[_msgid]=true", "3_dmz/gateway-nodered/src/check.js:13-14,54-60"),
    ("check", "resp", "그 밖(Node-RED 와이어 출력 1)", "거부 응답(401/400/409/422/503)", "3_dmz/gateway-nodered/flows.json:61-63"),
    ("check", "mq_out", "그 밖(Node-RED 와이어 출력 2)", "검사 통과 요청(+expires_at, topic, messageExpiryInterval=30)", "3_dmz/gateway-nodered/flows.json:64-66"),
    ("check", "resp", "콜백(setTimeout 2000 ms → node.send 출력 1)", "PUBACK 없을 때 503 BROKER_UNAVAILABLE", "3_dmz/gateway-nodered/src/check.js:62-76"),
    ("mq_out", "ack", "콜백(complete 노드: mq_out 의 done 이벤트)", "발행 끝난 msg(res 포함)", "3_dmz/gateway-nodered/flows.json:87-103"),
    ("ack", "ctx", "공유 메모리(flow 컨텍스트)", "pending 삭제, counters.accepted 증가", "3_dmz/gateway-nodered/src/ack.js:2-8"),
    ("ack", "resp", "그 밖(Node-RED 와이어)", "202 ACCEPTED·job_order_id·expires_at", "3_dmz/gateway-nodered/flows.json:118-122"),
    ("mq_out", "state", "콜백(status 노드: mq_out 상태 변경 이벤트)", "msg.status.fill", "3_dmz/gateway-nodered/flows.json:135-150"),
    ("state", "ctx", "공유 메모리(flow 컨텍스트)", "connected 참/거짓", "3_dmz/gateway-nodered/src/broker_state.js:2"),
    ("http_in", "obs", "그 밖(Node-RED 와이어)", "GET /health·/metrics 요청", "3_dmz/gateway-nodered/flows.json:181-185,219-223"),
    ("ctx", "obs", "공유 메모리(flow.get)", "connected, counters", "3_dmz/gateway-nodered/src/metrics.js:2-5"),
    ("obs", "resp", "그 밖(Node-RED 와이어)", "상태 JSON, Prometheus 텍스트", "3_dmz/gateway-nodered/flows.json:201-205,239-243"),
  ],
  ext=[
    ("http_in", "in", "HTTP :8088 POST /requests (Authorization: Bearer GATEWAY_CLIENT_TOKEN)", "승인된 작업 요청 JSON(it-collector ⑦ 발송 스트림이 보냄)", "3_dmz/gateway-nodered/flows.json:35-36, settings.js:7"),
    ("http_in", "in", "HTTP :8088 GET /health", "docker healthcheck", "compose.yml:302"),
    ("http_in", "in", "HTTP :8088 GET /metrics", "DMZ Prometheus 수집(job dmz-gateway)", "shared/monitoring-prometheus/dmz.yml:6-7"),
    ("mq_out", "out", "MQTT 5 tcp dmz-broker:1883, client dmz-gateway, 계정 gateway, 토픽 AR-100/request/in, QoS1, message expiry 30 s, retain 없음", "검사 통과 작업 요청", "3_dmz/gateway-nodered/flows.json:10-27,75-78; src/check.js:77-78; shared/registry/generated/tags.json:512"),
    ("glob", "in", "파일 /opt/ar100/registry/tags.json, work_masters.allow.json, schemas/job_request.schema.json(이미지에 복사)", "등록부·허용 목록·JSON 스키마", "3_dmz/gateway-nodered/settings.js:12-15; Dockerfile:5"),
    ("check", "in", "환경변수 GATEWAY_CLIENT_TOKEN", "고정 시간 비교용 토큰", "3_dmz/gateway-nodered/src/check.js:21-23; compose.yml:297"),
  ],
  notes=[
    "검사 순서: 토큰(401) → JSON 파싱(400) → 스키마 → 허용 작업 ID → 설비 일치 → 파라미터 존재·범위 → 요청자(ID·종류) → 승인자 → 나이 10 s(미래 2 s 허용) → 중복(409) → 브로커 연결(503). 기본 거부 코드는 422 (3_dmz/gateway-nodered/src/check.js:12-53)",
    "응답은 발행 확인 뒤에 낸다: pending 에 _msgid 를 넣고 2 s 타이머를 건다. complete 노드가 먼저 오면 202, 타이머가 먼저면 503 이고 seen 에서 그 ID 를 지워 재요청을 허용한다 (3_dmz/gateway-nodered/src/check.js:58-76, src/ack.js:2-5)",
    "중복 판정 창은 만료 30 s + 5 s = 35 s. 매 요청마다 지난 seen 항목을 지운다 (3_dmz/gateway-nodered/src/check.js:3,50-54)",
    "브로커가 끊겼으면(connected 거짓) 기다리지 않고 바로 503. 재연결 간격 1 s (3_dmz/gateway-nodered/src/check.js:53; settings.js:9)",
    "공장 상태(모드)는 보지 않는다. 경계 검사만 하고 최종 판단은 OT 쪽 (3_dmz/gateway-nodered/flows.json:7)",
    "flow 컨텍스트는 메모리라 재시작하면 counters·seen·pending 이 비워진다(contextStorage 설정 없음) (3_dmz/gateway-nodered/settings.js:4-22)",
    "src/*.js 는 flows.json 함수 본문의 원본이다(5개 모두 문자열 일치 확인). 이미지에는 flows.json 만 복사되고 기동 때 /data 로 복사해 쓴다 (3_dmz/gateway-nodered/Dockerfile:4; start.sh:5-6; shared/registry/generate.py:349)",
  ],
)

INTERNAL["loader"] = dict(
  runtime="Go · Bento 1.21.2 streams 모드 1프로세스 · 스트림 2개(loader, sys_metrics) · 공통 HTTP :4195(지표·ready) · GOMEMLIMIT 64MiB",
  parts=[
    ("l_in", "loader 입력(MQTT 구독)", "3_dmz/loader-bento/loader.yaml:5-16", "DMZ 브로커 tag/status/state 토픽 QoS1 구독"),
    ("l_buf", "loader 메모리 버퍼(32 MiB)", "3_dmz/loader-bento/loader.yaml:18-20", "출력이 막혀도 MQTT 입력을 계속 받음"),
    ("l_map", "loader 변환(Bloblang → 라인 프로토콜)", "3_dmz/loader-bento/loader.yaml:21-37", "process_raw·plc_status 행 생성, 나머지 버림"),
    ("l_out", "loader 출력(InfluxDB HTTP 쓰기)", "3_dmz/loader-bento/loader.yaml:38-52", "500건/1 s 묶어 lines 로 POST, 재시도"),
    ("s_in", "sys_metrics 입력($SYS 구독)", "shared/bento/broker-exporter/sys_metrics.yaml:5-14", "Mosquitto $SYS 토픽 7개 QoS0 구독"),
    ("s_met", "sys_metrics 변환+metric 처리기", "shared/bento/broker-exporter/sys_metrics.yaml:15-25", "숫자만 남겨 gauge mosquitto_sys{topic} 갱신"),
    ("s_out", "sys_metrics 출력(drop)", "shared/bento/broker-exporter/sys_metrics.yaml:26-27", "메시지는 버리고 지표만 남김"),
    ("http", "공통 HTTP 서버 :4195", "shared/bento/bento-global.yaml:2-5", "/ready·/metrics(Prometheus) 노출"),
  ],
  links=[
    ("l_in", "l_buf", "그 밖(Bento 스트림 내부 트랜잭션 채널)", "MQTT 메시지+meta mqtt_topic", "3_dmz/loader-bento/loader.yaml:5-20"),
    ("l_buf", "l_map", "그 밖(Bento 메모리 버퍼 → 파이프라인)", "버퍼된 메시지", "3_dmz/loader-bento/loader.yaml:18-23"),
    ("l_map", "l_out", "그 밖(Bento 파이프라인 → 출력, 출력 쪽 배칭)", "라인 프로토콜 한 줄", "3_dmz/loader-bento/loader.yaml:28-52"),
    ("s_in", "s_met", "그 밖(Bento 스트림 내부 채널)", "$SYS 값 문자열", "shared/bento/broker-exporter/sys_metrics.yaml:15-25"),
    ("s_met", "http", "공유 메모리(Bento 프로세스 공통 지표 레지스트리)", "mosquitto_sys gauge", "shared/bento/bento-global.yaml:4-5; sys_metrics.yaml:20-25"),
    ("s_met", "s_out", "그 밖(Bento 파이프라인 → 출력)", "처리된 메시지(버려짐)", "shared/bento/broker-exporter/sys_metrics.yaml:26-27"),
  ],
  ext=[
    ("l_in", "in", "MQTT tcp dmz-broker:1883, client dmz-loader, 계정 dmz-loader, clean_session, 토픽 AR-100/reaction/+/+/tag/+ · status/+ · state/+, QoS1", "OT 원시 계측값·PLC 상태", "3_dmz/loader-bento/loader.yaml:6-16"),
    ("l_out", "out", "HTTP POST http://dmz-influx:8086/api/v2/write?org=INFLUX_ORG&bucket=DMZ_INFLUX_BUCKET&precision=ns (Token DMZ_INFLUX_TOKEN)", "measurement process_raw(tag·quality, value·seq·pts) · plc_status(kind·name, text 또는 num)", "3_dmz/loader-bento/loader.yaml:29-44"),
    ("s_in", "in", "MQTT BROKER_URL=tcp://dmz-broker:1883, 계정 dmz-exporter, client dmz-exporter-sys, $SYS/broker/... 7개, QoS0", "브로커 연결 수·메시지 수·브리지 상태·uptime", "shared/bento/broker-exporter/sys_metrics.yaml:6-14; compose.yml:277-279"),
    ("http", "out", "HTTP :4195 /metrics, /ready", "Bento 지표(input_received{stream} 등)+mosquitto_sys, healthcheck", "shared/monitoring-prometheus/dmz.yml:4-5; compose.yml:286"),
  ],
  notes=[
    "품질 BAD 등 value 가 null 인 tag 메시지는 행을 만들지 않는다(공백 유지). ts 가 없으면 적재 시각(ns) 사용 (3_dmz/loader-bento/loader.yaml:3,27-30)",
    "plc_status 값이 문자열이면 text 필드, 불리언이면 1/0, 그 밖은 숫자 num 필드 (3_dmz/loader-bento/loader.yaml:31-35)",
    "출력: max_in_flight 1, 재시도 1 s 부터 최대 10 s 백오프, 500건 또는 1 s 마다 묶음 (3_dmz/loader-bento/loader.yaml:45-52)",
    "메모리 버퍼 32 MiB 는 프로세스가 죽으면 잃는다 (3_dmz/loader-bento/loader.yaml:17-20)",
    "두 스트림은 같은 프로세스·같은 :4195 를 쓰고 스트림 이름은 파일명(loader, sys_metrics). Prometheus 규칙이 input_received{stream=loader} 정지를 본다 (compose.yml:270; shared/monitoring-prometheus/rules.yml:27)",
  ],
)

INTERNAL["coll"] = dict(
  runtime="Go · Bento 1.21.2 streams 모드 1프로세스(it-collector) · /cfg/streams 디렉터리의 스트림 7개(①③④⑤⑥⑦⑧, ② 파일 없음) · 공통 HTTP :4195 · GOMEMLIMIT 96MiB",
  parts=[
    ("s1", "① dmz_to_kafka: MQTT → 메모리 버퍼 → 분기 매핑 → Kafka", "4_it/collector-bento/streams/dmz_to_kafka.yaml:1-50", "DMZ 브로커 값을 토픽 3개로 나눠 Kafka 로"),
    ("s3", "③ display_to_dmz: Kafka → MQTT", "4_it/collector-bento/streams/display_to_dmz.yaml:1-17", "alerts.display 를 DMZ 표시 토픽에 retained 발행"),
    ("s4", "④ alerts_to_alertmanager: Kafka → 라벨 매핑 → HTTP", "4_it/collector-bento/streams/alerts_to_alertmanager.yaml:1-41", "sensor.alerts 를 Alertmanager alert 로(끝 +60 s)"),
    ("s5", "⑤ status_to_alertmanager: Kafka → 억제 상태 매핑 → HTTP", "4_it/collector-bento/streams/status_to_alertmanager.yaml:1-43", "정비·정지·운전 꺼짐을 억제 alert 로"),
    ("s6", "⑥ alertmanager_to_display: HTTP 수신 → 분해 → SQL 기록 → Kafka", "4_it/collector-bento/streams/alertmanager_to_display.yaml:1-70", "webhook 을 ISA-18.2 기록, 새 분석 alert 만 표시"),
    ("s7", "⑦ request_dispatch: Kafka → SQL → HTTP → SQL → Kafka 2곳", "4_it/collector-bento/streams/request_dispatch.yaml:1-93", "승인 요청을 게이트웨이로 1회 발송·결과 기록"),
    ("s8", "⑧ mes_requester: HTTP 수신 → SQL → 동기 응답 → Kafka", "4_it/collector-bento/streams/mes_requester.yaml:1-55", "MES 흉내 생산 지시를 승인 요청으로"),
    ("http", "공통 HTTP 서버 :4195", "shared/bento/bento-global.yaml:2-5", "/<스트림>/<경로> 수신, /ready·/metrics"),
  ],
  links=[
    ("http", "s6", "그 밖(Bento 공통 HTTP 서버 경로 등록 /alertmanager_to_display/alertmanager)", "Alertmanager webhook 본문", "4_it/collector-bento/streams/alertmanager_to_display.yaml:3-7"),
    ("http", "s8", "그 밖(Bento 공통 HTTP 서버 경로 등록 /mes_requester/orders, sync_response)", "생산 지시 JSON ↔ 202/422 응답", "4_it/collector-bento/streams/mes_requester.yaml:4,8-13,48"),
    ("s8", "s7", "그 밖(Kafka 토픽 request.approved 경유)", "job_order_id(키 = 요청 ID)", "4_it/collector-bento/streams/mes_requester.yaml:50-54; request_dispatch.yaml:6-9"),
    ("s1", "s5", "그 밖(Kafka 토픽 plant.status 경유)", "PLC 상태·통신 상태·ACK(키 = 설비 ID)", "4_it/collector-bento/streams/dmz_to_kafka.yaml:33-40; status_to_alertmanager.yaml:5-8"),
    ("s4", "s6", "그 밖(Alertmanager HTTP 왕복: POST /api/v2/alerts → 묶기·억제 → webhook)", "source=plant alert 묶음 firing/resolved", "4_it/collector-bento/streams/alerts_to_alertmanager.yaml:30-31; shared/monitoring-prometheus/alertmanager.yml:9-21"),
    ("s5", "s6", "그 밖(Alertmanager HTTP 왕복)", "source=plant-state 억제 상태 firing/resolved", "4_it/collector-bento/streams/status_to_alertmanager.yaml:32-33; shared/monitoring-prometheus/alertmanager.yml:9-21"),
    ("s6", "s3", "그 밖(Kafka 토픽 alerts.display 경유)", "표시 문구·asset·tag·severity·group_id(키 = asset)", "4_it/collector-bento/streams/alertmanager_to_display.yaml:65-68; display_to_dmz.yaml:5-8"),
    ("s1", "http", "공유 메모리(Bento 프로세스 공통 지표 레지스트리)", "input_received{stream} 등 스트림별 지표", "shared/bento/bento-global.yaml:4-5; shared/monitoring-prometheus/rules.yml:27"),
  ],
  ext=[
    ("s1", "in", "MQTT tcp dmz-broker:1883, client·계정 it-collector, QoS1, 토픽 AR-100/reaction/+/+/tag/+ · status/+ · state/+ · ack/+ · AR-100/response/#", "계측값·PLC 상태·ACK·요청 응답", "4_it/collector-bento/streams/dmz_to_kafka.yaml:6-18"),
    ("s1", "out", "Kafka kafka:9092 토픽 sensor.telemetry.raw(키 asset) · plant.status(키 asset) · request.responses(키 job_order_id), 200건/200 ms 묶음", "GOOD 계측값 / 상태 / 응답 원문", "4_it/collector-bento/streams/dmz_to_kafka.yaml:28-50"),
    ("s3", "in", "Kafka alerts.display, 그룹 it-collector-display, 최신부터", "표시용 분석 alert", "4_it/collector-bento/streams/display_to_dmz.yaml:4-8"),
    ("s3", "out", "MQTT dmz-broker:1883 토픽 AR-100/alert/display, QoS1, retained, client it-collector-display", "FUXA 분석 경고(참고)", "4_it/collector-bento/streams/display_to_dmz.yaml:10-17"),
    ("s4", "in", "Kafka sensor.alerts, 그룹 it-collector-alertmanager, 최신부터", "Flink SQL·ONNX·업무 서비스 alert", "4_it/collector-bento/streams/alerts_to_alertmanager.yaml:5-9"),
    ("s4", "out", "HTTP POST http://alertmanager:9093/api/v2/alerts, 100건/200 ms json_array", "labels(source=plant, alertname, rule, asset, tag, severity, detector)+annotations", "4_it/collector-bento/streams/alerts_to_alertmanager.yaml:15-41"),
    ("s4", "in", "파일 /cfg/registry/alert_maps.blobl(map asset_of)", "태그 → 설비 매핑", "4_it/collector-bento/streams/alerts_to_alertmanager.yaml:13,20; compose.yml:411-412"),
    ("s5", "in", "Kafka plant.status, 그룹 it-collector-suppression, 최신부터 + 파일 alert_maps.blobl(map run_signal)", "PLC-01 maintenance·run_state, 설비 enable/run", "4_it/collector-bento/streams/status_to_alertmanager.yaml:5-19"),
    ("s5", "out", "HTTP POST http://alertmanager:9093/api/v2/alerts, 50건/200 ms json_array", "OutOfService·PlantStopped·SuppressedByDesign(source=plant-state)", "4_it/collector-bento/streams/status_to_alertmanager.yaml:22-43"),
    ("s6", "in", "HTTP POST :4195/alertmanager_to_display/alertmanager", "Alertmanager webhook(alerts 배열)", "4_it/collector-bento/streams/alertmanager_to_display.yaml:3-7; shared/monitoring-prometheus/alertmanager.yml:21"),
    ("s6", "out", "PostgreSQL postgres:5432/plant 계정 ops, 표 alert.alert_group·alert.alert_event", "묶음 생성/갱신·해제, 사건(DISPLAYED·OUT_OF_SERVICE·SUPPRESSED_BY_DESIGN)", "4_it/collector-bento/streams/alertmanager_to_display.yaml:16-54"),
    ("s6", "out", "Kafka alerts.display(키 asset), client it-collector-display-out", "새로 뜬 plant firing alert 만", "4_it/collector-bento/streams/alertmanager_to_display.yaml:56-70"),
    ("s7", "in", "Kafka request.approved, 그룹·client it-dispatcher", "승인된 job_order_id", "4_it/collector-bento/streams/request_dispatch.yaml:5-10"),
    ("s7", "both", "PostgreSQL 계정 dispatcher: workflow.request_status 조회, workflow.request_event·audit.log 추가", "dispatched 사건 선기록, 게이트웨이 결과 기록", "4_it/collector-bento/streams/request_dispatch.yaml:14-26,57-72"),
    ("s7", "out", "HTTP POST http://dmz-gateway:8088/requests (Bearer GATEWAY_CLIENT_TOKEN), timeout 5 s, retries 0", "작업 요청 ↔ 첫 겹 ⓐ 수용/거부 응답", "4_it/collector-bento/streams/request_dispatch.yaml:36-44"),
    ("s7", "out", "Kafka request.events · audit.copy (fan_out, 키 job_order_id)", "gateway_accepted/rejected 사건, 감사 사본", "4_it/collector-bento/streams/request_dispatch.yaml:76-93"),
    ("s8", "in", "HTTP POST :4195/mes_requester/orders", "work_master_id·equipment_id·parameters·planner·summary", "4_it/collector-bento/streams/mes_requester.yaml:4-13"),
    ("s8", "out", "PostgreSQL 계정 mes: workflow.request·workflow.request_event·audit.log(propose·approve)", "요청·승인 기록(requester mes-01)", "4_it/collector-bento/streams/mes_requester.yaml:23-39"),
    ("s8", "out", "Kafka request.approved(키 job_order_id), client it-mes-requester", "job_order_id", "4_it/collector-bento/streams/mes_requester.yaml:50-54"),
    ("http", "out", "HTTP :4195 /metrics, /ready", "IT Prometheus 수집(job it-collector), healthcheck", "shared/monitoring-prometheus/it.yml:24-25; compose.yml:418-419"),
  ],
  notes=[
    "① 은 GOOD·값 있는 계측값만 sensor.telemetry.raw 로 보낸다. status/state/ack 는 원문에 site·device·asset·kind·name·topic 을 덧붙여 plant.status 로 (4_it/collector-bento/streams/dmz_to_kafka.yaml:28-42)",
    "① 에 32 MiB 메모리 버퍼: Kafka 가 막혀도 MQTT 연결 유지, 프로세스가 죽으면 버퍼 내용 손실 (4_it/collector-bento/streams/dmz_to_kafka.yaml:19-22)",
    "④ 는 endsAt = alert 시각 + 60 s 로 보낸다. 같은 alert 가 다시 오면 끝만 늘고 60 s 조용하면 Alertmanager 가 해제. ML alert 의 tag MULTIVARIATE 는 asset_of 가 null 이라 device 로 대체 (4_it/collector-bento/streams/alerts_to_alertmanager.yaml:2-3,20,26-27)",
    "⑤ 는 켜지면 endsAt = 지금 + 86400 s, 풀리면 지금으로 보내 해제. 해당 키가 아니면 버림 (4_it/collector-bento/streams/status_to_alertmanager.yaml:16-30)",
    "⑥ 은 webhook 배열을 하나씩 나눠 source·status 로 SQL 3갈래, plant firing 만 group_id 를 붙여 alerts.display 로 낸다. plant-state 는 OutOfService 면 OUT_OF_SERVICE, 그 밖(PlantStopped 포함)은 SUPPRESSED_BY_DESIGN 로 기록 (4_it/collector-bento/streams/alertmanager_to_display.yaml:10-63)",
    "⑦ 은 마지막 사건이 approved 인 요청만 dispatched 를 먼저 쓰고 보낸다(같은 승인 메시지 재수신 시 재발송 없음). 게이트웨이 400·401·409·422·503 도 정상 응답으로 받고, 연결 실패는 GATEWAY_UNREACHABLE 로 기록. 재시도 없음 (4_it/collector-bento/streams/request_dispatch.yaml:2-4,18-26,42-48)",
    "⑧ 은 SQL 기록 실패 시 catch 에서 mes_status=422 로 동기 응답 후 메시지를 지워 Kafka 로 내지 않는다. 성공이면 202 (4_it/collector-bento/streams/mes_requester.yaml:12-13,41-49)",
    "③ 은 retained 라 DMZ 브로커에 마지막 표시 1건이 남는다 (4_it/collector-bento/streams/display_to_dmz.yaml:15-17)",
  ],
)

INTERNAL["hist"] = dict(
  runtime="Go · Bento 1.21.2 streams 모드 1프로세스(it-history, monitoring 프로필에서만 기동) · 스트림 1개(kafka_to_it_influx) · 공통 HTTP :4195",
  parts=[
    ("in", "Kafka 입력(kafka_franz)", "4_it/history-bento/kafka_to_it_influx.yaml:2-7", "Flink 결과 토픽 3개 소비, 최신부터"),
    ("map", "토픽별 변환(Bloblang → 라인 프로토콜)", "4_it/history-bento/kafka_to_it_influx.yaml:8-23", "process·anomaly·alerts measurement 생성, 태그값 이스케이프"),
    ("batch", "출력 묶음(1000건/1 s, lines 보관)", "4_it/history-bento/kafka_to_it_influx.yaml:34-38", "여러 줄을 한 요청 본문으로"),
    ("out", "InfluxDB HTTP 쓰기(http_client)", "4_it/history-bento/kafka_to_it_influx.yaml:24-33", "POST /api/v2/write, 재시도·백오프"),
    ("http", "공통 HTTP 서버 :4195", "shared/bento/bento-global.yaml:2-5", "/ready·/metrics"),
  ],
  links=[
    ("in", "map", "그 밖(Bento 스트림 내부 채널)", "Kafka 레코드+meta kafka_topic", "4_it/history-bento/kafka_to_it_influx.yaml:10-13"),
    ("map", "batch", "그 밖(Bento 출력 배칭)", "라인 프로토콜 한 줄", "4_it/history-bento/kafka_to_it_influx.yaml:13-23,34-38"),
    ("batch", "out", "함수 호출(배치 처리기 archive lines)", "줄바꿈으로 이은 본문", "4_it/history-bento/kafka_to_it_influx.yaml:37-38"),
  ],
  ext=[
    ("in", "in", "Kafka kafka:9092 토픽 sensor.telemetry.clean · sensor.anomaly.score · sensor.alerts, 그룹 it-collector-influx, start_from_oldest false", "정제값·이상 점수·alert", "4_it/history-bento/kafka_to_it_influx.yaml:3-7"),
    ("out", "out", "HTTP POST http://it-influx:8086/api/v2/write?org=INFLUX_ORG&bucket=IT_INFLUX_BUCKET&precision=ns (Token IT_INFLUX_TOKEN)", "measurement process · anomaly · alerts", "4_it/history-bento/kafka_to_it_influx.yaml:14-30"),
    ("http", "out", "HTTP :4195 /ready", "healthcheck", "compose.yml:493-494"),
  ],
  notes=[
    "다른 토픽은 deleted() 로 버린다. top_contributors 의 공백·쉼표·등호, detail 의 역슬래시·큰따옴표를 이스케이프 (4_it/history-bento/kafka_to_it_influx.yaml:17,21-22)",
    "max_in_flight 1, 재시도 1 s 부터 최대 10 s (4_it/history-bento/kafka_to_it_influx.yaml:31-33)",
    "compose 프로필 monitoring 에서만 뜬다(읽는 쪽이 Grafana 뿐) (compose.yml:479-480)",
  ],
)

INTERNAL["flink"] = dict(
  runtime="Java 17 · Flink 2.2.1 세션 클러스터: JobManager 1 + TaskManager 1(슬롯 4, 병렬도 1) · 잡 4개(SQL 3 + ONNX DataStream 1) · 상태 hashmap · 체크포인트 10 s EXACTLY_ONCE · ZooKeeper HA · 제출은 1회성 컨테이너(flink-job-submitter)",
  parts=[
    ("submit", "잡 제출기(submit-jobs.sh)", "4_it/detection-flink/submit-jobs.sh:1-95", "JM·슬롯 대기 → 중복 확인 → SQL 3잡·ONNX 잡 제출 → 4개 RUNNING 확인"),
    ("jm", "JobManager(REST·체크포인트 조정·HA)", "4_it/detection-flink/conf/config.yaml:11-24,49-79", "잡 관리, 10 s 체크포인트, ZooKeeper 로 잡 복구"),
    ("tbl", "SQL 표 정의(telemetry_raw·tag_limits·alerts)", "4_it/detection-flink/sql/01_sources.sql:1-61", "Kafka 원천(워터마크 5 s)·CSV 규격·Kafka alert 싱크"),
    ("j_thr", "잡 AR100-Tier1-Threshold", "4_it/detection-flink/sql/02_tier1_rules.sql:1-28", "규격 USL/LSL 이탈 → CRITICAL alert"),
    ("j_z", "잡 AR100-Tier1-ZScore", "4_it/detection-flink/sql/03_tier1_zscore.sql:1-52", "태그별 60행 창 z>3.5 가 최근 5중 3회 → WARNING"),
    ("j_cep", "잡 AR100-Tier1-CEP", "4_it/detection-flink/sql/04_tier1_cep.sql:1-44", "IT-102>9.6 후 10 s 안 VT-101>7.1 → CRITICAL"),
    ("o_src", "ONNX 잡 KafkaSource", "4_it/detection-flink/onnx-job/src/main/java/org/uengine/iiot/AnomalyJob.java:63-72", "sensor.telemetry.raw 읽기(워터마크 없음)"),
    ("interp", "Interpolator(keyBy tag)", "4_it/detection-flink/onnx-job/src/main/java/org/uengine/iiot/Interpolator.java:21-92", "(tag,ts) 중복 제거·결측 선형/LOCF 보간"),
    ("scorer", "OnnxScorer(keyBy device)", "4_it/detection-flink/onnx-job/src/main/java/org/uengine/iiot/OnnxScorer.java:40-313", "스캔 순번으로 벡터 조립·창 10스텝·ONNX 추론"),
    ("o_sink", "ONNX 잡 KafkaSink 3개", "4_it/detection-flink/onnx-job/src/main/java/org/uengine/iiot/AnomalyJob.java:81-96,109-118", "clean·score·ml-alert 를 JSON 으로, AT_LEAST_ONCE"),
  ],
  links=[
    ("submit", "jm", "HTTP(REST flink-jobmanager:8081, sql-client -f · flink run -d -m)", "SQL 문 묶음(01~04 이어 붙임), anomaly-job.jar+job.properties, 잡 상태 조회", "4_it/detection-flink/submit-jobs.sh:12,45-56,77-79,86"),
    ("tbl", "j_thr", "그 밖(같은 SQL Client 세션 카탈로그의 표 참조)", "telemetry_raw JOIN tag_limits → INSERT INTO alerts", "4_it/detection-flink/sql/02_tier1_rules.sql:14-28"),
    ("tbl", "j_z", "그 밖(같은 SQL 세션 카탈로그)", "telemetry_raw OVER 창 → INSERT INTO alerts", "4_it/detection-flink/sql/03_tier1_zscore.sql:14-52"),
    ("tbl", "j_cep", "그 밖(같은 SQL 세션 카탈로그)", "telemetry_raw MATCH_RECOGNIZE → INSERT INTO alerts", "4_it/detection-flink/sql/04_tier1_cep.sql:10-44"),
    ("o_src", "interp", "그 밖(Flink keyBy(tag) 해시 분할 데이터 교환)", "Reading(ts ns·site·device·tag·value·quality·seq·pts)", "4_it/detection-flink/onnx-job/src/main/java/org/uengine/iiot/AnomalyJob.java:75-79"),
    ("interp", "o_sink", "그 밖(Flink 연산자 체인 → sinkTo)", "실측+보간 Reading(quality GOOD·INTERPOLATED_*)", "4_it/detection-flink/onnx-job/src/main/java/org/uengine/iiot/AnomalyJob.java:81-82"),
    ("interp", "scorer", "그 밖(Flink keyBy(device) 해시 분할 데이터 교환)", "실측+보간 Reading", "4_it/detection-flink/onnx-job/src/main/java/org/uengine/iiot/AnomalyJob.java:85-89"),
    ("scorer", "o_sink", "콜백(Collector 주 출력 + side output ALERT_TAG)", "AnomalyScore, 이상이면 Alert(ML_AUTOENCODER)", "4_it/detection-flink/onnx-job/src/main/java/org/uengine/iiot/AnomalyJob.java:91-96; OnnxScorer.java:296-304"),
    ("jm", "interp", "그 밖(Flink 체크포인트 배리어·RPC 6123)", "keyed 상태 lastGood·lastEmittedTs 스냅숏", "4_it/detection-flink/conf/config.yaml:49-61; Interpolator.java:27-42"),
    ("jm", "scorer", "그 밖(Flink 체크포인트 배리어·RPC 6123)", "MapState latest·pending·window 등 스냅숏", "4_it/detection-flink/conf/config.yaml:49-61; OnnxScorer.java:107-120"),
  ],
  ext=[
    ("tbl", "in", "Kafka kafka:9092 sensor.telemetry.raw, 그룹 flink-tier1, latest-offset, json(파싱 오류 무시)", "원시 계측값(ts·site·device·tag·value·quality)", "4_it/detection-flink/sql/01_sources.sql:11-29"),
    ("tbl", "in", "파일 file:///opt/flink/sql/tag_limits.csv (filesystem·csv, 바인드 마운트)", "태그별 unit·lsl·usl 17행", "4_it/detection-flink/sql/01_sources.sql:32-43; sql/tag_limits.csv:1-17; compose.yml:439"),
    ("tbl", "out", "Kafka sensor.alerts, json", "THRESHOLD_USL/LSL·ZSCORE·CEP_BEARING alert", "4_it/detection-flink/sql/01_sources.sql:46-61"),
    ("o_src", "in", "Kafka sensor.telemetry.raw, 그룹 flink-tier2-onnx, latest", "원시 계측값(seq·pts 포함)", "4_it/detection-flink/onnx-job/job.properties:5-10; AnomalyJob.java:63-69"),
    ("o_sink", "out", "Kafka sensor.telemetry.clean · sensor.anomaly.score · sensor.alerts, JSON, AT_LEAST_ONCE", "정제값·재구성 오차·ML alert", "4_it/detection-flink/onnx-job/job.properties:7-9; AnomalyJob.java:109-118"),
    ("scorer", "in", "파일 /opt/models/model.onnx, /opt/models/model_meta.json (볼륨 model-store 읽기 전용)", "오토인코더, 태그 순서·mean·std·threshold·sample_interval_s", "4_it/detection-flink/onnx-job/job.properties:21-22; OnnxScorer.java:88-106; compose.yml:449"),
    ("jm", "both", "ZooKeeper zookeeper:2181, root /flink, cluster-id /ar100, storageDir file:///opt/flink/checkpoints/ha", "잡 목록·최신 체크포인트 위치(HA 메타데이터)", "4_it/detection-flink/conf/config.yaml:72-79"),
    ("jm", "out", "파일 file:///opt/flink/checkpoints (볼륨 flink-checkpoints), savepoint-dir /opt/flink/savepoints", "체크포인트(RETAIN_ON_CANCELLATION)", "4_it/detection-flink/conf/config.yaml:49-57; compose.yml:439"),
    ("jm", "in", "HTTP REST :8081 (호스트 127.0.0.1:PORT_FLINK_UI)", "Flink UI·잡 제출·상태", "compose.yml:438; conf/config.yaml:45-47"),
    ("jm", "out", "HTTP :9249 /metrics (JM·TM 각각 PrometheusReporter)", "체크포인트·백프레셔 지표(IT Prometheus job flink)", "4_it/detection-flink/conf/config.yaml:64-69; shared/monitoring-prometheus/it.yml:20-21"),
  ],
  notes=[
    "제출기는 RUNNING 이 4 이면 건너뛰고, 1~3 이면 중복 제출하지 않고 실패로 끝난다(재기동 멱등). SQL 은 Job ID 3개, 최종 20 s 뒤 RUNNING 4개를 확인 (4_it/detection-flink/submit-jobs.sh:32-41,51-68,83-95)",
    "ONNX 잡은 /opt/models/model.onnx 가 없으면 제출하지 않는다. compose 는 model-trainer 완료를 기다린다 (4_it/detection-flink/submit-jobs.sh:71-74; compose.yml:473-477)",
    "체크포인트: 서버 설정 10 s·EXACTLY_ONCE·timeout 60 s·min-pause 5 s, SQL 은 SET 으로, ONNX 잡은 클라이언트 설정으로 10 s 켬. 코드에 enableCheckpointing 호출 없음. 실패 복구는 Flink 기본 exponential-delay, failover region (4_it/detection-flink/conf/config.yaml:5,22-23,49-57; sql/01_sources.sql:6-7; conf/client-config.yaml:24-29)",
    "HA: JobManager 가 다시 뜨면 ZooKeeper 의 잡 목록·최신 체크포인트 위치로 잡을 되살린다 (4_it/detection-flink/conf/config.yaml:71-79; compose.yml:425)",
    "Interpolator: ts 가 직전 이하면 버림. 간격이 스캔 1.5배(1.5 s)를 넘으면 빠진 칸을 채운다. 20 s 이하면 선형, 넘으면 LOCF, 최대 maxGap/scan 칸 (4_it/detection-flink/onnx-job/src/main/java/org/uengine/iiot/Interpolator.java:48-90; job.properties:16-18)",
    "OnnxScorer: seq 없는 값(보간값)은 latest 만 갱신. 스캔이 태그 수만큼 모이거나 두 스캔 앞선 값이 오거나 처리 시각 타이머 1.5 s 가 지나면 벡터화. 한 번도 안 온 태그가 있으면 추론 안 함. pts 간격이 sample_interval_s×1.5 초과·역행이면 창을 비움 (4_it/detection-flink/onnx-job/src/main/java/org/uengine/iiot/OnnxScorer.java:136-220)",
    "추론: 창 10스텝을 학습 mean/std 로 정규화해 평탄화, ORT 세션 1스레드, MSE > threshold 면 is_anomaly 와 side output alert(tag MULTIVARIATE, WARNING). 점수 ts 는 벽시계 (4_it/detection-flink/onnx-job/src/main/java/org/uengine/iiot/OnnxScorer.java:100-104,239-304)",
    "SQL 원천은 이벤트 시각(ts/1e6 ms) 기준 워터마크 5 s, idle-timeout 5 s. ONNX 잡은 워터마크 없이 처리 시각 타이머만 쓴다 (4_it/detection-flink/sql/01_sources.sql:8,18-20; AnomalyJob.java:71-72)",
  ],
)

INTERNAL["trainer"] = dict(
  runtime="Python 3.12(python:3.12-slim) · 단일 프로세스·단일 스레드 1회 실행(restart no) · torch 2.8.0 CPU · onnx 1.17.0 · onnxruntime 1.20.1 · 가상설비 plant.py 를 모듈로 직접 import",
  parts=[
    ("cfg", "설정 적재(train.yaml·plant.yaml)", "4_it/ml-trainer/train.py:24-25,35-41", "학습 설정 읽기, 배속을 plant.yaml 값(600)으로"),
    ("gen", "정상 데이터 생성(ReactorPlant)", "4_it/ml-trainer/train.py:44-64", "warmup 1800 스텝 버린 뒤 21600행×태그 합성"),
    ("prep", "정규화·슬라이딩 창", "4_it/ml-trainer/train.py:70-75,107-121", "mean/std 산출, 10스텝 창 평탄화, 85/15 분할"),
    ("train", "오토인코더 학습", "4_it/ml-trainer/train.py:78-94,123-142", "dim→64→16→64→dim, Adam, MSE, 60 epoch"),
    ("thr", "임계치 산출", "4_it/ml-trainer/train.py:144-151", "검증 오차 99.5 백분위 × 1.15"),
    ("export", "ONNX·메타 저장", "4_it/ml-trainer/train.py:153-181", "model.onnx(opset 17)·model_meta.json 기록"),
    ("validate", "판별력 자가 검증(ORT)", "4_it/ml-trainer/train.py:189-248", "정상·고장 4종 재생해 탐지율 로그"),
  ],
  links=[
    ("cfg", "gen", "함수 호출(plant_cfg)", "배속 덮어쓴 설비 설정 dict", "4_it/ml-trainer/train.py:46"),
    ("gen", "prep", "함수 호출(main 안 반환값)", "np.ndarray(n×태그)·태그 목록", "4_it/ml-trainer/train.py:105-114"),
    ("prep", "train", "함수 호출(torch 텐서)", "Xtr·Xva", "4_it/ml-trainer/train.py:120-127"),
    ("train", "thr", "함수 호출(model 객체)", "검증 재구성 오차 배열", "4_it/ml-trainer/train.py:145-149"),
    ("thr", "export", "함수 호출(main 지역 변수)", "threshold·mean·std·tags", "4_it/ml-trainer/train.py:156-178"),
    ("export", "validate", "로컬 파일(/opt/models/model.onnx, model_meta.json)", "모델·메타를 다시 읽어 검증", "4_it/ml-trainer/train.py:192-201,251-253"),
  ],
  ext=[
    ("cfg", "in", "파일 /app/train.yaml(TRAIN_CONFIG), /app/plant.yaml, /app/plant.py(이미지 빌드 때 0_plant/simulator 원본 복사)", "학습 설정·설비 물리 모델", "4_it/ml-trainer/Dockerfile:8-10; train.py:22-25"),
    ("export", "out", "파일 /opt/models/model.onnx, /opt/models/model_meta.json (볼륨 model-store)", "ONNX 모델(input·reconstruction, 배치 축 동적), 메타(tags·window_steps·input_dim·mean·std·threshold·train_rows·sample_interval_s·physics_time_scale)", "4_it/ml-trainer/train.yaml:38-40; train.py:156-178; compose.yml:463"),
    ("validate", "out", "stdout 로그([trainer] 접두)", "오탐률·고장별 탐지율", "4_it/ml-trainer/train.py:28-29,233-248"),
  ],
  notes=[
    "재현성: torch·numpy·random 시드를 모두 42 로 고정(설비 노이즈가 random 모듈 사용) (4_it/ml-trainer/train.py:99-103; train.yaml:31)",
    "표본 간격 = dt_s 1.0 × 배속(plant.yaml physics_time_scale 600). 이 값이 meta.sample_interval_s 가 되어 Flink OnnxScorer 가 창 끊김 판정에 쓴다 (4_it/ml-trainer/train.py:35-41,175; train.yaml:15-17)",
    "window_steps 10 은 Flink job.properties window.steps 와 같아야 한다(코드상 자동 대조 없음) (4_it/ml-trainer/train.yaml:25; 4_it/detection-flink/onnx-job/job.properties:23)",
    "검증은 고장 drift·bearing_wear·noise·spike 를 400 스텝 재생하고 후반부만 평가, 통신 불량 센티널(< -999998)은 직전값으로 대체. 결과는 로그뿐이고 실패로 종료하지 않는다 (4_it/ml-trainer/train.py:205-248)",
    "compose 에서 기동 때 1회 실행, flink-job-submitter 가 완료(service_completed_successfully)를 기다린다 (compose.yml:459-464,477)",
  ],
)

INTERNAL["am"] = dict(
  runtime="Go · Prometheus Alertmanager v0.34.1 단일 프로세스 · 설정 alertmanager.yml · 상태 저장 /alertmanager(볼륨 alertmanager-data)",
  parts=[
    ("r_root", "기본 경로(route)", "shared/monitoring-prometheus/alertmanager.yml:1-6", "alertname·tier 로 묶음, 10 s/1 m/1 h"),
    ("r_plant", "공정 경로(source=~plant|plant-state)", "shared/monitoring-prometheus/alertmanager.yml:7-14", "asset·rule·alertname 묶음, 0 s/5 s/24 h"),
    ("rcv_def", "수신자 default", "shared/monitoring-prometheus/alertmanager.yml:18", "수신 설정 없음(인프라 경보는 로그만)"),
    ("rcv_plant", "수신자 plant(webhook)", "shared/monitoring-prometheus/alertmanager.yml:19-22", "it-collector ⑥ 으로 firing·resolved 전송"),
    ("inh_svc", "억제: PipelineServiceDown", "shared/monitoring-prometheus/alertmanager.yml:26-28", "같은 tier 의 severity=warning 억제"),
    ("inh_isa", "억제: OutOfService·PlantStopped", "shared/monitoring-prometheus/alertmanager.yml:30-33", "켜져 있으면 source=plant 전부 억제"),
    ("inh_sbd", "억제: SuppressedByDesign", "shared/monitoring-prometheus/alertmanager.yml:34-36", "같은 asset 의 source=plant 억제"),
  ],
  links=[
    ("r_root", "r_plant", "그 밖(라우팅 트리 하위 경로 매칭)", "source 라벨이 plant 또는 plant-state 인 alert", "shared/monitoring-prometheus/alertmanager.yml:7-10"),
    ("r_root", "rcv_def", "그 밖(설정 참조 receiver)", "그 밖의 alert(인프라)", "shared/monitoring-prometheus/alertmanager.yml:2"),
    ("r_plant", "rcv_plant", "그 밖(설정 참조 receiver)", "공정·억제 상태 묶음 알림", "shared/monitoring-prometheus/alertmanager.yml:10"),
    ("inh_isa", "r_plant", "그 밖(알림 파이프라인 억제 단계, 같은 프로세스 메모리)", "plant alert 억제 여부", "shared/monitoring-prometheus/alertmanager.yml:30-33"),
    ("inh_sbd", "r_plant", "그 밖(알림 파이프라인 억제 단계)", "asset 이 같은 plant alert 억제", "shared/monitoring-prometheus/alertmanager.yml:34-36"),
    ("inh_svc", "r_root", "그 밖(알림 파이프라인 억제 단계)", "tier 가 같은 warning 억제", "shared/monitoring-prometheus/alertmanager.yml:26-28"),
  ],
  ext=[
    ("r_root", "in", "HTTP :9093 POST /api/v2/alerts", "it-collector ④(source=plant)·⑤(source=plant-state), IT Prometheus 규칙 경보", "4_it/collector-bento/streams/alerts_to_alertmanager.yaml:31; status_to_alertmanager.yaml:33; shared/monitoring-prometheus/it.yml:7-9"),
    ("rcv_plant", "out", "HTTP POST http://it-collector:4195/alertmanager_to_display/alertmanager, send_resolved", "묶음 webhook(alerts 배열·status)", "shared/monitoring-prometheus/alertmanager.yml:20-22"),
    ("r_root", "both", "로컬 파일 /alertmanager(볼륨 alertmanager-data), 호스트 127.0.0.1:PORT_ALERTMANAGER", "알림 기록·침묵 상태, UI", "compose.yml:583-588"),
  ],
  notes=[
    "공정 경로 group_wait 0 s·group_interval 5 s 라 새 묶음·해제가 곧바로 ⑥ 으로 간다. repeat 24 h (shared/monitoring-prometheus/alertmanager.yml:11-14)",
    "억제 대상은 source=plant 뿐이라 plant-state 억제 상태 자체는 계속 ⑥ 으로 알려져 기록된다 (shared/monitoring-prometheus/alertmanager.yml:30-36)",
    "PipelineServiceDown 억제는 severity=warning(소문자)만 대상. Flink alert 의 severity 는 대문자 WARNING/CRITICAL 이라 해당 없음 (shared/monitoring-prometheus/alertmanager.yml:26-28; 4_it/detection-flink/sql/01_sources.sql:53)",
  ],
)

# 주의: 문서·주석과 코드가 다른 곳
CAUTION = [
  "상태 백엔드: AnomalyJob.java:28·Interpolator.java:13 주석은 RocksDB, 실제 설정은 hashmap (4_it/detection-flink/conf/config.yaml:59-61). OnnxScorer.java:224 의 RocksDB null 설명도 현재 설정과 무관",
  "태그 수: 주석은 12태그·12차원·120→64→16→64→120 (OnnxScorer.java:69,132,203; conf/config.yaml:3; ml-trainer/train.yaml:23), 실제 plant.yaml 태그 17개 → 입력 170차원, tag_limits.csv 도 17행",
  "Z-Score 기준: 02_tier1_rules.sql:7 주석 |z| > 3.0, 실제 03_tier1_zscore.sql:31 은 z > 3.5(최근 5중 3회)",
  "Flink UI 주소: submit-jobs.sh:92 는 localhost:27081 고정 출력, .env PORT_FLINK_UI=37081",
  "loader '두 스트림': 3_dmz/loader-bento 에는 loader.yaml 1개뿐, 두 번째는 shared/bento/broker-exporter/sys_metrics.yaml (compose.yml:270)",
  "collector 스트림 번호 ① ③~⑧ 만 있고 ② 파일 없음(무엇이었는지 미확인)",
  "gateway src/*.js 는 이미지에 들어가지 않는다. 실행본은 generate.py 가 만든 flows.json 함수 문자열(현재 5개 모두 일치)",
]

# ceco_demo 내부 구조 조사 G — ai(knowledge) · bus(business) · web · seed(graph-seed)
# 근거: D:/work/study/ceco_demo 현재 작업 트리(5_ai/, compose.yml). 경로는 5_ai/server/knowledge/backend/src/ 아래를 src/ 로 줄여 적음.

INTERNAL["ai"] = dict(
  runtime="Python 3.12 (python:3.12-slim, uv) · 명령 ontology-studio-backend → uvicorn 1프로세스·1워커(:8000) · asyncio 이벤트 루프 1 + lifespan 상주 asyncio 태스크 3(온도 관측 2 s · 정비 실행기 1 s · 자동 분석 2 s, 각 틱은 asyncio.to_thread 로 스레드풀에서 동기 psycopg/neo4j 실행) + 요청마다 만드는 asyncio 태스크(분석 drive · 지식 구축 drive) + FastAPI 동기 엔드포인트용 anyio 스레드풀 + 시동 때 local 샌드박스 bash 자식 프로세스 1회",
  parts=[
    ("host", "앱 조립·lifespan", "src/host/app.py:30-76", "라우터 12개 등록, 테이블 준비·중단 표시, 상주 루프 3개 기동"),
    ("incidents", "사건 접수·묶기 API", "src/modules/operations/api.py:19-183", "alarm 검증·sha256 중복 제거·30 s 묶음·사건/이벤트 조회"),
    ("evidence", "설비 근거·파이프라인 상태", "src/modules/operations/evidence.py:30-139 · pipeline.py:14-65", "DMZ Influx 사본·Neo4j 관계 읽기, Flink 잡 상태 조회"),
    ("agent", "LangGraph 분석·검토 흐름", "src/modules/operations/agent.py:39-601", "investigate→review(interrupt)→execute 그래프, 도구 7개, 실행 기록·SSE"),
    ("auto", "자동 분석 루프", "src/modules/operations/agent.py:605-673", "2 s 마다 조건 맞는 접수 사건을 골라 analyze 시작"),
    ("kg", "고장 온톨로지 조회·정비 판단 엔진", "src/modules/operations/fault_ontology.py:23-149 · decision.py:31-364 · src/modules/ontology/tools.py:21-89", "증상→고장모드 추적, 매뉴얼 벡터 검색, 대안 손익·규칙·뒤집힘 결정론 계산"),
    ("actions", "대응안·승인·작업 요청 발송", "src/modules/operations/actions.py:38-511", "대응안 저장, 승인 재검사, workflow 기록 후 Kafka request.approved 알림"),
    ("maint", "정비 계획 실행기", "src/modules/operations/maintenance.py:55-443", "1 s 틱 상태 기계: 단계별 작업 요청·결과 판정·회복 판정·보고서"),
    ("thermal", "냉각 조치 후 온도 관측기", "src/modules/operations/thermal_observation.py:10-111", "observing 대응안의 TT-101 목표±1°C 30 s 유지 판정(명령 없음)"),
    ("studio", "지식 스튜디오(읽기·검토 게시·의미 후보)·파일·세션 저장", "src/modules/ontology/api.py:612-620 · review.py:95-230 · prepare.py:25-79 · build.py:58-322 · src/modules/files/api.py:13-62 · src/modules/agent_session/service.py:785-937 · session_store.py:15-30", "그래프 읽기, 검토 묶음 단일 트랜잭션 게시, LLM 의미 후보, 업로드, 모델 프로필"),
  ],
  links=[
    ("host", "incidents", "함수 호출", "initialize_operations(): 사건 테이블 DDL(advisory lock 72401931)", "src/host/app.py:37"),
    ("host", "actions", "함수 호출", "initialize_actions(): manufacturing_proposals DDL", "src/host/app.py:38"),
    ("host", "agent", "함수 호출", "initialize_agent_runs · mark_interrupted_runs(running/resuming→interrupted)", "src/host/app.py:39-40"),
    ("host", "studio", "함수 호출", "warm_up_agent(SQLite·샌드박스 점검·모델 객체) · 지식 구축 DDL·중단 표시", "src/host/app.py:36,41-42"),
    ("host", "thermal", "asyncio 태스크(asyncio.Event stop)", "create_task(observe_temperature(stop)) · 종료 때 stop.set 후 gather", "src/host/app.py:43-51"),
    ("host", "maint", "asyncio 태스크(asyncio.Event stop)", "create_task(run_maintenance_plans(stop))", "src/host/app.py:45"),
    ("host", "auto", "asyncio 태스크(asyncio.Event stop)", "create_task(run_auto_analysis(stop))", "src/host/app.py:46"),
    ("auto", "agent", "함수 호출(await, 같은 이벤트 루프)", "analyze(incident_id) → 실행 행 INSERT 후 schedule()", "src/modules/operations/agent.py:661-665"),
    ("auto", "actions", "함수 호출(asyncio.to_thread)", "incident_symptoms(): 증상 확인 후 load_decisions 로 결정 연결 여부", "src/modules/operations/agent.py:617,641-642"),
    ("agent", "agent", "asyncio 태스크", "schedule(): drive() 를 create_task, _tasks 집합에 보관", "src/modules/operations/agent.py:477-480"),
    ("agent", "incidents", "함수 호출(asyncio.to_thread)", "get_incident · connection(): 사건·이벤트 읽기", "src/modules/operations/agent.py:25,294"),
    ("agent", "evidence", "함수 호출(asyncio.to_thread)", "incident_evidence · history · live_state(도구 호출 시점에 재조회)", "src/modules/operations/agent.py:272-284,294,397"),
    ("agent", "kg", "함수 호출", "signatures·fault_context·manual_search(도구)·decision.analyze·load_decisions", "src/modules/operations/agent.py:296-299,343,348,175-181,369"),
    ("agent", "actions", "함수 호출(asyncio.to_thread)", "create_proposal(investigate 끝) · decide(execute 노드, 승인 결과)", "src/modules/operations/agent.py:399,423"),
    ("agent", "studio", "함수 호출", "_init_model('answer') · _resolve_agent_model_profile: 모델 객체·설정 확인", "src/modules/operations/agent.py:30,61,368"),
    ("actions", "evidence", "함수 호출", "live_state · incident_evidence(승인 직전 재조회·지식 지문 비교)", "src/modules/operations/actions.py:172,393-399,421"),
    ("actions", "kg", "함수 호출", "decision.analyze·materialize·decision_for(계획 고정·승인 시 재계산), fault_ontology.trace", "src/modules/operations/actions.py:224-267,462-471"),
    ("actions", "maint", "PostgreSQL 행(ai.manufacturing_proposals status=executing, result.status=executing_plan)", "start_state 로 만든 plan_state 를 저장 → 실행기가 1 s 틱에 읽어 진행", "src/modules/operations/actions.py:473-480 · maintenance.py:376-378"),
    ("actions", "thermal", "PostgreSQL 행(status=observing, result.thermal_observation)", "냉각 확인 시 start() 로 관측 트랙 저장 → 관측기가 2 s 틱에 읽음", "src/modules/operations/actions.py:451-456 · thermal_observation.py:68"),
    ("maint", "actions", "함수 호출", "_announce_approved(공용 Kafka Producer) · connection · event", "src/modules/operations/maintenance.py:57,72,374"),
    ("maint", "kg", "함수 호출", "facts · environment · evaluate(조건·회복 기준 식) · _registry", "src/modules/operations/maintenance.py:24,159-161,181-187,382"),
    ("maint", "evidence", "함수 호출", "live_state(틱당 1회) · history(상한 초과 시간)", "src/modules/operations/maintenance.py:338-343,375,381"),
    ("thermal", "evidence", "함수 호출", "live_state(틱당 1회)", "src/modules/operations/thermal_observation.py:66,71"),
    ("thermal", "actions", "함수 호출", "connection · event", "src/modules/operations/thermal_observation.py:65"),
    ("kg", "evidence", "함수 호출", "history · live_state(점검 대상 태그의 최근 30 s 값)", "src/modules/operations/fault_ontology.py:16,54-78"),
    ("evidence", "kg", "함수 호출", "ontology.tools._run_readonly_query(공용 Neo4j 드라이버 싱글턴)", "src/modules/operations/evidence.py:14,102-117"),
    ("studio", "kg", "함수 호출", "ontology.tools.get_driver(게시 트랜잭션·그래프 읽기)", "src/modules/ontology/review.py:15,138 · api.py:11-21"),
    ("studio", "incidents", "함수 호출", "operations.api.connection(지식 구축 실행 행 저장)", "src/modules/ontology/build.py:20,58-67"),
  ],
  ext=[
    ("host", "in", "HTTP :8000(compose 127.0.0.1:${PORT_AI_KNOWLEDGE}) ← web nginx /api/ 프록시 · healthcheck GET /openapi.json 10 s", "REST·SSE 요청", "compose.yml:692,700-705 · src/host/main.py:14-15"),
    ("incidents", "in", "HTTP POST /api/operations/incidents · GET /incidents · /incidents/{id} · /incidents/{id}/events?before_id&limit", "alarm JSON(Alarm 9필드) · 사건 목록 100건·커서 페이지", "src/modules/operations/api.py:100-183"),
    ("incidents", "both", "PostgreSQL postgres:5432 DB ai(DB_* · ai_app) 표 manufacturing_incidents·manufacturing_events·manufacturing_alarm_links", "사건 행·이벤트 행(알람·도구·조치 기록 모두)", "src/modules/operations/api.py:32-80 · process_runtime/checkpointer.py:77-92"),
    ("evidence", "out", "HTTP GET http://dmz-influx:8086/query (InfluxQL v1, db=INFLUX_DB, Basic 읽기 전용 계정) measurement plc_status(1 h)·process_raw(10 s·이력)", "PLC 상태·센서 값·품질(timeout 10 s, 최대 2001행)", "src/modules/operations/evidence.py:30-92 · compose.yml:672-675"),
    ("evidence", "out", "HTTP GET http://flink-jobmanager:8081/jobs/overview (timeout 4 s)", "Flink 잡 상태(RUNNING 4개면 available)", "src/modules/operations/pipeline.py:14-26"),
    ("evidence", "out", "Neo4j bolt://graph:7687 읽기 세션: Asset-HAS_SENSOR-Sensor, INSTALLED_IN|FEEDS*1..2, HAS_PROCEDURE|GOVERNED_BY|DESCRIBED_BY→Document", "사건 설비·관련 문서 전문·센서 상하한", "src/modules/operations/evidence.py:101-120"),
    ("evidence", "in", "HTTP GET /api/operations/plant · /incidents/{id}/evidence · /pipeline", "설비 현재 상태 · 사건 근거 묶음 · 관측 지점 상태", "src/modules/operations/evidence.py:51,95 · pipeline.py:54"),
    ("agent", "out", "OpenAI API(ChatOpenAI, MINOR_MODEL=openai:gpt-6-luna, Responses API, timeout 90 s, max_retries 0, OPENAI_API_KEY)", "도구 호출 대화·구조화 출력(GroundedProposal|GroundedNeedsEvidence)", "src/modules/operations/agent.py:368-376 · src/modules/agent_session/service.py:806-829 · compose.yml:55-56"),
    ("agent", "both", "PostgreSQL DB ai: manufacturing_analysis_runs + LangGraph AsyncPostgresSaver 체크포인트 표(thread_id manufacturing:{run_id}, drive 마다 새 연결)", "실행 상태·결과, 그래프 상태(검토 대기 interrupt)", "src/modules/operations/agent.py:39-48,440-465"),
    ("agent", "in", "HTTP GET /api/operations/model-status · POST /incidents/{id}/analyze(202) · GET /incidents/{id}/analysis · /analysis/{run}/trace · SSE /analysis/{run}/stream(1 s) · POST /analysis/{run}/decision(202) · /analysis/{run}/recover", "분석 시작·검토 결정·실행 기록", "src/modules/operations/agent.py:59-601"),
    ("kg", "out", "Neo4j bolt://graph:7687: AlarmSignature→Symptom→FailureMode→Check/Cause, Decision·Option·Rule·KPI·Step 읽기 + 벡터 색인 section_embedding_v2(DocumentSection.v2_embedding) 검색·재색인 쓰기", "고장 후보·결정 정의·매뉴얼 절", "src/modules/operations/fault_ontology.py:29-131 · decision.py:111-153"),
    ("kg", "out", "OpenAI 임베딩 API(neo4j_graphrag OpenAIEmbeddings, EMBEDDING_MODEL text-embedding-3-small)", "검색어·절 텍스트 → 벡터", "src/modules/operations/fault_ontology.py:84-88,120-127"),
    ("kg", "in", "PostgreSQL postgres:5432 DB plant(PLANT_DB_* · ai_app) 표 enterprise.fact 읽기 · enterprise.work_order 읽기", "MES·ERP·CMMS 사실값, 작업 이력 50건", "src/modules/operations/decision.py:78-86,358-364 · plant_db.py:16-23"),
    ("kg", "in", "로컬 파일 /opt/ar100/registry/tags.json · work_masters.ot.json(읽기 전용 마운트 shared/registry/generated)", "태그 상하한·작업 정의(파라미터 범위·현장 작업 시간)", "src/modules/operations/decision.py:19,66-71 · compose.yml:693-694"),
    ("kg", "in", "HTTP GET /api/operations/v2/trace · /v2/search · POST /v2/index · GET /api/operations/maintenance/facts · /maintenance/work-orders", "온톨로지 추적·절 검색·재색인·사실값·작업 이력", "src/modules/operations/fault_ontology.py:134-149 · decision.py:349-364"),
    ("actions", "out", "PostgreSQL DB plant(ai_app): INSERT workflow.request · workflow.request_event(kind approved, source ai-app) · audit.log(ai propose + human approve)", "작업 요청 정본(job_order_id ai-<hex>, WM-M101-STOP·WM-HX102-ENABLE)", "src/modules/operations/actions.py:315-334 · plant_db.py:26-36"),
    ("actions", "out", "Kafka kafka:9092 produce 토픽 request.approved(key=job_order_id, acks=all, message.timeout 5 s, flush 6 s)", "{job_order_id} 만(내용 정본은 PostgreSQL)", "src/modules/operations/actions.py:297-312"),
    ("actions", "in", "PostgreSQL DB plant: SELECT workflow.request_event WHERE job_order_id 0.25 s 간격 최대 20 s", "게이트웨이·OT 수신·운전원·PLC·재관측 결과 사건", "src/modules/operations/actions.py:343-369"),
    ("actions", "both", "PostgreSQL DB ai: manufacturing_proposals(만료 5분) · manufacturing_incidents 상태 · manufacturing_events", "대응안·결정·결과·진행 이벤트", "src/modules/operations/actions.py:58-68,195-215,372-459"),
    ("actions", "in", "HTTP GET /api/operations/incidents/{id}/proposals · POST /proposals/{id}/decision(AI 대응안은 409) · POST /proposals/{id}/recover", "대응안 목록·비AI 대응안 결정·중단 실행 정리", "src/modules/operations/actions.py:270-273,487-511"),
    ("maint", "out", "PostgreSQL DB plant: INSERT workflow.request·request_event·audit.log(단계마다) · SELECT request_event(틱마다) · INSERT enterprise.work_order(끝날 때)", "정비 단계 작업 요청·결과·CMMS 작업 이력", "src/modules/operations/maintenance.py:55-83,419-431"),
    ("maint", "out", "Kafka produce request.approved(actions 의 공용 Producer)", "단계 작업 요청 ID", "src/modules/operations/maintenance.py:72-75"),
    ("maint", "both", "PostgreSQL DB ai: manufacturing_proposals FOR UPDATE(lock_timeout 2 s) · incidents · events(maintenance_progress·maintenance_report)", "plan_state 전이·보고서", "src/modules/operations/maintenance.py:376-416"),
    ("thermal", "both", "PostgreSQL DB ai: manufacturing_incidents·proposals FOR UPDATE(lock_timeout 2 s, statement_timeout 5 s) · events(thermal_observation)", "관측 트랙·최종 상태", "src/modules/operations/thermal_observation.py:64-99"),
    ("studio", "in", "HTTP GET /api/neo4j/status · /api/schema · /api/graph · /api/graph/search · /api/graph/neighbors(읽기 5개만 등록)", "게시 그래프 노드·관계", "src/modules/ontology/api.py:612-620"),
    ("studio", "in", "HTTP POST /api/knowledge/preview · /reconcile-assets · /publish · /prepare · /build(202) · GET /published · /structure · /builds · /builds/{id} · SSE /builds/{id}/stream(1 s)", "검토 묶음·sha256·게시 결과·의미 후보 실행", "src/modules/ontology/review.py:95-230 · prepare.py:25 · build.py:252-322"),
    ("studio", "in", "HTTP POST /api/upload · GET /api/files · DELETE /api/files/{f} · GET /api/download/{f} · POST /api/sandbox/clear", "원본 파일 업로드·목록", "src/modules/files/api.py:13-62"),
    ("studio", "both", "Neo4j bolt://graph:7687 쓰기 트랜잭션(_ImportBatch·_AssetIdentity·_Entity MERGE, 제약 3개) + 읽기", "검토한 노드·관계 묶음", "src/modules/ontology/review.py:133-197"),
    ("studio", "both", "로컬 파일 /workspace/uploads · /workspace/output(볼륨 knowledge-uploads·knowledge-output)", "업로드 원본·출력 파일", "src/modules/files/workspace.py:28-66 · compose.yml:693"),
    ("studio", "both", "SQLite 파일 /app/backend/data/sessions.db(볼륨 knowledge-data, WAL) — 세션·스키마 표 + LangGraph SqliteSaver", "스키마 그룹(/api/schema 원천)·대화 체크포인트", "src/modules/agent_session/session_store.py:15-30 · service.py:61-71"),
    ("studio", "out", "OpenAI API(ChatOpenAI 'build'=MAJOR_MODEL, timeout 90 s, retries 0)", "의미 후보 MeaningPlan(최대 2회 시도)", "src/modules/ontology/build.py:139-143,179-215"),
    ("studio", "both", "PostgreSQL DB ai: manufacturing_knowledge_builds", "실행 상태·trace·후보", "src/modules/ontology/build.py:58-72,218-249"),
    ("studio", "out", "자식 프로세스 bash -lc (local 샌드박스 시동 점검, timeout 10 s)", "실패 시 앱 기동 실패(raise)", "src/shared/sandbox/local_backend.py:113-163 · src/modules/agent_session/service.py:903-922"),
  ],
  notes=[
    "lifespan 순서: 로그 → warm_up_agent(샌드박스 bash 점검 실패면 raise → 기동 실패) → 사건·대응안·분석 실행 DDL → running/resuming 분석을 interrupted 로 → 지식 구축 DDL·running→interrupted → 상주 태스크 3개(src/host/app.py:35-46 · src/modules/agent_session/service.py:903-922)",
    "상주 루프 주기: 온도 관측 2 s, 정비 실행기 1 s, 자동 분석 2 s. 모두 stop.wait(timeout) 로 쉬고 틱은 asyncio.to_thread. 예외는 로그만 남기고 다음 틱에서 재시도(보낸 요청은 다시 보내지 않음)(thermal_observation.py:102-111 · maintenance.py:434-443 · agent.py:653-673)",
    "자동 분석은 AI_AUTO_ANALYZE=1 이고 모델 설정이 있을 때만: status=received, 가장 늦게 붙은 알람 시그니처 뒤 15 s 정착, alarm_count≥3, 마지막 알람 30 s 이내, 한계 이탈 경보(THRESHOLD_USL/LSL·CEP_BEARING) 있음, 연결 결정 있음, 틱당 최대 5건. 건너뜀은 review_revision 마다 auto_analysis_skipped 이벤트 1번(agent.py:605-650 · compose.yml:688)",
    "사건 묶기: alarm 정규화 JSON sha256 으로 중복 제거, 상관 키(교반기·열/냉각·압력 3묶음 아니면 tag:alert_type)별 pg_advisory_xact_lock, 같은 키의 열린 사건과 ±30 s 이내면 붙이고 revision+1, 새 종류 시그니처면 review_revision+1(api.py:83-142)",
    "분석 실행: 사건당 활성 실행 1개(부분 유니크 색인), 도구 6개(+결정 있으면 evaluate_maintenance_options) 모두 안 부르면 대응안 게시 거부, recursion_limit 30, 그래프 전체 asyncio.timeout 240 s. 도구마다 agent_tool_started/result/failed 이벤트를 PostgreSQL 에 남김(agent.py:47-48,302-320,376-382,459)",
    "검토 대기: review 노드가 langgraph interrupt 로 멈추고 상태는 AsyncPostgresSaver 에만 있다(메모리 대체 없음). 결정 POST 는 저장된 interrupt·run_id·incident_id·proposal_id 가 맞을 때만 Command(resume) 로 재개(agent.py:414-419,440-460)",
    "AI 출력 스키마는 action 을 maintenance_plan|inspect_only 로만 허용하고 citations 는 실제 조회된 document_id Literal 로 묶는다(값 수리 없음)(agent.py:105-129)",
    "대응안은 5분 뒤 만료. 승인 때 사건 review_revision, 설비 지문(스위치·인터록·정비 모드), 지식 지문(설비·문서·센서 내용 sha256)을 다시 비교하고 정비 계획은 손익·규칙을 지금 값으로 재계산(actions.py:65,74-104,391-405,462-471)",
    "단발 조치(stop_mixer·enable_cooling)는 승인 트랜잭션이 사건 행을 FOR NO KEY UPDATE 로 잡은 채 작업 요청 결과를 최대 20 s 기다린다. 진행 이벤트는 별도 연결(lock_timeout 2 s·statement_timeout 3 s)로 쓴다(actions.py:412-449,283)",
    "작업 요청은 재전송하지 않는다: Kafka 알림 실패면 request_event not_dispatched(KAFKA_UNAVAILABLE) 남기고 실패, 결과 불명확이면 uncertain 으로 사람에게 넘김(actions.py:336-340,366-369 · maintenance.py:72-75,126-131)",
    "정비 실행기 시간 한도: control 60 s, field 는 설비 작업시간÷PHYSICS_TIME_SCALE(600)+60 s, 운전원 대기면 +95 s, operator 단계 기본 180 s, wait 는 설비 시간÷600. 실패 시 LOTO(WM-PLC-MAINT-ON)를 켰고 안 풀었으면 WM-FLD-LOTO-RELEASE 정리 단계를 붙인다(maintenance.py:27-30,135-176,225-247)",
    "온도 관측: 목표 ±1.0°C 를 새 스캔(seq)으로 30 s 유지하면 temperature_stable, 스캔 공백 6 s 넘으면 unknown, 900 s 넘으면 timeout. 목표·냉각 명령·인터록·review_revision 이 바뀌면 interrupted(thermal_observation.py:10-13,23-61,84-87)",
    "SSE 두 개(분석 trace, 지식 구축)는 커밋된 DB 를 1 s 마다 다시 읽어 바뀐 때만 보내고 아니면 heartbeat. 재연결이 모델·조치를 다시 실행하지 않는다(agent.py:528-549 · build.py:298-322)",
    "async def 엔드포인트(analyze·resume·recover_run, 온톨로지 읽기 라우트)는 동기 psycopg·neo4j 호출을 이벤트 루프 스레드에서 직접 한다 — 그동안 상주 루프·SSE 가 잠시 멈춘다. def 엔드포인트는 스레드풀(agent.py:483-500 · ontology/api.py:59-68,347-421)",
    "등록 안 된 코드: agent_session/api.py(채팅 SSE), document_indexing, ontology_mcp, process_runtime/mcp.py, ontology/api.py 의 쓰기·nl-query 라우트는 호스트가 include 하지 않는다. warm_up_agent 는 build·answer 채팅 에이전트 객체를 만들기만 한다(src/host/app.py:64-75 · ontology/api.py:609-620 · agent_session/service.py:933-934)",
    "knowledge 컨테이너에는 KAFKA_BOOTSTRAP_SERVERS 가 없어 기본값 kafka:9092 로 접속한다(actions.py:306 · compose.yml:659-705)",
  ],
)

INTERNAL["bus"] = dict(
  runtime="Python 3.12 (knowledge 와 같은 이미지 ceco-ai-knowledge:base) · python -m backend.src.modules.operations.business 1프로세스 · 스레드 2(main: plant.status·request.responses 소비 + 0.5 s 타이머 / ai-intake 데몬: sensor.alerts 소비→사건 접수) + librdkafka 내부 스레드(Consumer 2·Producer 1)",
  parts=[
    ("main", "주 루프(소비·타이머 구동)", "src/modules/operations/business.py:206-233", "업무 DB 연결 1개로 메시지 poll 0.2 s, 0.5 s 마다 타이머, /tmp/alive 갱신"),
    ("status", "PLC 상태 기억", "src/modules/operations/business.py:32-33,52-63", "plant.status 값을 메모리 dict 에 저장, 정비 모드 변경을 감사"),
    ("resp", "OT 응답 기록", "src/modules/operations/business.py:67-77", "request.responses(ⓑⓒ)를 같은 요청 ID 의 request_event·감사로"),
    ("timers", "요청 시간 판정", "src/modules/operations/business.py:94-182", "ACK·만료·운전원 대기·현장 정비·재관측 판정을 한 번씩 기록"),
    ("intake", "AI 사건 접수", "src/modules/operations/business.py:185-203 · consumer.py:12-43 · api.py:100-142", "sensor.alerts → inbox 저장·Alarm 검증·사건 묶기, 저장 뒤 commit"),
    ("pub", "Kafka 발행기", "src/modules/operations/business.py:31,40-48", "공용 Producer 로 audit.copy·request.events·sensor.alerts 발행"),
    ("reg", "등록부 적재", "src/modules/operations/business.py:25-28,80-94", "tags.json·work_masters.ot.json 을 import 때 읽고 재관측 기대값 표 EXPECT 생성"),
  ],
  links=[
    ("main", "intake", "스레드 시작(threading.Thread daemon, name ai-intake)", "intake_loop 실행", "src/modules/operations/business.py:209"),
    ("main", "status", "함수 호출(토픽별 디스패치)", "plant.status 메시지 dict", "src/modules/operations/business.py:223-224"),
    ("main", "resp", "함수 호출(토픽별 디스패치)", "request.responses 메시지 dict", "src/modules/operations/business.py:223-224"),
    ("main", "timers", "함수 호출(0.5 s 마다)", "공용 autocommit 업무 DB 연결", "src/modules/operations/business.py:226-229"),
    ("status", "timers", "공유 메모리(threading.Lock 'lock', dict state)", "(asset, name) → 최신 PLC 상태값(재관측 비교용)", "src/modules/operations/business.py:57-59,163-164"),
    ("reg", "timers", "함수 호출(모듈 전역 WM·EXPECT 조회)", "작업 정의 종류·설비·상태 이름·기대값", "src/modules/operations/business.py:140,159-162"),
    ("status", "pub", "함수 호출", "audited → audit.copy(maintenance_on/off)", "src/modules/operations/business.py:62-63"),
    ("resp", "pub", "함수 호출", "audited → audit.copy(response_{stage})", "src/modules/operations/business.py:77"),
    ("timers", "pub", "함수 호출", "note → request.events·audit.copy, 불일치면 sensor.alerts COMMAND_DISAGREE", "src/modules/operations/business.py:172-181"),
    ("main", "pub", "함수 호출", "producer.poll(0) 0.5 s 마다(전달 콜백 처리)", "src/modules/operations/business.py:228"),
    ("intake", "intake", "함수 호출", "persist_message → Alarm.model_validate_json → api.ingest", "src/modules/operations/consumer.py:27-35"),
  ],
  ext=[
    ("main", "in", "Kafka kafka:9092 그룹 ar100-business-v2 토픽 plant.status · request.responses(auto.offset.reset latest, 수동 동기 commit 메시지마다)", "PLC 상태 · OT 수신기 응답", "src/modules/operations/business.py:210-225 · compose.yml:730"),
    ("intake", "in", "Kafka 그룹 ar100-ai-incidents-v1 토픽 sensor.alerts(earliest, 수동 commit 저장 뒤)", "Flink·업무 서비스 alert JSON", "src/modules/operations/business.py:189-200"),
    ("intake", "out", "PostgreSQL postgres:5432 DB ai(DB_* · ai_app) 표 manufacturing_inbox(topic,partition,offset PK) · manufacturing_incidents·events·alarm_links", "원본 바이트·accepted/rejected·사건", "src/modules/operations/consumer.py:12-43 · api.py:42-142 · compose.yml:722-726"),
    ("resp", "both", "PostgreSQL DB plant(PLANT_DB_USER=ops) SELECT workflow.request · INSERT workflow.request_event(source ot-receiver) · audit.log", "요청 존재 확인·응답 사건", "src/modules/operations/business.py:67-77 · plant_db.py:26-36 · compose.yml:727-729"),
    ("timers", "both", "PostgreSQL DB plant: SELECT workflow.request ⋈ request_event(최근 15분) · INSERT request_event(source business)·audit.log", "ack_timeout·expired_unconfirmed·unconfirmed·observed·command_disagree", "src/modules/operations/business.py:107-180"),
    ("status", "out", "PostgreSQL DB plant: audit.log", "정비 모드 켜기·끄기(주체 operator-{n} 또는 field-panel)", "src/modules/operations/business.py:60-63"),
    ("pub", "out", "Kafka produce audit.copy · request.events · sensor.alerts(linger 5 ms, 전달 확인 없음)", "감사 사본 · 판정 사본 · COMMAND_DISAGREE alert", "src/modules/operations/business.py:31,40-48,172-181"),
    ("reg", "in", "로컬 파일 /opt/ar100/registry/tags.json · work_masters.ot.json(읽기 전용 마운트)", "hierarchy·작업 정의", "src/modules/operations/business.py:25-26 · compose.yml:731-734"),
    ("main", "out", "로컬 파일 /tmp/alive touch(0.5 s) → compose healthcheck 수정 시각 30 s 이내", "생존 신호", "src/modules/operations/business.py:29,230 · compose.yml:740-745"),
  ],
  notes=[
    "사건 접수를 다른 스레드·연결·소비자 그룹으로 분리한 이유: AI 승인이 사건 행을 잠근 동안 접수가 막혀도 요청 시간 판정은 멈추지 않게(business.py:185-189)",
    "주 루프는 autocommit 업무 DB 연결 하나를 쓰고, 어떤 예외든 2 s 쉬고 연결부터 다시 만든다. 접수 스레드는 예외 시 2 s 쉬고 같은 Consumer 로 재시도(commit 안 된 메시지는 다시 받음)(business.py:214-233,192-203)",
    "타이머 판정 순서: 게이트웨이 수용 없음·거부·최종 판정 있으면 건너뜀 → 수신 응답 없음: 만료+5 s 면 expired_unconfirmed, ACK 5 s 넘으면 ack_timeout(끝 아님) → 거부면 건너뜀 → OPERATOR_WAIT 뒤 60+30+5 s 운전원 응답 없으면 unconfirmed → field 작업은 field 결과로 observed/unconfirmed(시간 한도 설비 작업시간÷600+30 s) → PLC ACCEPTED 뒤 메모리 상태가 기대값이면 observed, 10 s 넘으면 command_disagree(business.py:107-176)",
    "판정은 사건 종류로 1번만 남는다. 설정값 비교 허용 오차 0.6(PLC 정수 레지스터 반올림)(business.py:98-104,121-123)",
    "PLC 상태 dict 는 메모리에만 있고 plant.status 그룹이 latest 로 시작하므로 재시작 직후에는 새 상태 메시지가 올 때까지 재관측 비교값이 비어(None) 있다(business.py:32,210)",
    "등록되지 않은 job_order_id 의 응답은 기록하지 않고 로그만(business.py:71-75)",
    "sensor.alerts 검증 실패 메시지는 rejected 로 원본 바이트·오류와 함께 inbox 에 남기고 commit(조용히 버리지 않음). 같은 offset 재수신은 ON CONFLICT DO NOTHING(consumer.py:27-43)",
    "시동 때 initialize_inbox 가 knowledge 와 같은 사건 DDL(api.initialize, advisory lock 72401931)을 실행한다. 등록부 파일이 없으면 import 단계에서 바로 죽는다(business.py:25-26,208 · consumer.py:12-13 · api.py:42-44)",
  ],
)

INTERNAL["web"] = dict(
  runtime="빌드: node:24-alpine 에서 vite build(VITE_FUXA_URL 빌드 인자) → 실행: nginx 1.28-alpine 1 server 블록 :8080(정적 SPA + /api/ 역프록시). 브라우저: Vue 3 SPA(main.js 가 App.vue 를 마운트) 단일 JS 이벤트 루프, setInterval/setTimeout 폴링 + EventSource SSE(분석 2개까지·지식 구축 1개)",
  parts=[
    ("nginx", "nginx 정적 서버·API 프록시", "5_ai/web/nginx.conf:1-46", "/healthz, /api/ → knowledge:8000(재시도 없음), SPA 폴백"),
    ("app", "앱 셸·사건 목록·근거 탭", "5_ai/web/src/App.vue:1-91", "페이지 3개 전환, 2 s 갱신(사건·설비·모델), 사건 선택 시 근거 조회"),
    ("scada", "실시간 공정 관제·파이프라인 상태", "5_ai/web/src/features/operations/ScadaLive.vue:1-87 · PipelineStatus.vue:1-26", "설비 사본 2 s 폴링·45점 추세, 파이프라인 15 s 폴링"),
    ("dash", "대시보드 AI 진행", "5_ai/web/src/features/operations/DashboardActivity.vue:1-37", "선택 사건 최신 분석 실행 2 s/10 s 폴링"),
    ("review", "AI 분석·검토·결과 패널", "5_ai/web/src/features/operations/IncidentReview.vue:1-142 (+ProcessFlow·ProposalFacts·MaintenancePlanCard·ThermalObservation, 표시 전용)", "대응안·실행·모델 상태 폴링, 분석 시작·승인/반려·복구 POST"),
    ("trace", "실행 기록 스트림", "5_ai/web/src/features/operations/ExecutionTrace.vue:1-66", "분석 run 의 SSE 수신, 끊기면 trace 2 s 폴링"),
    ("timeline", "사건 처리 이력", "5_ai/web/src/features/operations/IncidentTimeline.vue:1-40", "이벤트 30건 커서 페이지(타이머 없음)"),
    ("kreview", "지식 자료·후보·검토 게시", "5_ai/web/src/features/ontology/KnowledgeReview.vue:1-235", "업로드·구조 추출·의미 후보(SSE)·미리보기·게시"),
    ("graph", "관계 그래프(읽기 전용)", "5_ai/web/src/features/ontology/OntologyGraphPanel.vue:256-1600 · KnowledgeCoverage.vue", "게시 그래프 표시, 텍스트 검색·이웃 펼치기만 호출"),
    ("console", "FUXA 운전원 화면 대화상자", "5_ai/web/src/features/operations/OperatorConsole.vue:1-9", "VITE_FUXA_URL 을 iframe 으로 띄움(/api 호출 없음)"),
  ],
  links=[
    ("app", "scada", "Vue 컴포넌트(자식, v-show 로 항상 마운트) · emit 'control'", "설비 제어 패널 열기 신호", "5_ai/web/src/App.vue:79 · ScadaLive.vue:85"),
    ("app", "console", "Vue props(open) · emit 'close'", "대화상자 열림 상태", "5_ai/web/src/App.vue:65"),
    ("app", "dash", "Vue props(incidents, model, modelError) · emit 'inspect'", "2 s 갱신된 사건 목록 · 선택 사건으로 이동", "5_ai/web/src/App.vue:79"),
    ("dash", "trace", "Vue props(run)", "최신 분석 실행 행", "5_ai/web/src/features/operations/DashboardActivity.vue:3,35"),
    ("app", "review", "Vue props(incidentId, incidentStatus) · emit 'updated'", "선택 사건 · 상태 변화 시 refresh 와 이력 갱신", "5_ai/web/src/App.vue:37,84"),
    ("review", "trace", "Vue props(run, mode) · emit 'state'", "최신 실행 · 단계(investigate/execute)", "5_ai/web/src/features/operations/IncidentReview.vue:154"),
    ("app", "timeline", "Vue props(incidentId, revision, refreshToken)", "사건 revision·갱신 토큰 변화 시 다시 조회", "5_ai/web/src/App.vue:36-37,84 · IncidentTimeline.vue:38-39"),
    ("app", "kreview", "emit 'published'", "게시 뒤 그래프 다시 읽기(loadGraph)", "5_ai/web/src/App.vue:87"),
    ("app", "graph", "Vue props(graph-data, schema, read-only, allow-natural-language=false) · emit 'filter'·'refresh'", "/api/graph·/api/knowledge/structure 결과", "5_ai/web/src/App.vue:45,87"),
    ("app", "nginx", "HTTP(같은 출처 /api/...)", "모든 컴포넌트의 fetch·EventSource 가 nginx 를 거친다", "5_ai/web/nginx.conf:15-29"),
  ],
  ext=[
    ("nginx", "in", "HTTP :8080(compose 127.0.0.1:${PORT_AI_WEB}) · GET /healthz(wget 10 s healthcheck)", "브라우저 요청 · 상태 JSON", "5_ai/web/nginx.conf:1-13 · compose.yml:707-714"),
    ("nginx", "out", "HTTP http://knowledge:8000$request_uri(resolver 127.0.0.11 5 s, connect 5 s, read 60 s, proxy_next_upstream off, 502/504 → 503 JSON)", "모든 /api/ 요청·SSE", "5_ai/web/nginx.conf:15-35"),
    ("app", "out", "HTTP GET /api/operations/model-status · /api/operations/incidents · /api/operations/plant — setInterval 2 s(첫 화면부터, timeout 20 s)", "모델 설정·사건 100건·설비 상태", "5_ai/web/src/App.vue:41-43,60"),
    ("app", "out", "HTTP GET /api/operations/incidents/{id}/evidence — 사건 선택 때 1회", "근거 묶음", "5_ai/web/src/App.vue:44"),
    ("app", "out", "HTTP GET /api/graph?limit=250 · /api/knowledge/structure — 지식 페이지 첫 방문·게시 뒤·재시도 때", "게시 그래프·클래스 구조", "5_ai/web/src/App.vue:45,53,87"),
    ("scada", "out", "HTTP GET /api/operations/plant — 응답 뒤 2 s setTimeout(timeout 8 s), 1 s 시계", "설비 상태(seq 바뀔 때만 추세 추가)", "5_ai/web/src/features/operations/ScadaLive.vue:21-42"),
    ("scada", "out", "HTTP GET /api/operations/pipeline — 15 s setTimeout(timeout 18 s), details 가 닫혀 있어도 마운트됨", "관측 지점 3개 상태", "5_ai/web/src/features/operations/PipelineStatus.vue:5-17 · ScadaLive.vue:85"),
    ("dash", "out", "HTTP GET /api/operations/incidents/{id}/analysis — 실행 중이면 2 s, 아니면 10 s", "최신 분석 실행", "5_ai/web/src/features/operations/DashboardActivity.vue:14-27"),
    ("trace", "out", "SSE EventSource /api/operations/analysis/{run}/stream(event trace·unavailable) · 끊기면 HTTP GET /analysis/{run}/trace 2 s(오류 6 s) 실행 중일 때만", "실행 기록 200건 스냅샷", "5_ai/web/src/features/operations/ExecutionTrace.vue:7-26,50-63"),
    ("review", "out", "HTTP GET /incidents/{id}/proposals · /incidents/{id}/analysis · /model-status 동시 — 실행 중이면 3 s, executing 대응안 있으면 1.5 s, 오류면 6 s, 그 밖엔 멈춤", "대응안·실행·모델 상태", "5_ai/web/src/features/operations/IncidentReview.vue:56-86"),
    ("review", "out", "HTTP POST /incidents/{id}/analyze · /analysis/{run}/recover · /analysis/{run}/decision(AI 대응안) 또는 /proposals/{id}/decision · /proposals/{id}/recover(timeout 25 s, POST 재시도 없음)", "분석 시작·승인/반려(note 필수)·복구", "5_ai/web/src/features/operations/IncidentReview.vue:120-142"),
    ("timeline", "out", "HTTP GET /api/operations/incidents/{id}/events?limit=30[&before_id] — 선택·revision·refreshToken 변화 때", "이벤트 페이지", "5_ai/web/src/features/operations/IncidentTimeline.vue:21-39"),
    ("kreview", "out", "HTTP GET /api/files · /api/knowledge/published · /api/knowledge/builds(마운트 때) · POST /api/upload · /api/knowledge/preview · /prepare · /build · /reconcile-assets · /publish", "원본 목록·후보·게시", "5_ai/web/src/features/ontology/KnowledgeReview.vue:97-112,123,132,143,162,189,197,235"),
    ("kreview", "out", "SSE EventSource /api/knowledge/builds/{id}/stream · 실패 시 HTTP GET /api/knowledge/builds/{id} 3 s(오류 6 s)", "의미 후보 실행 진행", "5_ai/web/src/features/ontology/KnowledgeReview.vue:49-66,146-158"),
    ("graph", "out", "HTTP GET /api/graph/search?q&limit=50 · /api/graph/neighbors?node_id(timeout 20 s)", "검색 노드 · 이웃 경로(최대 500)", "5_ai/web/src/features/ontology/OntologyGraphPanel.vue:569,1591"),
    ("console", "out", "브라우저 iframe → VITE_FUXA_URL(compose 빌드 인자 http://127.0.0.1:${PORT_FUXA}/)", "FUXA 운전원 화면", "5_ai/web/src/features/operations/OperatorConsole.vue:6,9 · compose.yml:708"),
  ],
  notes=[
    "같은 /api/operations/plant 를 App(2 s setInterval)과 ScadaLive(응답 뒤 2 s)가 따로 폴링한다 — 탭 하나에서 2 s 마다 약 2회, 각 호출이 백엔드에서 InfluxQL 2건(App.vue:43,60 · ScadaLive.vue:21-41 · evidence.py:55-58)",
    "/api/operations/model-status 도 App 2 s 와 IncidentReview(실행 중 3 s)에서 중복 조회(App.vue:42 · IncidentReview.vue:68)",
    "ExecutionTrace 는 대시보드(공정 페이지, v-show)와 검토 패널 두 곳에 동시에 마운트될 수 있어 SSE 연결이 2개 열릴 수 있다(App.vue:79,84 · DashboardActivity.vue:35 · IncidentReview.vue:154)",
    "nginx 는 502/504 를 503 JSON 으로 바꾸고 proxy_next_upstream off — 결과 불명확한 승인 POST 를 프록시가 다시 보내지 않는다. read timeout 60 s(nginx.conf:23-35)",
    "OntologyGraphPanel 의 쓰기 호출(PATCH/DELETE/POST entities·relationships, nl-query)은 readOnly 가드로 막히고 백엔드도 등록하지 않는다(OntologyGraphPanel.vue:421-1036 · App.vue:87 · ontology/api.py:609-620)",
    "host/AppShell.vue·ChatPanel·FilePanel·ContextPanel·TodoPanel·useOntologyStudio.js·ThermalResponse.vue 는 main.js→App.vue 경로에서 import 되지 않는다(원본 스튜디오 잔존 코드)(main.js:3,12 · App.vue:3-14)",
    "개발 서버(vite)는 /api 를 http://localhost:28000 으로 프록시(vite.config.js)",
  ],
)

INTERNAL["seed"] = dict(
  runtime="Python 3.12 (knowledge 이미지 ceco-ai-knowledge:base) · python /repo/5_ai/server/seed_graph.py 1프로세스·1스레드·동기 · restart no(기동 때 1회), 종료 코드 0 이어야 knowledge 가 뜬다(service_completed_successfully)",
  parts=[
    ("main", "시드 주 흐름", "5_ai/server/seed_graph.py:65-85", "묶음 A·B·C 생성→게시→C 이전 판 정리→임베딩, Neo4j 연결 오류 재시도"),
    ("bundleA", "묶음 A 생성기(등록부·교육 문서·설비 관계)", "5_ai/server/build_knowledge_bundle.py:17-71 · export_inventory.py:6-7 · src/modules/ontology/inventory.py:16-71", "Device·Sensor·ControlPoint·WorkMaster·Document·Section·Asset·관계"),
    ("bundleB", "묶음 B 생성기(고장 지식 문서)", "5_ai/server/build_ontology_bundle.py:110-128", "V1 외 매뉴얼 문서·절 + applies_to 설비 HAS_PROCEDURE"),
    ("bundleC", "묶음 C 생성기(고장 온톨로지 v2·결정층)", "5_ai/server/build_ontology_bundle.py:131-274", "신호→증상→고장모드→원인·점검, 조치, KPI·결정·대안·규칙·단계·입력"),
    ("publish", "검토 게시(백엔드 review.publish)", "src/modules/ontology/review.py:133-197", "digest 일치 확인 후 Neo4j 단일 쓰기 트랜잭션, 같은 digest 는 중복 처리"),
    ("retire", "고장 온톨로지 이전 판 정리", "5_ai/server/seed_graph.py:51-62", "이번 C digest 에 없는 v2/* 개체·관계 삭제"),
    ("embed", "임베딩·벡터 색인", "5_ai/server/seed_graph.py:29-48 · src/modules/operations/fault_ontology.py:91-108 · src/modules/ontology/tools.py:668-731 · src/modules/ontology/embedding.py:40-92", "매뉴얼 절·개체 벡터 생성(바뀐 것만), 색인 2개, 누락·0 벡터 검사"),
  ],
  links=[
    ("main", "bundleA", "함수 호출", "build_knowledge_bundle.build() → batch dict", "5_ai/server/seed_graph.py:66"),
    ("main", "bundleB", "함수 호출", "build_ontology_bundle.arm_b()", "5_ai/server/seed_graph.py:67"),
    ("main", "bundleC", "함수 호출", "build_ontology_bundle.arm_c()", "5_ai/server/seed_graph.py:68"),
    ("main", "publish", "함수 호출", "Publish(batch, expected_sha256=batch.digest(), review_note='기동 시드: …') — A→B→C 순서", "5_ai/server/seed_graph.py:71-75"),
    ("main", "retire", "함수 호출", "C 게시 직후 C digest 전달", "5_ai/server/seed_graph.py:76-78"),
    ("main", "embed", "함수 호출", "세 묶음 게시 뒤 embed() 반환값이 종료 코드", "5_ai/server/seed_graph.py:79,88-89"),
    ("bundleC", "bundleA", "함수 호출(공용 export_inventory)", "ControlPoint·WorkMaster 노드를 등록부 인벤토리에서 재사용(같은 ID 로 MERGE)", "5_ai/server/build_ontology_bundle.py:24,135-146,206,271-272"),
  ],
  ext=[
    ("bundleA", "in", "로컬 파일(읽기 전용 마운트) /repo/shared/registry/equipment.yaml · /repo/5_ai/manuals/*.md", "설비·신호·명령·작업 정의 · 교육 문서 전문", "5_ai/server/build_knowledge_bundle.py:19-43 · compose.yml:654-655"),
    ("bundleB", "in", "로컬 파일 /repo/5_ai/manuals/*.md(front matter applies_to) · equipment.yaml", "고장 지식 문서·적용 설비", "5_ai/server/build_ontology_bundle.py:110-128"),
    ("bundleC", "in", "로컬 파일 /repo/5_ai/ontology/v2/kg/*.yaml · /repo/0_plant/simulator/plant.yaml(field_tasks) · equipment.yaml · manuals", "고장 지식·결정·KPI·대안 정의, 현장 작업 목록", "5_ai/server/build_ontology_bundle.py:100-107,131-136,201-206 · compose.yml:654-655"),
    ("publish", "out", "Neo4j bolt://graph:7687(NEO4J_USER/PASSWORD) 쓰기: 제약 3개 · _ImportBatch(sha256) · _AssetIdentity · MERGE _Entity:{class} · 관계 MERGE", "묶음별 노드·관계(_batch_id=digest)", "src/modules/ontology/review.py:138-197 · compose.yml:649-653"),
    ("retire", "out", "Neo4j DELETE: v2/* 에 닿는 이전 digest 관계 · _batch_id 다른 v2/* 개체 DETACH DELETE", "삭제 건수", "5_ai/server/seed_graph.py:55-62"),
    ("embed", "out", "OpenAI 임베딩 API(EMBEDDING_MODEL text-embedding-3-small, 1536차원): 절은 neo4j_graphrag OpenAIEmbeddings, 개체는 urllib POST {OPENAI_BASE_URL|api.openai.com/v1}/embeddings 5개씩", "텍스트 → 벡터", "src/modules/operations/fault_ontology.py:84-99 · src/modules/ontology/embedding.py:40-61,80-101 · compose.yml:57-58"),
    ("embed", "out", "Neo4j 쓰기: DocumentSection.v2_embedding·v2_embedded_hash·v2_embed_model, _Entity.embedding + 벡터 색인 section_embedding_v2 · entity_embedding_vector(cosine, 차원 다르면 DROP 후 재생성)", "벡터·색인", "src/modules/operations/fault_ontology.py:102-107 · src/modules/ontology/tools.py:668-731"),
    ("main", "out", "표준 출력 로그 · 프로세스 종료 코드(0/1) → compose depends_on", "게시·임베딩 결과", "5_ai/server/seed_graph.py:74-89 · compose.yml:699"),
  ],
  notes=[
    "멱등: 같은 묶음은 digest 가 같아 _ImportBatch status=published 이면 duplicate 로 끝난다. 임베딩도 내용 해시·모델·차원이 바뀐 것만 다시 만든다(review.py:151-155 · fault_ontology.py:93-96 · tools.py:690-697)",
    "Neo4j 가 막 떴을 때만 재시도: 예외 타입 이름에 ServiceUnavailable·Connection 이 있으면 2 s 간격 최대 30회, 그 밖의 예외는 그대로 실패(seed_graph.py:69-85)",
    "OPENAI_API_KEY 가 없으면 임베딩을 건너뛰고 0 으로 끝난다(매뉴얼 검색 불가). 키가 있으면 빠진 벡터나 0 벡터가 하나라도 남으면 1 로 끝나 knowledge 가 기동하지 않는다(seed_graph.py:29-48)",
    "개체 임베딩 실패는 embed_texts 가 0 벡터로 바꿔 돌려주고 _embed_entity_nodes 가 0 벡터를 저장하지 않아 루프가 끝난다 → 남은 수 검사로 실패가 드러난다(embedding.py:80-101 · tools.py:716-724 · seed_graph.py:38-48)",
    "_embed_entity_nodes 는 한 번에 최대 500개라 seed 가 0 이 될 때까지 반복 호출(tools.py:690-697 · seed_graph.py:38-39)",
    "게시 코드(backend.src…review)는 이미지 안 설치본을 쓰고, 묶음 생성기·매뉴얼·온톨로지 YAML 은 /repo 읽기 전용 마운트본을 읽는다(seed_graph.py:21-26 · compose.yml:643-655)",
    "묶음 C 는 결정층 식의 이름을 접두사·사실값·field_tasks 규칙으로 검사하고 모르는 이름·없는 KPI·등록부에 없는 작업 정의면 SystemExit 로 시드 전체를 멈춘다(build_ontology_bundle.py:218-224,256-257,268-270)",
    "5_ai/ontology/v2/data/*.yaml, cq.yaml, answer-key.yaml 은 어떤 .py 도 읽지 않는다 — 묶음 C 는 kg/*.yaml 만(build_ontology_bundle.py:103)",
  ],
)

# 주의: 문서·주석과 코드가 다른 곳
# 1. web 이력·실행 기록 라벨(action_connecting·action_dispatch_started·action_acknowledged='Modbus 응답 수신')은 백엔드가 더 이상 내지 않는 이벤트다. 실제로 나는 action_gateway_accepted·action_ot_receipt·action_operator·action_plc_ack·action_ack_timeout·action_command_disagree·request_recorded·maintenance_progress·maintenance_report 는 web 라벨표에 없다(IncidentTimeline.vue:6 · ExecutionTrace.vue:33-34 · actions.py:341-346 · maintenance.py:404,411-416).
# 2. ExecutionTrace 의 관측 도구 출처 표기 'InfluxDB + 시뮬레이터' — 코드는 DMZ InfluxDB 사본만 읽고 시뮬레이터에 직접 닿지 않는다(ExecutionTrace.vue:30 · evidence.py:19-75).
# 3. actions.Proposal 은 stop_mixer·enable_cooling 을 허용하고 실행·온도 관측 경로도 있지만, AI 출력 스키마는 maintenance_plan|inspect_only 만 허용하고 create_proposal 을 부르는 런타임 코드는 agent 뿐이다 → 단발 조치·thermal 관측기·POST /proposals/{id}/decision 은 테스트에서만 닿는다(actions.py:42,180-191,439-455,487-493 · agent.py:108-110,399).
# 4. agent SYSTEM_PROMPT 는 '고장모드 후보가 있으면 evaluate_maintenance_options 호출'이라 하지만 필수 검사는 증상에 연결된 결정(option_ids)이 있을 때다(agent.py:137,369,380).
# 5. compose 의 business 주석 '5 s·10 s 타이머' — 코드는 0.5 s 틱에서 ACK 5 s·재관측 10 s·만료+5 s·운전원 95 s·현장 작업시간÷600+30 s 를 판정한다(compose.yml:716 · business.py:7-8,27,95,226).
# 6. 5_ai/server/export_inventory.py CLI 기본 --source 가 0_plant/simulator/plant.yaml 인데 export_inventory 는 equipment.yaml 형식(hierarchy·assets.signals)을 요구한다 — plant.yaml 에는 hierarchy 키가 없어 기본값으로는 실패(export_inventory.py:11 · inventory.py:3,19).
# 7. embedding.py·fault_ontology.py 주석은 'OpenAI or LiteLLM'·OPENAI_BASE_URL 을 말하지만 compose 는 LiteLLM 중계를 폐기하고 OpenAI 직접 호출로 설정(embedding.py:1,41 · fault_ontology.py:85 · compose.yml:51).
# 8. checkpointer.py 의 풀 기반 get_async_postgres_checkpointer·InMemory 대체는 제조 분석에서 쓰이지 않는다 — agent.drive 는 매번 AsyncPostgresSaver.from_conn_string 으로 새 연결을 연다(checkpointer.py:42-60,95-148 · agent.py:444).

