# -*- coding: utf-8 -*-
# ceco_demo 데이터 리니지 (LINEAGE_SPEC.md 규격). 근거 = 2026-10-07 작업 트리(커밋 안 된 변경 포함), docs/ 제외.
# 경로는 저장소 D:\work\study\ceco_demo 기준 상대 경로. 'generate.py' = shared/registry/generate.py.
# shared/registry/generate.py --check 결과: 생성본(tags.json·flows.json·main.st·project.json 등)이 정본과 같음.
LINEAGE = {}

LINEAGE["tag"] = dict(
  title="계측값(예: TT-101 반응기 온도)",
  origin="가상설비 ReactorPlant.step() 의 raw['TT-101']=self.temp_c(에너지수지 적분) → _measure() 가 잡음·고장 효과를 붙임 (0_plant/simulator/plant.py:297-298, 328-358, 473-491)",
  hops=[
    dict(branch="본선", step="1", where="plant-sim · plant.py ReactorPlant.step/_integrate/_measure",
         how="프로세스 내부 호출. 스캔 1000 ms(plant.yaml scan_interval_ms), 물리 배속 600(설비 600 s/스캔), 소구간 ≤5 s 오일러 적분",
         fmt="파이썬 dict readings{tag: float}",
         fields="readings['TT-101'], self.seq(스캔 순번 u32), self.sim_time(설비 시각 s)",
         change="생성: temp_c(가열·반응열−냉각−손실−공급 원료) → +gauss(0, noise 0.06) → 고장 효과(spike +magnitude, noise ×14, drift 램프, dropout → BAD_QUALITY -999999.0) → clamp_lo(TT-101 은 없음). 다른 태그: PT-101 = 압력 + pt101_drift, PT-101 격리 중 BAD_QUALITY",
         keep="메모리(마지막 스캔 readings 만)",
         ref="0_plant/simulator/plant.py:15, 310-358, 473-491; plant.yaml:7,11-12,138-155"),
    dict(branch="본선", step="2", where="plant-sim · sim.py Simulator._write_readings (Modbus/TCP 슬레이브 :502, pymodbus)",
         how="Modbus TCP 슬레이브, 홀딩 레지스터. 접속자는 PLC 하나(ot-net)",
         fmt="Modbus 레지스터(float32 2워드, big-endian ABCD) + UINT32 2워드",
         fields="HR4..5 = TT-101(plant.yaml tags[].hr=4), 17개 태그 HR0..23·28..37, HR24..25 = seq, HR26..27 = int(sim_time)",
         change="float64 → float32(정밀도 약 7자리로 반올림). 설비 시각은 정수 초로 버림",
         keep="레지스터 메모리(다음 스캔에 덮어씀)",
         ref="0_plant/simulator/sim.py:52-58, 98-101, 115-119; plant.yaml:17-35, 51-52"),
    dict(branch="본선", step="3", where="plc(OpenPLC v4) · Modbus 마스터 ioGroup 'tags' → %IW",
         how="Modbus TCP 마스터 → plant-sim:502, FC3 offset 0 length 38, 주기 100 ms, errorHandling keep-last-value",
         fmt="Modbus 레지스터 → PLC 입력 워드 %IW0..37",
         fields="%IW4..5 = TT-101 원 워드 그대로, %IW24..27 = seq·pts",
         change="없음(워드 복사). PLC 프로그램은 TT-101 을 해독하지 않는다(WORDS_TO_REAL 은 PT-101·LT-101·IT-101·IT-102 만: 인터록·건식운전·되읽기 판단용)",
         keep="PLC 메모리(통신 실패 시 마지막 값 유지)",
         ref="1_control/plc-openplc/project/project.json:53-60; project/pous/programs/main.st:24-29, 115-120; generate.py:434-439, 455"),
    dict(branch="본선", step="4", where="edge(Node-RED) · rd_values(modbus-read) → f_values(values.js)",
         how="Modbus TCP plc:502 unit 1, FC4 InputRegister adr 0 qty 38, 250 ms 폴링",
         fmt="워드 배열 → JSON(UNS 값) + EdgeX Event JSON",
         fields="UNS payload {ts, value, quality, seq, pts}; edgex/telemetry {apiVersion:'v3', id=seq, deviceName, profileName, sourceName:'AllSensors', origin, readings[{id:'seq-TT-101', origin, deviceName, resourceName:'TT-101', profileName, valueType:'Float32', value(문자열)}]}",
         change="같은 seq 면 버림(250 ms 폴링 → 1 s 1회). float32 해독 → 유한·>-1000 이면 소수 4자리 반올림, 아니면 value=null·quality='BAD'. quality = plcStatus.field_comm==1 ? 'GOOD' : 'STALE'. 보고 조건(품질 변화·|Δ|≥deadband 0.03·pts 역행·pts 간격 ≥ max_interval_s 600 설비 초) — 배속 600 에서는 한 스캔 pts 증가가 600 이라 매 스캔 전 태그 발행. ts = Date.now()*1e6(엣지가 읽은 벽시계 ns, 설비 시각 아님). 토픽 AR-100/reaction/reactor-line-01/R-101/tag/TT-101(qos 1, retain false). edgex/telemetry 는 BAD 값을 readings 에서 뺌",
         keep="flow 메모리(lastPub·lastValues·lastSeq)",
         ref="2_ot/edge-nodered/src/values.js:1-41; flows.json:97 (rd_values); generate.py:39-48, 61-70, 111-112, 281-285"),
    dict(branch="본선", step="5", where="edge · f_saf(saf.js) → mq_out(mqtt out, edge 계정)",
         how="MQTT 3.1.1 → ot-hub:1883, clientid edge-01, clean session, QoS 1",
         fmt="JSON(토픽별 메시지)",
         fields="topic, payload, qos, retain",
         change="허브 연결이 끊기면 디스크 컨텍스트 큐에 쌓고 재연결 때 먼저 보냄. 72000 건 넘으면 새 메시지 버림(safDropped)",
         keep="끊김 중 디스크 컨텍스트(localfilesystem, flush 5 s), 한도 72000 건",
         ref="2_ot/edge-nodered/src/saf.js:1-24; mqtt_state.js; settings.js:28-31; flows.json:258"),
    dict(branch="본선", step="6", where="ot-hub(Mosquitto 2.1.2, OT 허브·UNS)",
         how="토픽 AR-100/reaction/reactor-line-01/R-101/tag/TT-101. 구독자: FUXA(fuxa 계정)·viewer. 브리지 connection dmz: 'AR-100/reaction/+/+/tag/+ out 1', MQTT 5, cleansession false, session expiry 3600",
         fmt="MQTT 메시지(JSON 그대로)",
         fields="ts, value, quality, seq, pts",
         change="없음. edgex/telemetry 는 브리지 대상이 아님(OT 안에서만)",
         keep="persistence true(autosave 60 s). 브리지 끊김 중 큐 max_queued_messages 72000·max_queued_bytes 32 MiB",
         ref="2_ot/factory-broker-mosquitto/mosquitto.conf:8-18, 26-44; acl:3-9"),
    dict(branch="본선", step="7", where="dmz-broker(Mosquitto, DMZ)",
         how="bridge-ot 계정이 write. 구독자 dmz-loader·it-collector(둘 다 clean_session true, QoS 1)",
         fmt="MQTT 메시지(JSON)",
         fields="ts, value, quality, seq, pts",
         change="없음",
         keep="persistence true. clean session 구독자는 끊긴 동안 쌓이지 않음",
         ref="3_dmz/dmz-broker-mosquitto/mosquitto.conf; acl:3-14, 21-24"),
    dict(branch="적재기(DMZ 사본)", step="8", where="dmz-loader(Bento) loader.yaml",
         how="MQTT 구독 tag/status/state, qos 1 → HTTP POST http://dmz-influx:8086/api/v2/write?bucket=plant_raw&precision=ns, 배치 500건/1 s, max_in_flight 1, 재시도 1~10 s",
         fmt="InfluxDB line protocol",
         fields="process_raw,site=AR-100,area=reaction,device=reactor-line-01,asset=R-101,tag=TT-101,quality=GOOD|STALE value=<float>,seq=<int>i,pts=<int>i <ts ns>",
         change="토픽 조각 → 태그 site·area·device·asset·tag, quality 는 태그로. value=null(BAD) 은 행을 만들지 않음. ts 없으면 적재 시각",
         keep="메모리 버퍼 32 MiB(프로세스가 죽으면 잃음)",
         ref="3_dmz/loader-bento/loader.yaml:5-52"),
    dict(branch="적재기(DMZ 사본)", step="9", where="dmz-influx(InfluxDB 2, 버킷 plant_raw)",
         how="v2 쓰기(관리 토큰은 적재기만). IT 는 v1 호환 읽기 전용 계정 + dbrp(InfluxQL) 로 조회",
         fmt="시계열(측정 process_raw)",
         fields="time, site, area, device, asset, tag, quality, value, seq, pts",
         change="없음",
         keep="디스크, 보존 7일(DOCKER_INFLUXDB_INIT_RETENTION 7d)",
         ref="compose.yml:247-264; 3_dmz/history-influxdb/10-it-reader.sh:5-8"),
    dict(branch="AI 증거(DMZ 사본 조회)", step="10", where="knowledge · operations/evidence.py live_state()·history()",
         how="HTTP GET dmz-influx:8086/query (InfluxQL, Basic 읽기 전용 계정, timeout 10 s)",
         fmt="InfluxQL 결과 → 파이썬 dict 행",
         fields="live: readings{tag: round(last(value),4)}, seq=max(last(seq)) (최근 10 s); history 행 {time(RFC3339), tag, value(float), quality}",
         change="live: 최근 10 s 마지막 값만(없으면 status unavailable). history: 사건 창 [first_ts−30 s, min(last_ts+15 s, 시작+300 s)] + 현재 30 s, LIMIT 2001 → 2000 자름(truncated). pts·asset 은 버림",
         keep="없음(조회 때마다). 대응안 생성 시 evidence 를 AI DB manufacturing_proposals.evidence 에 저장",
         ref="5_ai/server/knowledge/backend/src/modules/operations/evidence.py:30-92, 95-139"),
    dict(branch="AI 증거(DMZ 사본 조회)", step="11", where="knowledge · agent.py get_sensor_observations / actions.require_current_* / decision.environment / maintenance.verify·exceed_hours / pipeline",
         how="파이썬 함수 호출",
         fmt="파이썬 dict → LLM 도구 결과 JSON(manufacturing_events agent_tool_result)",
         fields="statistics[{tag, count, min, max, mean, first, last, latest_age_seconds, quality_counts}], at_first_alarm{values}, env o_TT_101, usl_TT_101",
         change="태그별 통계로 집계(원 행은 evidence 에 보존). 승인 조건: 최근 10 s·GOOD·유한값. 결정 엔진 이름 o_<태그('-'→'_')>",
         keep="AI DB(manufacturing_events·manufacturing_proposals) — 보존 정책 없음(미확인)",
         ref="agent.py:223-284; actions.py:107-167; decision.py:89-108; maintenance.py:178-205, 335-355; pipeline.py:29-51"),
    dict(branch="수집기(Kafka)", step="12", where="it-collector ① dmz_to_kafka.yaml(Bento)",
         how="MQTT 구독(it-collector 계정, clean_session, qos 1) → Kafka sensor.telemetry.raw, 키 = 설비 ID(R-101), 배치 200건/200 ms, max_in_flight 1",
         fmt="JSON",
         fields="{ts(int64 ns), site, device, tag, value(number), quality, asset, seq, pts}",
         change="quality=='GOOD' 이고 value != null 인 것만(STALE·BAD 버림). 토픽 조각 → site·device·tag·asset 필드",
         keep="메모리 버퍼 32 MiB. 토픽 6 파티션, 보존 7일, lz4",
         ref="4_it/collector-bento/streams/dmz_to_kafka.yaml:5-50; 4_it/stream-kafka/create-topics.sh:20"),
    dict(branch="수집기(Kafka)", step="13", where="Flink SQL 소스 telemetry_raw (잡 3개 공통)",
         how="Kafka connector, group flink-tier1, latest-offset, json.ignore-parse-errors; 체크포인트 10 s EXACTLY_ONCE, source idle-timeout 5 s",
         fmt="Flink 테이블 행",
         fields="ts, site, device, tag, value, quality, event_time=TO_TIMESTAMP_LTZ(ts/1e6,3), WATERMARK event_time−5 s",
         change="asset·seq·pts 버림(선언 안 됨)",
         keep="Flink 상태(hashmap 백엔드) + 체크포인트 볼륨",
         ref="4_it/detection-flink/sql/01_sources.sql:6-29; conf/config.yaml:49-61"),
    dict(branch="수집기(Kafka)", step="14", where="Flink SQL ① 임계치(02) · ② Z-Score(03) · ③ CEP(04)",
         how="INSERT INTO alerts → Kafka sensor.alerts(json, 키 없음)",
         fmt="JSON 행",
         fields="{ts, site, device, tag, value, alert_type, severity, detector, detail}",
         change="① tag_limits.csv(TT-101,degC,40.0,95.0) 조인: value>95 → THRESHOLD_USL, <40 → THRESHOLD_LSL, CRITICAL, TIER1_RULE, detail 'TT-101 = <3자리> degC / 규격 [40.0, 95.0]'. ② 태그별 최근 60행 평균·표준편차, n≥30, z>3.5 가 최근 5행 중 3회 이상 → ZSCORE WARNING TIER1_ZSCORE. ③ CEP 는 IT-102→VT-101 만(TT-101 해당 없음). 이후는 'alert' 리니지",
         keep="SQL 상태(일반 조인·OVER 창). 상태 TTL 설정 없음",
         ref="sql/02_tier1_rules.sql:14-28; 03_tier1_zscore.sql:14-52; 04_tier1_cep.sql:10-44; sql/tag_limits.csv(generate.py:189-193)"),
    dict(branch="수집기(Kafka)", step="15", where="Flink 잡 AR100-Tier2-OnnxAnomalyDetection · Interpolator(keyBy tag)",
         how="KafkaSource sensor.telemetry.raw, group flink-tier2-onnx, latest, noWatermarks → KafkaSink sensor.telemetry.clean(AT_LEAST_ONCE)",
         fmt="Java Reading → JSON(Jackson, NON_NULL)",
         fields="{ts, site, device, tag, value, quality('GOOD'|'INTERPOLATED_LINEAR'|'INTERPOLATED_LOCF'), seq, pts}",
         change="asset 버림. ts ≤ 마지막 ts 는 버림(중복·역순). 간격 > 1.5 s 면 채움: 20 s 이하 선형, 넘으면 LOCF, 최대 20점, 채운 값은 ts=prev+i·1 s 이고 seq·pts 없음. 원값은 그대로 통과",
         keep="키별 상태 lastGood·lastEmittedTs(hashmap, 체크포인트). Kafka clean 7일",
         ref="onnx-job/.../AnomalyJob.java:63-82; Interpolator.java:45-91; Reading.java:9-35; job.properties:12-18"),
    dict(branch="수집기(Kafka)", step="16", where="같은 잡 · OnnxScorer(keyBy device)",
         how="clean 스트림 → KafkaSink sensor.anomaly.score, 사이드 출력 → sensor.alerts",
         fmt="Java AnomalyScore·Alert → JSON",
         fields="score {ts(처리 시각 ns), site, device, reconstruction_error, threshold, is_anomaly, top_contributors, inference_ms, seq, pts}; alert {ts, site, device, tag:'MULTIVARIATE', value=mse, alert_type:'ML_AUTOENCODER', severity:'WARNING', detector:'TIER2_ML', detail}",
         change="seq 별로 한 스캔을 모음(17태그 다 오면 즉시, 아니면 1.5 s 타이머·LOCF). seq 없는 보간값은 latest 만 갱신. model_meta 태그 순서(plant.yaml tags 17개) 벡터 → 10스텝 창(pts 간격 > 1.5×sample_interval_s 면 창 초기화) → (x−mean)/std → ONNX 재구성 → MSE, 임계 = 학습 99.5 백분위×1.15, 기여 상위 3 태그. TT-101 개별 값은 여기서 사라지고 다변량 점수만 남음",
         keep="키별 상태 latest·pending·window(hashmap)",
         ref="OnnxScorer.java:137-305; ml-trainer/train.py:55-64, 148-175; train.yaml"),
    dict(branch="수집기(Kafka)", step="17", where="it-history(Bento, 감시 프로필 전용) kafka_to_it_influx.yaml",
         how="Kafka group it-collector-influx(latest) 토픽 clean·score·alerts → HTTP POST it-influx bucket process, 배치 1000/1 s",
         fmt="line protocol",
         fields="process,site,device,tag,quality value=<v> <ts>; anomaly,site,device,top_contributors=… reconstruction_error,threshold,inference_ms,is_anomaly <ts>; alerts,site,device,tag,alert_type,severity,detector value,detail <ts>",
         change="clean 은 보간값 포함. seq·pts 버림. top_contributors 공백·쉼표·= 이스케이프",
         keep="없음(통과)",
         ref="4_it/history-bento/kafka_to_it_influx.yaml:1-38; compose.yml:478-490"),
    dict(branch="수집기(Kafka)", step="18", where="it-influx(버킷 process) → grafana(감시 프로필 전용)",
         how="Grafana 데이터소스 uid influx(Flux). 01-process: _measurement=='process', _field=='value', 태그별; 02-anomaly: anomaly; 03-alerts: alerts",
         fmt="Flux 결과 → 패널",
         fields="_time, tag, quality, _value",
         change="aggregateWindow 등 화면 집계",
         keep="IT Influx 보존 30일",
         ref="compose.yml:500-516, 534-557; 4_it/dashboard-grafana/provisioning/datasources/datasources.yml; dashboards/01-process.json·02-anomaly.json·03-alerts.json"),
    dict(branch="FUXA(OT 화면)", step="19", where="fuxa · MQTTclient 장치 UNS(fuxa 계정, OT 허브 직접)",
         how="MQTT 구독 토픽 …/R-101/tag/TT-101, 태그 type json memaddress 'value'",
         fmt="FUXA 태그 값",
         fields="태그 TT_101(=value), 알람 'TT-101 규격' high [95, 1e9]·low [−1e9, 40], timedelay 2 s, ackmode ackactive, DAQ enabled(changed)",
         change="JSON 의 value 만 씀(quality·ts·seq 무시). 규격 이탈 시 FUXA 공정 알람",
         keep="FUXA DAQ SQlite, 보존 days7(FUXA_DAQ_RETENTION 기본)",
         ref="2_ot/hmi-fuxa/build_project.py:43-59, 117-132; provision.py:28, 95-110; ot-hub acl:22-26"),
  ],
  ends=[
    "DMZ InfluxDB process_raw(7일) → AI 증거·현재 상태·결정 엔진 관측(o_*)·정비 회복 판정·보고서 상한 초과 시간",
    "Kafka sensor.alerts → 'alert' 리니지(Alertmanager·FUXA 분석 경고·AI 사건)",
    "IT InfluxDB process/anomaly/alerts(30일) → Grafana 01~03 화면(감시 프로필 기동 때만)",
    "FUXA 공정 화면 값·규격 알람·DAQ 이력(OT 안, DMZ 와 무관)",
    "edgex/telemetry 는 OT 허브 안에서만(viewer 계정 수업용), 저장 없음",
  ],
  loss=[
    "고장 dropout·PT-101 교정 격리 → BAD_QUALITY → 엣지 value=null·'BAD' → 적재기·수집기 모두 버림: DMZ·Kafka 에 공백. 보간은 Flink clean 에서만(IT Influx), DMZ 사본은 공백 그대로",
    "가상설비가 멈추고 PLC 는 살아 있으면 PLC 가 마지막 값 유지 → seq 고정 → values.js 가 아무것도 내지 않음(STALE 도 안 냄). STALE 은 PLC 폴링 실패 때 comm.js 가 한 번만 냄",
    "quality 'STALE' 값: DMZ 사본에는 저장, Kafka 로는 안 감(Flink·IT 에 없음). 엣지 기동 직후 상태 블록을 읽기 전 값도 STALE 로 나가 Kafka 에서 빠짐",
    "끊김 버퍼 한도: 엣지 디스크 큐 72000 건(넘으면 새 값 버림, 디스크 flush 5 s 사이 프로세스 사망 시 손실), OT 허브 브리지 큐 72000 건·32 MiB, DMZ 적재기·IT 수집기 메모리 버퍼 32 MiB(프로세스 사망 시 손실), 둘 다 clean_session 이라 끊긴 동안 DMZ 브로커에 쌓이지 않음",
    "Flink 소스·it-history·Alertmanager 수집 스트림은 latest 에서 시작: 체크포인트 없이 재기동하면 그 사이 값은 탐지·IT 이력에서 빠짐(Kafka 7일 안에 남아 있어도)",
    "Flink SQL 워터마크 5 s: 늦게 온 행은 OVER 창·CEP 에서 빠질 수 있음. Interpolator 는 ts ≤ 마지막 ts 를 버림. JSON 해석 실패 행은 무시",
    "배속 600 에서는 max_interval(600 설비 초)이 한 스캔과 같아 deadband 거르기가 사실상 꺼짐(전 태그 매 초 발행). 배속을 낮추면 deadband 미만 변화는 발행되지 않음",
    "it-history·it-influx·grafana 는 monitoring 프로필이라 기본 기동에 없음: 이때 clean·score 는 Kafka 7일에만 남음",
    "AI 이력 조회는 2000행에서 자름(창 최대 300 s+30 s, 17태그면 잘릴 수 있음). live_state 는 최근 10 s 값이 없으면 unavailable",
  ],
)

LINEAGE["status"] = dict(
  title="PLC 상태 · ACK(모드·정비·인터록·운전 출력·설정값·명령 응답)",
  origin="PLC 프로그램 main.st 13단계 상태 레지스터 %QW100..118 쓰기(100 ms 태스크) (1_control/plc-openplc/project/pous/programs/main.st:284-289, 329-356)",
  hops=[
    dict(branch="본선", step="1", where="plc · main.st(OpenPLC, 100 ms 주기)",
         how="Modbus 슬레이브 :502 홀딩 레지스터(%QW)",
         fmt="Modbus 레지스터(WORD 19개)",
         fields="%QW100 sp_pump, 101 sp_valve, 102 sp_temp_x10, 103 st_run, 104 st_mode, 105 st_maint, 106 st_maint_op, 107 st_interlock, 108 st_field_comm, 109 st_estop, 110 st_outputs(bit0 P-101,1 M-101,2 HX-101,3 HX-102), 111 st_op_ack_seq, 112 st_op_ack_code, 113 st_rq_ack_seq, 114 st_rq_ack_code, 115·116 st_rq_ack_hash_hi/lo, 117 st_heartbeat, 118 st_fb_fault",
         change="생성: 출력 = 명령 AND NOT 인터록·비상정지. 설정값 REAL → INT 반올림. ACK = 명령 채널 순번이 바뀌었을 때 결과 코드(0 수용 … 11 PHYSICS)와 요청 해시 되돌림",
         keep="PLC 메모리. maint·maint_op 는 RETAIN(재시작 유지)",
         ref="main.st:44-63, 192-291, 329-356; generate.py:113-124"),
    dict(branch="본선", step="2", where="edge · rd_status(modbus-read FC3 HoldingRegister 100 qty 19, 250 ms) → f_status(status.js)",
         how="Modbus TCP plc:502 → MQTT(edge 계정) 보존 토픽",
         fmt="JSON",
         fields="상태 payload {ts, value, quality:'GOOD'} — 토픽 PLC-01/status/{mode('LOCAL'|'REMOTE_MANUAL'|'REMOTE_AUTO'|'UNKNOWN'), maintenance(bool), maint_operator(num), interlock(bool), estop(bool), field_comm(bool), run_state('RUN'|'STOP'), fb_fault(num)}; P-101/status/run·M-101/status/run·HX-101/status/enable·HX-102/status/enable(bool, outputs 비트); P-101/status/speed_sp·CV-101/status/open_sp(%), R-101/status/temp_sp(=sp_temp_x10/10). ACK payload ack/operator {ts, source:'plc', seq, code, result, command(opBySeq)}; ack/request {ts, source:'plc', seq, job_hash, job_order_id(jobByHash), code, result}",
         change="숫자 코드 → 이름(modes, ack_codes). run_state 는 엣지가 계산(heartbeat 가 2 s 넘게 그대로면 STOP). 바뀐 값만 발행, 48 s(=28800/600 벽시계)마다 전부 재발행, retain true. ACK 는 순번이 바뀔 때만, 기동 후 첫 읽기는 내지 않고 순번만 이어받음",
         keep="flow 메모리(plcStatus·opBySeq·jobByHash 최근 64), 브로커 보존 메시지",
         ref="2_ot/edge-nodered/src/status.js:1-64; flows.json:129; generate.py:113-130, 283-286"),
    dict(branch="본선", step="3", where="edge · f_comm(comm.js) · mqtt-broker birth/will",
         how="MQTT 보존 토픽",
         fmt="JSON",
         fields="PLC-01/state/comm {ts, value(bool), quality}; EDGE-01/state/node {value, quality}(birth true / will·close false)",
         change="PLC 폴링 노드 상태 문자열 → online. 끊기면 각 태그 마지막 값을 STALE 로 한 번 재발행",
         keep="브로커 보존 메시지",
         ref="2_ot/edge-nodered/src/comm.js:1-25; generate.py:255, 268-274"),
    dict(branch="본선", step="4", where="ot-hub → 소비자 FUXA · OT 수신기",
         how="FUXA: AR-100/reaction/# 읽기. 수신기(ot-receiver, MQTT 5, 세션 유지): PLC-01/status/+ → receiver_state, ack/request → receiver_plc_ack",
         fmt="MQTT JSON → FUXA 태그 / flow 컨텍스트",
         fields="FUXA 태그 PumpRun·AgitatorRun·HeaterEnable·CoolerEnable·PumpSpeedSP·ValveOpenSP·TempSP·PlcMode·Maintenance·MaintOperator·Interlock·Estop·FieldComm·PlcRunState·PlcComm·LastAck(result); 수신기 flow.plc{mode, maintenance, maint_operator, interlock, estop, field_comm, run_state, fb_fault}",
         change="수신기는 토픽 끝 이름 → 값만 기억(ts 버림). FUXA 알람: interlock·estop =1 즉시, field_comm·plc_comm =0 2 s",
         keep="수신기 flow 메모리, FUXA 메모리",
         ref="2_ot/edge-nodered/src/receiver_state.js:1-8; 2_ot/hmi-fuxa/build_project.py:62-79, 133-138"),
    dict(branch="본선", step="5", where="ot-hub 브리지 → dmz-broker",
         how="'AR-100/reaction/+/+/status/+ out 1', '…/ack/+ out 1', '…/state/+ out 1'",
         fmt="MQTT JSON",
         fields="위와 같음",
         change="없음",
         keep="브리지 큐(72000 건·32 MiB)",
         ref="2_ot/factory-broker-mosquitto/mosquitto.conf:37-40"),
    dict(branch="DMZ 사본", step="6", where="dmz-loader → dmz-influx",
         how="status·state 만 구독(ack 는 구독 안 함) → line protocol",
         fmt="line protocol",
         fields="plc_status,site,area,device,asset,kind=status|state,name text=<문자열> | num=<숫자·bool→1/0> <ts>",
         change="value 형식별로 text/num 필드. quality 버림",
         keep="DMZ Influx 7일",
         ref="3_dmz/loader-bento/loader.yaml:31-35"),
    dict(branch="DMZ 사본", step="7", where="knowledge · evidence.live_state",
         how="InfluxQL last(num), last(text) GROUP BY asset,name, 최근 1 h",
         fmt="파이썬 dict",
         fields="commands{pump_run, agitator_run, heater_enable, cooler_enable, pump_speed_sp, valve_open_sp, temp_sp_c}, interlock, mode, maintenance, field_comm, run_state",
         change="(P-101,speed_sp) 등 → 온톨로지 제어점 이름, 스위치는 bool, 설정값 소수 1자리. → 승인 지문(fingerprint: 스위치·인터록·정비), 결정 엔진 c_*·b_*·i_interlock·i_maintenance, 정비 실행기 operator 단계 until",
         keep="없음",
         ref="5_ai/server/knowledge/backend/src/modules/operations/evidence.py:19-75; actions.py:74-81; decision.py:89-108"),
    dict(branch="수집기", step="8", where="it-collector ① dmz_to_kafka.yaml",
         how="Kafka plant.status, 키 = 설비(토픽 4번째 조각: PLC-01, P-101 …)",
         fmt="JSON",
         fields="원 payload(ts, value, quality | ACK 필드) + {site, device, asset, kind('status'|'state'|'ack'), name, topic}",
         change="토픽 조각을 필드로 덧붙임(merge)",
         keep="Kafka 3 파티션, 7일",
         ref="4_it/collector-bento/streams/dmz_to_kafka.yaml:33-42; create-topics.sh:24"),
    dict(branch="수집기", step="9", where="business(업무 서비스) on_status",
         how="Kafka group ar100-business-v2(latest, 수동 commit)",
         fmt="파이썬 dict",
         fields="state[(asset, name)] = value; 정비 모드 변화 → audit.log(actor_type 'human', actor_id 'operator-<maint_operator>'|'field-panel', action 'maintenance_on'|'maintenance_off', subject 'PLC-01', detail{maint_operator, source})",
         change="kind 'ack' 는 버림. 최신 값만 메모리. 정비 모드가 이전 값과 다를 때만 감사(첫 값은 기록 안 함). 감사 사본 Kafka audit.copy",
         keep="메모리(재시작 시 비어 있음), PostgreSQL audit.log(추가 전용)",
         ref="5_ai/server/knowledge/backend/src/modules/operations/business.py:45-63, 206-233"),
    dict(branch="수집기", step="10", where="business timers() 재관측",
         how="0.5 s 틱",
         fmt="SQL 행(workflow.request_event)",
         fields="EXPECT[work_master_id] = (설비, 상태 이름, 기대값): switch → fixed_value bool, setpoint → 요청 파라미터, maintenance_on → True",
         change="PLC 수용(plc:ACCEPTED) 뒤 state 와 비교(설정값 ±0.6): 같으면 observed OK, 10 s 넘게 다르면 command_disagree + sensor.alerts COMMAND_DISAGREE",
         keep="PostgreSQL workflow.request_event·audit.log",
         ref="business.py:80-104, 156-175"),
    dict(branch="억제(⑤)", step="11", where="it-collector ⑤ status_to_alertmanager.yaml",
         how="Kafka plant.status group it-collector-suppression(latest) → HTTP POST alertmanager:9093/api/v2/alerts, 배치 50/200 ms",
         fmt="Alertmanager v2 alert JSON 배열",
         fields="{labels{source:'plant-state', alertname:'OutOfService'|'PlantStopped'|'SuppressedByDesign', asset:'PLC-01'|설비}, startsAt(지금), endsAt(켜짐: 지금+86400 s, 꺼짐: 지금)}",
         change="PLC-01/maintenance==true → OutOfService, PLC-01/run_state=='STOP' → PlantStopped, switch 상태(alert_maps run_signal: P-101/run·M-101/run·HX-101/enable·HX-102/enable)==false → SuppressedByDesign(asset). 그 밖(ACK 포함)은 버림",
         keep="Alertmanager 메모리",
         ref="4_it/collector-bento/streams/status_to_alertmanager.yaml:1-43; shared/registry/generated/alert_maps.blobl"),
    dict(branch="억제(⑤)", step="12", where="alertmanager inhibit_rules → webhook ⑥",
         how="OutOfService·PlantStopped → source=plant 전부 억제, SuppressedByDesign → equal [asset] 억제. plant-state 자체도 route plant 로 webhook",
         fmt="webhook JSON",
         fields="alert.alert_event(ts, asset_id, rule_id=alertname, display_state 'OUT_OF_SERVICE'|'SUPPRESSED_BY_DESIGN', detail '억제 시작'|'억제 해제')",
         change="PlantStopped 도 SUPPRESSED_BY_DESIGN 으로 기록",
         keep="PostgreSQL alert.alert_event(추가 전용)",
         ref="shared/monitoring-prometheus/alertmanager.yml:24-36; alertmanager_to_display.yaml:42-54"),
    dict(branch="요청 응답", step="13", where="OT 수신기 f_ack(receiver_plc_ack.js)",
         how="ack/request 구독 → AR-100/response/{job_order_id}",
         fmt="JSON",
         fields="{job_order_id, stage:'plc', status:'ACCEPTED'(code 0)|'REJECTED', reason=result(ACK 이름), plc_ack_code, ts(ISO)}",
         change="job_order_id 없는 ACK(엣지 재시작 뒤 jobByHash 없음 등)는 버림. 이후 'req' 리니지 → request.responses → 업무 서비스",
         keep="없음",
         ref="2_ot/edge-nodered/src/receiver_plc_ack.js:1-8"),
  ],
  ends=[
    "FUXA 상태 표시·공정 알람(인터록·비상정지·통신)",
    "OT 수신기 수용 판단(모드·정비·실행 상태·현장 통신)",
    "DMZ plc_status → AI live_state(승인 지문·결정 엔진·정비 실행기 운전원 단계)",
    "업무 서비스 재관측(observed / command_disagree) · 정비 모드 감사",
    "Alertmanager 억제(OutOfService·PlantStopped·SuppressedByDesign) → alert.alert_event 억제 기록",
    "PLC 요청 ACK → 응답 ⓒ(plc) → workflow.request_event",
  ],
  loss=[
    "PLC 에 아예 닿지 않으면 status.js 가 돌지 않아 run_state 가 보존된 'RUN' 으로 남음(STOP 은 PLC 가 응답하는데 heartbeat 만 멈출 때만). 수신기는 state/comm 을 보지 않아 이때도 요청을 받아 명령을 냄 → 쓰기 실패·ACK 없음",
    "ACK 는 기동 뒤 첫 상태 읽기에서 버림. 엣지 재시작으로 jobByHash(메모리)가 비면 ACK 의 job_order_id=null → 수신기가 버림 → 업무 서비스는 plc 응답 없이 결과 미판정(정비 실행기는 60 s 뒤 실패)",
    "상태는 바뀔 때만 + 48 s 마다 발행. 업무 서비스·수집기 소비자는 latest 에서 시작, 업무 서비스 state 는 메모리라 재시작 직후 최대 48 s 비어 있음 — 그동안 PLC 가 수용했지만 값이 이미 기대값이어서 새 상태 메시지가 없는 요청은 10 s 뒤 command_disagree 로 오판될 수 있음(same(None, 기대값) 거짓)",
    "DMZ 적재기는 ack 를 구독하지 않음. plant.status 의 ack 사본은 소비하는 코드가 없음",
    "업무 서비스: 처리 중 예외가 나면 같은 Consumer 로 계속 poll — 실패한 메시지로 되감지 않고 다음 메시지 commit 이 앞질러 그 메시지는 영구히 건너뜀",
    "Alertmanager 활성 alert 는 메모리(재시작 시 다음 재발행 48 s 까지 억제 없음 — Alertmanager 일반 동작, 실측 안 함)",
  ],
)

LINEAGE["alert"] = dict(
  title="분석 경보(alert)",
  origin="Flink SQL INSERT INTO alerts(임계치·Z-Score·CEP), Flink ONNX OnnxScorer 사이드 출력(ML_AUTOENCODER), 업무 서비스 timers() 의 COMMAND_DISAGREE (4_it/detection-flink/sql/02~04; OnnxScorer.java:298-304; business.py:171-175)",
  hops=[
    dict(branch="본선", step="1", where="Kafka sensor.alerts",
         how="Flink SQL kafka sink(키 없음) / Flink KafkaSink(AT_LEAST_ONCE, 키 없음) / business confluent Producer(키 = 설비)",
         fmt="JSON",
         fields="{ts(ns), site, device, tag, value, alert_type, severity, detector, detail}",
         change="ML: tag='MULTIVARIATE', value=MSE, ts=처리 시각. COMMAND_DISAGREE: tag='<설비>/<상태 이름>', value=0.0, severity WARNING, detector BUSINESS",
         keep="Kafka 3 파티션, 7일",
         ref="sql/01_sources.sql:46-61; AnomalyJob.java:94-96; Alert.java; business.py:172-175; create-topics.sh:23"),
    dict(branch="본선(Alertmanager)", step="2", where="it-collector ④ alerts_to_alertmanager.yaml",
         how="Kafka group it-collector-alertmanager(latest) → HTTP POST alertmanager:9093/api/v2/alerts, 배치 100/200 ms",
         fmt="Alertmanager v2 alert JSON 배열",
         fields="{labels{source:'plant', alertname=alert_type, rule='<alert_type>:<tag>', asset=asset_of(tag) 없으면 device, tag, severity, detector}, annotations{detail(없으면 ''), value(문자열), ts_ns(문자열)}, startsAt=ts, endsAt=ts+60 s}",
         change="ns → RFC3339(밀리초, UTC). 태그 → 설비(alert_maps.blobl, 등록부 생성). 같은 라벨이 다시 오면 endsAt 만 늘어남",
         keep="없음",
         ref="4_it/collector-bento/streams/alerts_to_alertmanager.yaml:1-41; shared/registry/generated/alert_maps.blobl; generate.py:210-216"),
    dict(branch="본선(Alertmanager)", step="3", where="alertmanager",
         how="route source=~'plant|plant-state' → receiver plant, group_by [asset, rule, alertname], group_wait 0 s, group_interval 5 s, repeat 24 h; inhibit(OutOfService·PlantStopped → source=plant, SuppressedByDesign equal asset)",
         fmt="Alertmanager 내부 alert",
         fields="labels·annotations·startsAt·endsAt·status(firing|resolved)",
         change="묶기(설비·규칙별 한 묶음), 억제된 alert 는 알리지 않음, endsAt 지나면(60 s 조용) resolved",
         keep="메모리 + alertmanager-data(알림 기록·silence)",
         ref="shared/monitoring-prometheus/alertmanager.yml:1-36"),
    dict(branch="본선(Alertmanager)", step="4", where="webhook ⑥ → it-collector alertmanager_to_display.yaml(http_server /alertmanager_to_display/alertmanager)",
         how="HTTP POST(send_resolved true) → sql_raw(postgres, 계정 ops)",
         fmt="webhook JSON {alerts[…]} → 한 alert 씩(unarchive) → SQL 행",
         fields="firing: alert.alert_group(asset_id, rule_id, first_ts, last_ts, state 'ACTIVE') upsert + alert.alert_event(ts=startsAt, asset_id, rule_id, tag, value(double), severity, detector, detail, display_state 'DISPLAYED', group_id); resolved: alert_group SET state='CLEARED', last_ts=endsAt",
         change="열린 묶음이 있으면 last_ts 만 갱신(count 는 올리지 않음). resolved 는 행 추가 없이 묶음만 닫음",
         keep="PostgreSQL plant.alert(alert_event 추가 전용, alert_group 은 ops 만 UPDATE)",
         ref="alertmanager_to_display.yaml:4-55; 4_it/db-postgres/init/10_schema.sql:68-86"),
    dict(branch="본선(Alertmanager)", step="5", where="같은 스트림 매핑 → Kafka alerts.display",
         how="kafka_franz 키 = asset, max_in_flight 1",
         fmt="JSON",
         fields="{ts=annotations.ts_ns(number), text:'MM-DD HH:MM:SS UTC | severity | tag | alertname', asset, tag, alert_type, severity, group_id}",
         change="source=plant·firing 만 남기고 나머지(resolved·억제 상태) 삭제. detail·value·detector 버림",
         keep="Kafka 1 파티션, 7일",
         ref="alertmanager_to_display.yaml:56-70; create-topics.sh:25"),
    dict(branch="본선(Alertmanager)", step="6", where="it-collector ③ display_to_dmz.yaml",
         how="Kafka group it-collector-display(latest) → MQTT dmz-broker 토픽 AR-100/alert/display, it-collector 계정, qos 1, retained true",
         fmt="MQTT JSON",
         fields="위 alerts.display 필드 그대로",
         change="없음(보존 메시지라 마지막 1건만 남음)",
         keep="DMZ 브로커 보존 메시지 1건",
         ref="4_it/collector-bento/streams/display_to_dmz.yaml:1-17; dmz acl:21-24"),
    dict(branch="본선(Alertmanager)", step="7", where="ot-hub 브리지 in → FUXA",
         how="'AR-100/alert/display in 0'(QoS 0 으로 내려받음) → OT 허브 → FUXA 태그 AnalysisAlert(memaddress 'text')",
         fmt="FUXA 태그 문자열",
         fields="text",
         change="text 만 화면 '분석 경고(참고)'로(알람 목록과 따로, 소리·조작 없음)",
         keep="OT 허브 보존 메시지, FUXA 메모리",
         ref="2_ot/factory-broker-mosquitto/mosquitto.conf:42-44; build_project.py:107; dashboard.py"),
    dict(branch="AI 사건", step="8", where="business intake_loop → consumer.persist_message",
         how="Kafka group ar100-ai-incidents-v1, earliest, 저장 뒤 동기 commit",
         fmt="bytes → pydantic Alarm(extra forbid)",
         fields="Alarm{ts(int>0), site, device, tag, value(float, inf/nan 금지), alert_type, severity, detector, detail(str ≤10000)}; manufacturing_inbox(topic, partition_id, offset_id, status 'accepted'|'rejected', incident_id, raw_payload, error)",
         change="검증 실패는 원문·오류를 inbox 에 'rejected' 로 남김(사건 없음)",
         keep="AI DB(ai) manufacturing_inbox",
         ref="business.py:185-203; consumer.py:12-43; api.py:19-29"),
    dict(branch="AI 사건", step="9", where="api.ingest (AI 묶기)",
         how="PostgreSQL DATABASE ai, advisory lock(correlation_key)",
         fmt="SQL 행",
         fields="alarm_key=sha256(정렬 JSON); correlation_key=[site, device, group] — group: IT-102·VT-101 & CEP_BEARING|THRESHOLD_USL|ZSCORE → 'mixer-current-vibration-v1', TT-101·TT-102·TT-104·FT-103·PDT-103 & 임계·ZSCORE → 'reactor-thermal-cooling-v1', PT-101·PT-102·LT-102 & THRESHOLD_USL → 'reactor-pressure-v1', 그 밖 '<tag>:<alert_type>'; manufacturing_incidents(id, alarm_key, site, device, status 'received', revision, review_revision, alarm(첫 경보 jsonb), correlation_key, first_ts, last_ts, alarm_count); manufacturing_alarm_links(alarm_key, incident_id); manufacturing_events(kind 'alarm_received'|'alarm_correlated', payload=Alarm)",
         change="같은 alarm_key 는 중복으로 무시. 열린 사건(같은 키, first_ts−30 s ≤ ts ≤ last_ts+30 s)이 있으면 묶고 alarm_count·revision +1, 새 서명(tag·type·detector·severity)이거나 더 이른 ts 면 review_revision +1",
         keep="AI DB(보존 정책 없음)",
         ref="api.py:42-142"),
    dict(branch="AI 사건", step="10", where="agent.run_auto → auto_candidates → analyze",
         how="2 s 루프(AI_AUTO_ANALYZE=1), 모델 설정 시",
         fmt="SQL 조회 → 분석 실행 행",
         fields="manufacturing_analysis_runs(id, incident_id, status 'running', model, review_revision); events auto_analysis_started | auto_analysis_skipped{reason, review_revision}",
         change="조건: status received, 새 서명 뒤 15 s 조용, alarm_count ≥3, 마지막 경보 30 s 안, 한계 경보(THRESHOLD_USL·THRESHOLD_LSL·CEP_BEARING) 있음, 온톨로지 증상에 결정 연결. 아니면 그 review_revision 에서 건너뜀 기록 → 이후 'plan' 리니지",
         keep="AI DB",
         ref="agent.py:604-673"),
  ],
  ends=[
    "PostgreSQL alert.alert_event·alert_group(ISA-18.2 기록, 감사·조회)",
    "FUXA '분석 경고(참고)' 한 줄(마지막 1건)",
    "AI 사건(manufacturing_incidents) → 자동/수동 분석 → 대응안 카드",
    "IT InfluxDB alerts 측정 → Grafana 03(감시 프로필일 때)",
  ],
  loss=[
    "Alertmanager 가 억제한 alert 는 webhook 으로 오지 않아 alert_event 에 개별 기록이 남지 않음(억제 시작·해제만 기록). AI 사건 쪽은 억제와 무관하게 전부 접수",
    "ML·COMMAND_DISAGREE 는 asset_of 에 없는 태그라 asset=device('reactor-line-01') → SuppressedByDesign(equal asset) 로 억제되지 않고, 설비별 묶음도 라인 단위로 섞임",
    "endsAt = 마지막 alert + 60 s: 60 s 조용하면 묶음이 닫히고 다음 alert 는 새 묶음·새 DISPLAYED 행",
    "FUXA 표시: 보존 메시지 1건이라 해제돼도 마지막 문구가 남고, 여러 묶음이 겹치면 마지막 것만 보임. 브리지 in QoS 0",
    "④·③ 수집 스트림 latest 시작: 수집기가 멈춘 동안의 alert 는 Alertmanager·FUXA 에 안 감(AI 접수는 earliest 라 따라잡음)",
    "AI 접수: 저장 중 예외면 그 메시지를 되감지 않고 다음 메시지 commit 으로 건너뜀(persist_message 는 DB 장애 시 HTTPException 을 냄)",
    "AI 묶기 30 s 틈: 그보다 띄엄띄엄 오면 별도 사건. 동일 payload(ts 포함)는 중복으로 무시",
  ],
)

LINEAGE["req"] = dict(
  title="작업 요청(AI 승인 → PLC 명령 또는 정비팀 작업 → 응답 → 판정)",
  origin="AI 승인 시 actions._request_action()(대응안 stop_mixer·enable_cooling) 또는 정비 실행기 maintenance.submit()(계획 control·field 단계)가 workflow.request 행을 만든다 (5_ai/server/knowledge/backend/src/modules/operations/actions.py:315-340; maintenance.py:55-76)",
  hops=[
    dict(branch="본선", step="1", where="knowledge · actions._request_action / maintenance.submit → 공용 업무 DB(plant)",
         how="psycopg 한 트랜잭션, 계정 ai_app",
         fmt="SQL 행",
         fields="workflow.request(job_order_id='ai-'+uuid4 hex, work_master_id, equipment_id, job_order_parameters(jsonb, 단계 파라미터 [{id, value}] 또는 []), requester='ai-ops', requester_type='ai', approver=AI_APPROVER_ID('operator-01'), context{summary, proposal_id, plan_step?}, incident_id, proposal_id, created_at=now()); workflow.request_event(kind 'approved', status 'APPROVED', reason=승인 메모, detail{action, before_seq | plan_option, plan_step}, source 'ai-app'); audit.log ×2 (ai/ai-ops/propose, human/<approver>/approve)",
         change="생성. approver 는 화면의 실제 승인자가 아니라 환경변수 고정값. 요청자 필드 이름은 requester(requester_id 아님), 발행 시각은 created_at(issued_at 없음)",
         keep="PostgreSQL workflow.request·request_event·audit.log(추가 전용, UPDATE·DELETE 트리거 거부)",
         ref="actions.py:281-340; maintenance.py:55-76; 4_it/db-postgres/init/10_schema.sql:29-66, 88-116"),
    dict(branch="본선", step="2", where="knowledge · _announce_approved",
         how="Kafka request.approved, 키 = job_order_id, acks all, message.timeout 5 s",
         fmt="JSON",
         fields="{job_order_id}",
         change="내용은 빼고 ID 만(정본은 PostgreSQL). 전달 실패 → request_event 'not_dispatched'/'KAFKA_UNAVAILABLE' 추가하고 보내지 않음",
         keep="Kafka 3 파티션, 30일",
         ref="actions.py:297-312, 336-340; create-topics.sh:26"),
    dict(branch="본선", step="3", where="it-collector ⑦ request_dispatch.yaml(발송)",
         how="Kafka group it-dispatcher → sql_raw(계정 dispatcher) → HTTP POST http://dmz-gateway:8088/requests(Bearer GATEWAY_CLIENT_TOKEN, timeout 5 s, 재시도 0)",
         fmt="SQL 행 → JSON 요청 본문",
         fields="본문 {job_order_id, work_master_id, equipment_id, job_order_parameters(배열), requester, requester_type, approver, created_at(epoch 초 float), context(객체, NULL 이면 뺌)}; 먼저 request_event('dispatched', detail{gateway}, source 'dispatcher') + audit(system, it-dispatcher, dispatched)",
         change="workflow.request_status 뷰에서 마지막 사건이 'approved' 인 요청만(재수신 시 다시 안 보냄). incident_id·proposal_id 는 보내지 않음",
         keep="없음",
         ref="4_it/collector-bento/streams/request_dispatch.yaml:1-44"),
    dict(branch="본선", step="4", where="dmz-gateway(Node-RED) f_check(check.js) → mq_out → f_ack(ack.js)",
         how="HTTP in /requests(본문 원문) → MQTT 5 dmz-broker 'AR-100/request/in' QoS 1, retain false, messageExpiryInterval 30 s → PUBACK 2 s 안이면 202, 아니면 503",
         fmt="HTTP JSON → MQTT 5 JSON",
         fields="발행 본문 = 요청 본문 + expires_at(floor(now)+30, epoch 초); HTTP 응답 ⓐ 202 {status:'ACCEPTED', job_order_id, expires_at} | 4xx/503 {status:'REJECTED', reason, job_order_id}",
         change="검사: 토큰 → JSON Schema(draft-07, additionalProperties false, job_order_id 패턴 ^[A-Za-z0-9._:-]{8,80}$) → 허용 작업·설비·파라미터 범위 → 요청자(ID·종류 쌍)·승인자 허용 목록 → created_at 나이 −2~10 s → 중복(35 s 안 같은 ID) → 브로커 연결. 만료 시각 덧붙임",
         keep="flow 메모리 seen(35 s)·pending·counters",
         ref="3_dmz/gateway-nodered/src/check.js:1-80; ack.js:1-12; generate.py:149-171, 348-393; shared/registry/generated/work_masters.allow.json"),
    dict(branch="본선", step="5", where="it-collector ⑦ 응답 ⓐ 기록",
         how="sql_raw(dispatcher) + Kafka fan_out request.events·audit.copy",
         fmt="SQL 행 · JSON",
         fields="request_event(kind 'gateway_accepted'|'gateway_rejected', status, reason, detail{http_status, expires_at, latency_ms}, source 'dispatcher'); audit(system, it-dispatcher, kind, subject=status, detail{…, reason}); request.events {job_order_id, kind, status, reason, http_status, expires_at, latency_ms, at}; audit.copy {actor_type, actor_id, action, job_order_id, status, reason, at}",
         change="HTTP 400·401·409·422·503 도 정상 응답으로 받음. 연결 실패 → status REJECTED, reason 'GATEWAY_UNREACHABLE' 또는 'HTTP_<코드>'",
         keep="PostgreSQL; Kafka request.events·audit.copy 30일(소비 코드 없음)",
         ref="request_dispatch.yaml:45-93"),
    dict(branch="본선", step="6", where="dmz-broker → ot-hub 브리지 in → OT 수신기 in_req(mqr, ot-receiver 계정)",
         how="'AR-100/request/in in 1'(MQTT 5, 브리지 세션 3600 s), 수신기 MQTT 5 cleansession false·session expiry 3600, QoS 1",
         fmt="MQTT 5 JSON(메시지 만료 30 s 가 브리지로 넘어감)",
         fields="요청 본문 + expires_at",
         change="브리지가 끊긴 채 30 s 지나면 브로커가 만료 메시지를 버림",
         keep="DMZ·OT 브로커 persistence(만료 전까지)",
         ref="2_ot/factory-broker-mosquitto/mosquitto.conf:25-44; flows.json:628(in_req)"),
    dict(branch="본선", step="7", where="OT 수신기 ch_schema → js_req(json 노드 스키마 재검사) → f_req(receiver_request.js) | catch → f_invalid",
         how="Node-RED, global jobSchema·workMastersOt·registry",
         fmt="JSON → job 객체 → MQTT 메시지 묶음",
         fields="응답 ⓑ AR-100/response/{id} {job_order_id, stage:'receipt', status:'AUTO_ACCEPTED'|'OPERATOR_WAIT'|'REJECTED', reason('REMOTE_AUTO'|'STORED'|NOT_ALLOWED·EQUIPMENT_MISMATCH·PARAMETER_MISSING·PARAMETER_RANGE·EXPIRED·PLC_UNAVAILABLE·LOCAL_MODE·MAINTENANCE_REQUIRED·MAINTENANCE·MODE_UNKNOWN·SCHEMA_INVALID(+detail)), ts(ISO)}; job {job_order_id, work_master_id, equipment_id, desc, code, value, command_topic, job_hash, received_at, expires_at(정수), kind, field_task, release_maintenance, requires_maintenance, context_summary='[AI ai-ops] '+context.summary 120자}; 대기 목록 …/request/pending(retain) {count, head_job, head_wm, head_desc, head_context, head_wait_s, items[{job_order_id, work_master_id, desc}]}",
         change="중복(QoS 1 재전송) 무시: seen[id]=expires_at+60. 파라미터 → value = round(값 × scale)(온도 ×10), 고정값이면 fixed_value. job_hash = sha256(job_order_id) 앞 8 hex(32비트). requester·approver·created_at·job_order_parameters·context 원본은 여기서 버림. REMOTE_AUTO: 즉시 명령(또는 정비팀), REMOTE_MANUAL: 대기 목록 저장, 그 밖 거부",
         keep="flow 메모리 seen·pending(엣지 재시작 시 잃음)",
         ref="2_ot/edge-nodered/src/receiver_request.js:1-69; receiver_invalid.js:1-10; generate.py:313-320; shared/registry/generated/work_masters.ot.json"),
    dict(branch="운전원 대기(REMOTE_MANUAL)", step="8", where="FUXA 받은 요청 → …/request/decision → f_dec(receiver_decision.js) / f_timer(receiver_timer.js)",
         how="FUXA 발행 태그 Req_accept·Req_reject → MQTT(fuxa 계정) AR-100/reaction/reactor-line-01/request/decision",
         fmt="JSON",
         fields="결정 {job_order_id(=head_job), decision:'accept'|'reject', ts}; 응답 ⓒ-1 {job_order_id, stage:'operator', status:'OPERATOR_ACCEPTED'|'OPERATOR_REJECTED'|'REJECTED', reason('OPERATOR'|'MAINTENANCE'|'MODE_<모드>'|'MAINTENANCE_REQUIRED'|'OPERATOR_TIMEOUT'), ts}",
         change="10 s 넘은 결정·보존 메시지·대기 목록에 없는 ID 무시. 수락이면 새 expires_at = 지금+30, operator_accepted 1. 60 s(벽시계) 넘게 대기면 OPERATOR_TIMEOUT. FUXA 는 맨 앞 1건에만 결정",
         keep="flow 메모리 pending",
         ref="receiver_decision.js:1-40; receiver_timer.js:1-27; 2_ot/hmi-fuxa/build_project.py:101-106"),
    dict(branch="PLC 명령(control)", step="9", where="OT 수신기 → ot-hub {설비}/cmd/request → edge in_rqcmd → f_rqcmd(request_cmd.js) → fw_rq1 → f_rqseq → fw_rq2",
         how="MQTT QoS 1(edge 계정 cmd/+ 읽기) → Modbus FC16 %MW21..27(홀딩 1045..1051) 뒤 %MW20(1044) 순번",
         fmt="JSON → Modbus 레지스터(WORD 7 + 1)",
         fields="명령 {job_order_id, code, value, expires_at, operator_accepted 0|1, job_hash}; 레지스터 [code, value&0xFFFF, exp hi, exp lo, accepted, hash hi, hash lo] + rq_seq",
         change="보존 메시지·형식 오류는 경고만 남기고 버림(응답 없음). jobByHash[job_hash]=job_order_id(최근 64, 메모리). 순번은 PLC ACK 순번을 이어받음",
         keep="edge flow 메모리 rqSeq·jobByHash",
         ref="2_ot/edge-nodered/src/request_cmd.js:1-19; write_seq.js; flows.json:477; generate.py:119, 303-307"),
    dict(branch="PLC 명령(control)", step="10", where="plc · main.st 9단계(src=2 외부 요청 채널)",
         how="100 ms 주기, %MW20 순번 변화 = 새 명령",
         fmt="Modbus 레지스터 → ACK 레지스터",
         fields="입력 rq_code, rq_value(INT), rq_exp(DWORD), rq_accepted, rq_hash; 출력 st_rq_ack_seq, st_rq_ack_code(0 ACCEPTED,1 LOCAL_MODE,2 MAINTENANCE,3 MODE,4 RANGE,5 INTERLOCK,6 EXPIRED,7 DUPLICATE,8 UNKNOWN_COMMAND,9 ESTOP,10 NO_TIME_SYNC,11 PHYSICS), st_rq_ack_hash_hi/lo",
         change="검사: 코드·범위 → 시각 동기(엣지가 %MW0..1 에 1 s 마다 epoch) → 만료(now_s > exp) → 해시 중복(최근 8) → 모드(REMOTE_MANUAL 은 operator_accepted 필요)·정비 모드(외부 요청 전부 거부) → 비상정지·인터록·건식운전. 수용 시 명령 반영(설정값은 hold 3000 주기=300 s 스케줄 제외)",
         keep="PLC 메모리(seen_hash 8개)",
         ref="1_control/plc-openplc/project/pous/programs/main.st:192-291; time_sync.js"),
    dict(branch="PLC 명령(control)", step="11", where="edge status.js ACK → ack/request → 수신기 receiver_plc_ack.js → 응답 ⓒ-2",
         how="'status' 리니지 2·13단계와 같음",
         fmt="JSON",
         fields="{job_order_id, stage:'plc', status:'ACCEPTED'|'REJECTED', reason=ACK 이름, plc_ack_code, ts}",
         change="해시 → job_order_id(엣지 메모리)",
         keep="없음",
         ref="status.js:55-61; receiver_plc_ack.js:1-8"),
    dict(branch="현장 정비(field)", step="12", where="수신기 f_batch → f_crew_req(crew_request.js) → http_crew → f_crew_resp(crew_response.js)",
         how="HTTP POST http://plant-sim:8082/tasks, Basic(FIELD_CREW_USER), requestTimeout 60 s",
         fmt="JSON",
         fields="요청 {job_order_id, task(field_task), release_maintenance}; 정비팀 응답 {job_order_id, status 'DONE'|'DONE_NO_FAULT'|'REJECTED', reason?('FIELD_SAFETY'|'UNKNOWN_TASK'|'BAD_JOB_ID'), task, effective, finding, plant_duration_s, wall_s, maintenance_released?}; 응답 ⓒ field {job_order_id, stage:'field', status, reason(=reason 또는 finding), finding, effective, task, plant_duration_s, wall_s, maintenance_released, ts}",
         change="가상 정비팀: 같은 job_order_id 는 한 번만 수행(이전 결과 반환), 안전 확인 → 격리 → 설비 시간/배속 만큼 대기 → field_apply(열화 상태 복구·소견) → 격리 해제 → 필요 시 정비 해제 키. HTTP 실패는 status 'UNKNOWN'(재전송 없음)",
         keep="plant-sim crew_jobs 메모리(256 넘으면 128 남김)",
         ref="2_ot/edge-nodered/src/crew_request.js; crew_response.js; 0_plant/simulator/sim.py:155-192, 335-352; plant.py:401-466"),
    dict(branch="본선", step="13", where="수신기 mq_rout → ot-hub → 브리지 out 'AR-100/response/# out 1' → dmz-broker → it-collector ①",
         how="MQTT QoS 1 → Kafka request.responses, 키 = job_order_id",
         fmt="JSON",
         fields="응답 payload 그대로(job_order_id, stage, status, reason, ts, + plc_ack_code | detail | finding·effective·task·plant_duration_s·wall_s·maintenance_released)",
         change="없음(토픽 조각을 붙이지 않음)",
         keep="Kafka 3 파티션, 30일",
         ref="mosquitto.conf:41; dmz_to_kafka.yaml:29, 38, 42; create-topics.sh:28"),
    dict(branch="본선", step="14", where="business on_response",
         how="Kafka group ar100-business-v2(latest) → plant DB(계정 ops)",
         fmt="SQL 행",
         fields="request_event(kind=stage('receipt'|'operator'|'plc'|'field'), status, reason, detail=응답 전체, source 'ot-receiver'); audit.log(system, ot-receiver, 'response_<stage>', jid, subject=status, detail{reason}); audit.copy",
         change="workflow.request 에 없는 ID 는 기록 안 함(로그만)",
         keep="PostgreSQL(추가 전용)",
         ref="business.py:67-77"),
    dict(branch="본선", step="15", where="business timers()(0.5 s)",
         how="최근 15분 요청의 사건 집계 SQL",
         fmt="SQL 행 + Kafka request.events·audit.copy(·sensor.alerts)",
         fields="request_event(kind 'ack_timeout'|'expired_unconfirmed'|'unconfirmed'|'observed'|'command_disagree', status 'UNKNOWN'|'OK'|'NO_FAULT_FOUND'|'REJECTED'|'DISAGREE', reason, detail{asset, name, value|expected, current | task, field_status}, source 'business')",
         change="ⓐ 수용 뒤 ⓑ 없음 5 s → ack_timeout(끝 아님), expires_at+5 s → expired_unconfirmed. OPERATOR_WAIT 뒤 ⓒ 없음 95 s → unconfirmed. field: DONE → observed OK, DONE_NO_FAULT → observed NO_FAULT_FOUND, 그 밖 → unconfirmed; 결과 없음이 plant_duration/600+30 s 넘으면 unconfirmed. control: plc:ACCEPTED 뒤 상태 일치 → observed, 10 s 넘게 불일치 → command_disagree + sensor.alerts",
         keep="PostgreSQL; workflow.request_status 뷰 = 마지막 사건",
         ref="business.py:107-182"),
    dict(branch="본선", step="16", where="knowledge · _request_action 대기 / maintenance.judge_request",
         how="request_event 0.25 s(조치) · 1 s(정비 틱) 폴링",
         fmt="SQL 행 → 파이썬 결과 dict",
         fields="조치 결과 {status 'stop_verified'|'cooling_command_verified'|'awaiting_operator'|'not_executed'|'uncertain', job_order_id, stage?, reason}; 정비 단계 판정 done|no_fault|failed|waiting|waiting_operator + {field_status, finding, effective, wall_s, plant_duration_s, observed, stage, status, reason}",
         change="진행 사건을 manufacturing_events(action_* ) 로 복사. 조치는 20 s 안에 결론 없으면 uncertain. 재전송 없음",
         keep="AI DB manufacturing_events·manufacturing_proposals.result",
         ref="actions.py:341-369; maintenance.py:86-157"),
  ],
  ends=[
    "PostgreSQL workflow.request·request_event(정본, 현재 상태 = request_status 뷰)·audit.log",
    "AI 대응안 결과·정비 실행기 단계 상태(AI DB) → 화면 진행 표시·보고서",
    "FUXA 받은 요청 대기 목록(운전원 결정)",
    "Kafka request.events·audit.copy(사본, 소비 코드 없음)",
  ],
  loss=[
    "게이트웨이 created_at 나이 10 s: 기록부터 발송까지 Kafka·발송 스트림이 10 s 넘게 밀리면 TOO_OLD 로 거부(재전송 없음)",
    "브리지·수신기가 30 s 안에 못 받으면 MQTT 만료로 버려짐 → expired_unconfirmed. 수신기 PLC_UNAVAILABLE 검사는 보존된 run_state·field_comm 만 봄",
    "수신기·엣지 메모리(seen·pending·jobByHash): 엣지 재시작 시 대기 중 요청과 ACK 대응이 사라짐 → unconfirmed 또는 plc 응답 없음(업무 서비스는 plc 응답이 없으면 판정을 내지 않고 15분 창이 지나면 손 놓음)",
    "엣지 request_cmd 형식 오류·보존 메시지는 경고만 하고 응답 없음",
    "정비팀 HTTP 60 s 제한: 배속을 낮춰 작업이 60 s 넘으면 field UNKNOWN(작업은 정비팀 쪽에서 계속될 수 있음)",
    "업무 서비스·발송 스트림 예외 시 해당 Kafka 메시지를 되감지 않음(다음 commit 으로 건너뜀) — 응답 사건이 빠질 수 있음",
    "운전원 결정은 FUXA 대기 목록 맨 앞 1건에만",
  ],
)

LINEAGE["mes"] = dict(
  title="MES 흉내 생산 지시(작업 요청의 두 번째 출처)",
  origin="it-collector ⑧ mes_requester.yaml 의 http_server POST /mes_requester/orders (4_it/collector-bento/streams/mes_requester.yaml:8-22)",
  hops=[
    dict(branch="본선", step="1", where="it-collector ⑧ http_server /orders",
         how="HTTP POST http://it-collector:4195/mes_requester/orders",
         fmt="JSON",
         fields="입력 {work_master_id, equipment_id, job_order_parameters[{id, value}], planner, summary}",
         change="생성: job_order_id='mes-'+uuid_v4(하이픈 제거), approver=planner, summary 없으면 'MES 생산 지시', 파라미터 없으면 []",
         keep="없음",
         ref="mes_requester.yaml:8-22"),
    dict(branch="본선", step="2", where="⑧ sql_raw(계정 mes, plant DB 한 문장 CTE)",
         how="postgres",
         fmt="SQL 행",
         fields="workflow.request(job_order_id, work_master_id, equipment_id, job_order_parameters, requester='mes-01', requester_type='mes', approver, context{summary}); request_event('approved', 'APPROVED', detail {}, source 'mes-01'); audit.log(system, mes-01, propose, subject=work_master_id), audit.log(human, <planner>, approve, detail{note: summary})",
         change="incident_id·proposal_id 없음. FK(registry.work_master·equipment)·NOT NULL(approver) 위반이면 실패 → 422 {status 'REJECTED', reason 'RECORD_FAILED'}, 메시지 삭제",
         keep="PostgreSQL(추가 전용)",
         ref="mes_requester.yaml:23-49; 10_schema.sql:30-41, 107"),
    dict(branch="본선", step="3", where="⑧ sync_response → Kafka request.approved",
         how="HTTP 응답 202 {job_order_id}, kafka_franz 키 = job_order_id",
         fmt="JSON",
         fields="{job_order_id}",
         change="내용 버리고 ID 만",
         keep="Kafka 30일",
         ref="mes_requester.yaml:40-55"),
    dict(branch="본선", step="4", where="이후 'req' 리니지 3~15단계와 같음(발송 → 게이트웨이 → 수신기 → PLC/정비팀 → 응답 → 업무 서비스 판정)",
         how="같음",
         fmt="같음",
         fields="requester='mes-01', requester_type='mes', approver=planner(게이트웨이 허용 목록 operator-01·operator-02·planner-01 이어야 함). FUXA 대기 목록 head_context='[MES mes-01] '+summary",
         change="게이트웨이가 요청자 (mes-01, mes) 쌍과 승인자를 검사",
         keep="같음",
         ref="shared/registry/equipment.yaml:187-191; check.js:46-47; receiver_request.js:54-55"),
  ],
  ends=[
    "PostgreSQL workflow·audit 기록(결과를 읽어 가는 MES 쪽 소비자는 없음)",
    "FUXA 받은 요청(REMOTE_MANUAL) · PLC 설정값 변경",
  ],
  loss=[
    "MES 스트림은 승인자·허용 작업을 검사하지 않음 — 게이트웨이에서 거부되면 gateway_rejected 로만 남고 MES 호출자는 202 를 이미 받음",
    "202 응답 시점이 Kafka 전달 확인 뒤인지는 Bento sync_response 동작에 달림(코드상 sync_response 가 출력 앞에 있음, 미확인)",
    "나머지 손실 지점은 'req' 와 같음",
  ],
)

LINEAGE["plan"] = dict(
  title="정비 계획 → 실행 → 회복 판정 → 작업 보고서",
  origin="AI 분석 실행 agent.investigate() 의 구조화 출력 GroundedProposal(action='maintenance_plan', option_id) → actions.create_proposal() → build_plan() (agent.py:287-400; actions.py:170-267)",
  hops=[
    dict(branch="본선", step="1", where="knowledge · agent.investigate 도구 evaluate_maintenance_options → decision.analyze",
         how="LLM(LangChain agent) 도구 호출, 결정론 계산",
         fmt="파이썬 dict → 도구 결과 JSON(manufacturing_events agent_tool_result)",
         fields="{computed_at, assessment{fm: supported|refuted|unknown|not_applicable}, decisions[{decision_id, name, question, options[{option_id, name, kind, treats, impacts[{kpi, name, owner, unit, expr, value}], total, rules[{rule_id, then, reason, policy}], excluded, eligible, eligibility, errors, procedure, derived, executable, steps(문장)}], recommended, runner_up, money_best_but_excluded, recovery{all, hold_s, timeout_s, section}, inputs, flips[…], facts_used[…]}], kpis, plant_status, method}",
         change="'fact' 리니지 계산 결과. 모델에게는 단계를 '순번. [kind] say' 문장으로 줄여 줌",
         keep="AI DB manufacturing_events",
         ref="agent.py:175-181, 350-359; decision.py:173-288"),
    dict(branch="본선", step="2", where="agent → GroundedProposal(구조화 출력)",
         how="ToolStrategy, 인용·option_id·고장모드 ID 를 Literal 로 제한",
         fmt="pydantic Proposal",
         fields="{expected_revision, summary(5줄 머리 [관측]…[승인 시 영향]), action:'maintenance_plan'|'inspect_only', option_id, citations[document_id], uncertainties[], cause_assessment[{failure_mode, status, evidence}]}",
         change="필수 도구 6~7개를 다 부르지 않으면 실패. 근거 부족이면 NeedsEvidence(대응안 없음)",
         keep="AI DB(events agent_model_output)",
         ref="agent.py:86-129, 132-172, 376-400"),
    dict(branch="본선", step="3", where="actions.create_proposal → build_plan → decision.materialize",
         how="결정 엔진 재계산 + 단계 고정",
         fmt="SQL 행(AI DB manufacturing_proposals)",
         fields="manufacturing_proposals(id, incident_id, status 'pending', incident_revision, body(Proposal), evidence(조회 근거 전체), state_fingerprint, origin 'ai-run:<run>:<model>', plan, expires_at=now+5분); plan {decision_id, option_id, option_name, treats, procedure, steps[{order, kind, say, wm, abort_on_no_fault, status 'pending', equipment_id, desc, parameters[{id, value}], plant_duration_s | until, timeout_s | plant_hours}], recovery{all, hold_s, timeout_s, section}, base_commands, facts_at_plan{key: value}, evaluation(고른 결정 1개), assessment, symptoms, failure_modes{fm: {name, symptom, field_checks}}, rank, recommended, differs_from_recommended}",
         change="검사: 인용 ⊆ 조회 문서, 대안 자격·제외·계산 가능·실행 단계 있음, 절차 문서 인용. 파라미터 식을 지금 명령값 b_* 로 계산해 작업 정의 범위 안인지 확인. 이전 pending 대응안 superseded, 사건 status 'awaiting_review', 이벤트 proposal_created",
         keep="AI DB",
         ref="actions.py:170-267; decision.py:291-339"),
    dict(branch="본선", step="4", where="담당자 승인(화면 IncidentReview → /api/operations/analysis/{run}/decision → agent.resume → execute → actions.decide → start_plan)",
         how="HTTP POST {decision:'approve'|'reject', note} → LangGraph HITL 재개(AsyncPostgresSaver)",
         fmt="SQL 행 갱신",
         fields="manufacturing_proposals status 'executing', decision{decision, note}, started_at, result{status 'executing_plan', reason, plan_state}; plan_state {status, phase 'steps', current 0, started_at, approver(AI_APPROVER_ID), approval_note, before{at, readings, commands, interlock, maintenance, mode}, steps(복사), verify None, report None, reason, evaluation_at_approval{total, rank, recommended}}; 사건 status 'executing'; 이벤트 action_authorized{proposal_id, note, before, plan, current_observations, knowledge_sha256}",
         change="재검사: 만료(5분)·검토 버전·상태 지문(스위치·인터록·정비)·지식 지문(문서·설비 관계) → 지금 사실값·관측으로 재계산해 대안이 여전히 자격·비제외·계산 가능해야 함. reject → status rejected, 사건 unresolved",
         keep="AI DB + LangGraph 체크포인트(PostgreSQL)",
         ref="agent.py:414-437, 552-562; actions.py:372-405, 462-484; maintenance.py:41-51"),
    dict(branch="본선", step="5", where="maintenance.run → tick() → advance()(1 s, knowledge 프로세스 안)",
         how="FOR UPDATE 잠금으로 대응안 한 건씩, 단계별 작업 요청 발행(→ 'req' 리니지)",
         fmt="plan_state JSON 갱신",
         fields="steps[i] {…, started_at, job_order_id, status 'sent'|'running'|'done'|'done_no_fault'|'no_fault'|'failed', field_status, finding, effective, wall_s, plant_duration_s, observed, waiting_operator, remaining_s, reason, finished_at}; 이벤트 maintenance_progress{proposal_id, phase, step{order, kind, say, status, finding, job_order_id, reason}}",
         change="control·field: submit → judge_request(제한 control 60 s, field plant_duration/600+60 s, 운전원 대기면 +95 s). operator: until 식(i_interlock == 0 등)이 참이 될 때까지(timeout 기본 180 s). wait: plant_hours×3600/600 초. DONE_NO_FAULT + abort_on_no_fault → cause_mismatch 로 중단. 실패 시 정비 모드를 켰고 아직 안 풀었으면 WM-FLD-LOTO-RELEASE 정리 단계를 붙임(phase cleanup)",
         keep="AI DB manufacturing_proposals.result.plan_state(전이마다 저장), manufacturing_events",
         ref="maintenance.py:109-177, 214-247, 373-417, 434-443; host/app.py:45"),
    dict(branch="본선", step="6", where="advance() phase 'verify' (회복 판정)",
         how="매 틱 live_state(DMZ 사본) + 사실값으로 회복 식 평가",
         fmt="plan_state.verify",
         fields="verify {started_at, within_since, held_s, samples[≤240]{at, <태그>}, last{at, results[{criterion, ok, missing?}]}}; ps.outcome 'recovered'|'not_recovered'",
         change="recovery.all 식이 모두 참인 상태가 hold_s(예: 30 s) 이어지면 recovered, timeout_s(180~240 s) 넘으면 not_recovered. 관측이 없으면 거짓",
         keep="AI DB",
         ref="maintenance.py:178-205; decision.py:31-63, 89-108"),
    dict(branch="본선", step="7", where="tick() phase 'done' → report()",
         how="파이썬 계산(기록·사실값·DMZ 이력)",
         fmt="보고서 dict",
         fields="{work_order_id='WO-<yymmdd>-<proposal id 앞 8자>', headline, outcome, reason, cleanup, option{id, name, decision}, approver, approval_note, started_at, finished_at, steps[{order, kind, say, wm, status, job_order_id, finding, reason, wall_s}], findings[{order, say, finding, field_status}], before_after[{tag, before, after}], recovery{criteria, hold_s, held_s, last}, kpi{predicted{kpi: value}, predicted_total, actual{production_loss, maint_cost, downtime_plant_h, field_work_plant_h, parts[{item, cost}], batch_scrapped, over_limit_tag, over_limit_plant_h, quality_loss|equipment_risk}}, next}",
         change="실적: 정지 시간(벽시계×600/3600)×mes_hour_value + 배치 폐기, 현장 작업 h×cmms_labor_per_h + 부품(효과 있는 DONE 만), 상한 초과 설비 시간×사실값(DMZ 이력 GOOD 행). 예상은 계획 당시 evaluation 의 impacts",
         keep="AI DB: proposals status 'resolved'|'unresolved', result{status=outcome, reason, plan_state, report}; 사건 status 동일; 이벤트 maintenance_report",
         ref="maintenance.py:250-370, 393-405"),
    dict(branch="본선", step="8", where="_record_work_order → plant DB enterprise.work_order",
         how="psycopg(계정 ai_app), ON CONFLICT (id) DO NOTHING",
         fmt="SQL 행",
         fields="enterprise.work_order(id=work_order_id, incident_id(text), proposal_id(text), equipment_id(첫 단계 설비), option_id, status=outcome, opened_at=to_timestamp(started_at), closed_at=to_timestamp(finished_at), approver, report jsonb, created_at)",
         change="보고서 통째로 jsonb. 실패해도 로그만(보고서는 AI 사건 기록에 남음)",
         keep="PostgreSQL plant.enterprise.work_order(ai_app INSERT·SELECT, ops·reader SELECT)",
         ref="maintenance.py:419-431; 4_it/db-postgres/init/30_enterprise.sql:18-29, 54-57"),
    dict(branch="재사용", step="9", where="화면 MaintenancePlanCard · /api/operations/maintenance/work-orders · agent.precedents",
         how="HTTP 조회 / SQL",
         fmt="JSON",
         fields="카드: plan.evaluation.decisions[0](options·flips·facts_used), plan_state, report; 작업 이력 목록 {id, incident_id, option_id, status, opened_at, closed_at, approver, headline}; 선례 this_incident·history_other_incidents{option_id, status, reviewer_note, headline, findings, next}",
         change="선례는 work_order 표가 아니라 manufacturing_proposals 에서 읽음(다른 사건은 참고용)",
         keep="없음",
         ref="5_ai/web/src/features/operations/MaintenancePlanCard.vue:7-125; decision.py:358-364; agent.py:184-205"),
  ],
  ends=[
    "enterprise.work_order(CMMS 작업 이력 흉내) 보고서",
    "AI DB 대응안·사건 상태(resolved/unresolved)·maintenance_report 이벤트 → 화면 카드",
    "다음 분석의 선례(같은 사건 현장 소견은 원인 평가 근거)",
  ],
  loss=[
    "대응안 5분 만료·검토 버전 변경·상태 지문(스위치·인터록·정비) 변경·지식 지문 변경·승인 시 재계산 결과 제외 → 409, 재분석 필요",
    "단계 결과를 제한 시간 안에 못 읽으면 실패로 멈춤(재전송 없음), 정비 모드가 켜진 채면 정리 단계 하나만 더 함",
    "회복 판정은 DMZ live_state(최근 10 s) 기준이라 사본 공백이면 판정이 거짓으로 남아 not_recovered 로 끝날 수 있음",
    "실적 손익은 보고 시점 사실값을 쓰고 예상은 계획 시점 값 → 그 사이 사실값이 바뀌면 비교가 섞임. 상한 초과 시간은 이력 2000행 한도",
    "work_order 기록 실패는 로그만 남고 CMMS 표에서 빠짐",
    "knowledge 재시작 시 실행 중 분석은 interrupted, 실행 중 계획은 plan_state 에서 이어 감(보낸 요청은 결과만 다시 읽음)",
  ],
)

LINEAGE["fact"] = dict(
  title="기업 사실값(가상 MES · ERP · CMMS)",
  origin="PostgreSQL 초기화 스크립트 4_it/db-postgres/init/30_enterprise.sql:31-52 의 INSERT INTO enterprise.fact … ON CONFLICT (key) DO NOTHING (20개 키, 금액 단위 만원)",
  hops=[
    dict(branch="본선", step="1", where="postgres(plant DB) enterprise.fact",
         how="docker-entrypoint-initdb.d(빈 볼륨 첫 기동 때만), 이후 사람이 SQL 로 수정(코드상 갱신 경로 없음)",
         fmt="SQL 행",
         fields="enterprise.fact(key PK, system 'MES'|'ERP'|'CMMS', value double, unit, description, updated_at)",
         change="생성(교육용 가상 값). 다시 실행해도 있는 키는 덮어쓰지 않음",
         keep="PostgreSQL 디스크(pg-data)",
         ref="30_enterprise.sql:10-16, 31-57"),
    dict(branch="본선", step="2", where="온톨로지 YAML → 그래프 InputData·Decision (graph-seed 번들 C)",
         how="build_ontology_bundle.decision_layer → review.publish(Neo4j)",
         fmt="Cypher 노드·관계",
         fields="InputData{key, system, source:'enterprise.fact'}; (Decision)-[:REQUIRES_INPUT]->(InputData) — 결정의 식(shared_derived·recovery·rules.when·options.derived·impacts·steps)에 실제 등장한 사실값 키만; Option.params/derived(JSON 문자열), IMPACTS.expr, Rule.when",
         change="키 이름만 그래프에 들어감(숫자는 안 들어감). 식의 이름은 사실값·o_/usl_/lsl_/c_/b_/opt_/d_/a_/t_<작업>/i_* 규칙 밖이면 빌드 실패",
         keep="Neo4j(graph-data)",
         ref="5_ai/server/build_ontology_bundle.py:201-274; 5_ai/ontology/v2/kg/maintenance-decisions.yaml:39-44"),
    dict(branch="본선", step="3", where="knowledge · decision.facts() / environment()",
         how="psycopg plant DB(knowledge 계정 ai_app, 업무 서비스는 ops) SELECT … ORDER BY key",
         fmt="파이썬 dict",
         fields="fact_rows{key: {key, system, value, unit, description, updated_at(ISO)}}; env{<key>: float(value), t_<field_task>: plant_duration_s/3600, usl_<태그>, lsl_<태그>(tags.json), o_<태그>(DMZ live_state), c_<명령>, b_<명령>(계획 기준 명령), i_interlock, i_maintenance}",
         change="value → float. 읽기 실패는 503(판단 불가). 결정의 inputs 키가 표에 없으면 503",
         keep="없음(호출 때마다 조회)",
         ref="5_ai/server/knowledge/backend/src/modules/operations/decision.py:66-108, 270-288"),
    dict(branch="본선", step="4", where="decision.score_option / rank / flips",
         how="허용 연산만 있는 식 계산기(ast)",
         fmt="파이썬 dict",
         fields="옵션 {impacts[{kpi, value(소수 1)}], total, rules(EXCLUDE 등), excluded, eligible, derived, errors}; rank 1.. ; recommended, runner_up, money_best_but_excluded; flips[{fact, system, current, flip_value, unit, description, new_recommendation}]; facts_used[{key, system, value, unit, description, updated_at}]",
         change="opt_* = 대안 params, a_<고장모드> = 평가 무게(supported 1, unknown 0.5, refuted·not_applicable 0), d_* 파생값 → KPI 식 합계. 값이 없으면 기본값으로 메우지 않고 계산 불가. 뒤집힘: 사실값 하나씩 ×0.75·1.25·0.5·1.5·0.25·2·0·3·5(_qty 는 0↔1, 0 은 0.5~8) 넣어 권고가 바뀌는 가장 가까운 값",
         keep="없음",
         ref="decision.py:156-267"),
    dict(branch="카드", step="5", where="agent 도구 결과 → 대응안 plan.evaluation · plan.facts_at_plan → 화면 MaintenancePlanCard",
         how="AI DB jsonb → HTTP /api/operations/incidents/{id}/proposals",
         fmt="JSON → Vue",
         fields="카드: 대안별 KPI·합계·제외 규칙, '이 권고가 뒤집히는 조건'(flips 앞 4개: description(system) 지금 current unit → flip_value unit 이면 new_recommendation), '계산에 쓴 기업 사실값'(facts_used: system·description·value unit); /maintenance/facts 엔드포인트는 전체 표",
         change="계획 시점 값으로 고정(facts_at_plan). 화면은 표시만",
         keep="AI DB manufacturing_proposals.plan",
         ref="actions.py:259-266; decision.py:328-332, 352-355; 5_ai/web/src/features/operations/MaintenancePlanCard.vue:7, 77-80"),
    dict(branch="재계산", step="6", where="승인 start_plan · 실행기 operator·verify · 보고서",
         how="facts() 재조회",
         fmt="파이썬 dict",
         fields="evaluation_at_approval{total, rank, recommended}; 회복·운전원 식의 사실값; report.kpi.actual(mes_hour_value·mes_batch_scrap_cost·cmms_labor_per_h·erp_*_cost·mes_offspec_loss_per_h·cmms_overtemp_risk_per_h·cmms_seizure_risk_per_h)",
         change="승인 시점 값으로 다시 순위·제외 검사. 보고서 실적은 보고 시점 값",
         keep="AI DB plan_state·report, enterprise.work_order.report",
         ref="actions.py:462-476; maintenance.py:159-166, 181, 251-296, 382"),
  ],
  ends=[
    "AI 대응안 카드(대안 손익·제외 규칙·뒤집힘 표·사용 사실값)",
    "승인 재검사·정비 실행 조건·작업 보고서 실적 손익 → enterprise.work_order",
  ],
  loss=[
    "초기화 SQL 은 빈 DB 첫 기동 때만 실행되고 ON CONFLICT DO NOTHING 이라, 파일의 값을 고쳐도 기존 DB 에는 반영되지 않음",
    "updated_at 은 기본값(now)뿐이라 사람이 UPDATE 할 때 함께 바꾸지 않으면 갱신 시각이 틀림",
    "결정 inputs 에 없는 키(식에 안 쓰인 사실값)는 뒤집힘 표·facts_used 에 나오지 않음",
    "카드의 값은 계획 시점 고정 → 이후 사실값 변경은 승인 시 재계산에서만 반영(카드 숫자는 그대로)",
  ],
)

LINEAGE["manual"] = dict(
  title="매뉴얼 → 지식 그래프 → 에이전트 검색",
  origin="5_ai/manuals/*.md(10개: front matter document_id·version·applies_to·alarm_types, 본문은 '## ' 로 절 구분)",
  hops=[
    dict(branch="본선", step="1", where="graph-seed(기동 1회) · seed_graph.main",
         how="compose 가 5_ai/manuals·5_ai/ontology·shared/registry·plant.yaml 을 읽기 전용으로 붙임",
         fmt="파이썬 dict 번들 3개(A·B·C)",
         fields="번들 이름, nodes[{id, class, properties}], relationships[{from_id, to_id, type, properties}], unresolved",
         change="결정론 생성(LLM 없음)",
         keep="없음",
         ref="5_ai/server/seed_graph.py:65-85; compose.yml:642-658"),
    dict(branch="본선", step="2", where="번들 A · build_knowledge_bundle.build",
         how="등록부 인벤토리 + 전체 매뉴얼",
         fmt="Batch 후보",
         fields="Document{id=파일 이름, name, source_path, source_sha256, version, environment 'simulation', content(전문)}; DocumentSection{id '<doc>/section/<i>', name(절 첫 줄), content, document_id, source_locator 'section:<i>', source_path}; HAS_SECTION; 모든 설비 DESCRIBED_BY AR100-ASSET-CONTEXT · GOVERNED_BY AR100-MAINT-POLICY; M-101 HAS_PROCEDURE AR100-MIXER-RESPONSE; M-101·R-101 GOVERNED_BY AR100-EVIDENCE-POLICY; INSTALLED_IN·FEEDS; Device·Sensor·ControlPoint·WorkMaster(레지스터 주소 없음)",
         change="front matter 를 떼고 '## ' 로 절 분할(0번 = 머리). section_key 없음",
         keep="없음",
         ref="5_ai/server/build_knowledge_bundle.py:17-71; knowledge/backend/src/modules/ontology/inventory.py:16-71"),
    dict(branch="본선", step="3", where="번들 B · build_ontology_bundle.arm_b / 번들 C · arm_c",
         how="V1 문서 5개(ASSET-CONTEXT·EVIDENCE-POLICY·MIXER-RESPONSE·SENSOR-CONTEXT·THERMAL-RESPONSE)를 뺀 매뉴얼",
         fmt="Batch 후보",
         fields="B: Document·DocumentSection(+section_key: 0번 '본문', 'N.' 로 시작하면 N, 아니면 제목 단어를 '-' 로) · (Asset)-[:HAS_PROCEDURE]->(Document) for applies_to ∩ 등록부 설비. C: 모든 매뉴얼 절 스텁{section_key}; Symptom-DOCUMENTED_IN/INVESTIGATED_BY, FailureMode-DOCUMENTED_IN, Action·Option-PROCEDURE, Decision-VERIFIED_BY, Rule-ENCODES → DocumentSection",
         change="절 이름이 B 에서 0번 절은 ''(A 는 첫 줄)로 덮임. 온톨로지 YAML 의 'DOC#key' 참조를 절 ID 로 해석(없으면 빌드 중단)",
         keep="없음",
         ref="5_ai/server/build_ontology_bundle.py:28-128, 131-190"),
    dict(branch="본선", step="4", where="review.publish(Neo4j 한 트랜잭션)",
         how="bolt://graph:7687, MERGE (n:_Entity:<Class> {_source_id}) SET n += properties; 관계 MERGE SET",
         fmt="Cypher 노드·관계",
         fields="노드 속성 + _source_id, _batch_id(digest), _review_status 'published', updated_at; _ImportBatch{sha256, status, payload, review_note, published_at}; (b)-[:IMPORTED]->(n)",
         change="digest 가 같으면 건너뜀(중복). 뒤 번들이 같은 노드 속성을 덮음(A→B→C 순). 문서 version 이 게시본보다 작거나 없으면 409 로 전체 중단. 번들 C 뒤 이번 판에 없는 v2/* 노드·관계 삭제",
         keep="Neo4j(graph-data)",
         ref="5_ai/server/knowledge/backend/src/modules/ontology/review.py:61-197; seed_graph.py:51-62"),
    dict(branch="본선", step="5", where="seed_graph.embed → fault_ontology.index_sections",
         how="OPENAI_API_KEY 있을 때만. neo4j_graphrag OpenAIEmbeddings(EMBEDDING_MODEL 기본 text-embedding-3-small, OPENAI_BASE_URL)",
         fmt="Neo4j 속성 벡터",
         fields="DocumentSection.v2_embedding(=embed('<name>\\n<content>')), v2_embedded_hash('<len(content)>:<name>'), v2_embed_model; 벡터 색인 section_embedding_v2(cosine, 차원 자동)",
         change="내용 길이·이름·모델이 바뀐 절만 다시 임베딩. 빈/0 벡터면 예외",
         keep="Neo4j",
         ref="5_ai/server/knowledge/backend/src/modules/operations/fault_ontology.py:84-108; seed_graph.py:29-48"),
    dict(branch="본선", step="6", where="seed_graph.embed → tools._embed_entity_nodes",
         how="embedding.embed_texts(5개씩, EMBEDDING_CHUNK_MAX_TOKENS 자름)",
         fmt="Neo4j 속성 벡터",
         fields="_Entity.embedding(=name title content[:1500]); 색인 entity_embedding_vector",
         change="embedding 이 없거나 차원이 다른 노드만. API 실패 시 0 벡터 → 건너뜀(남은 개수·0 벡터가 있으면 시드 종료 코드 1)",
         keep="Neo4j",
         ref="5_ai/server/knowledge/backend/src/modules/ontology/tools.py:668-731; embedding.py:80-102"),
    dict(branch="에이전트 검색", step="7", where="knowledge · agent 도구 search_manual_sections → fault_ontology.search",
         how="VectorCypherRetriever(index section_embedding_v2), 질의 임베딩 같은 모델, top 10 후보",
         fmt="Cypher 결과 → dict",
         fields="{query, results[{section:'<document_id>#<section_key>', heading, content, score, graph_linked}](3개), vector_only(3개), method}",
         change="사건 증상과 그래프로 이어진 절(DOCUMENTED_IN|PROCEDURE|INVESTIGATED_BY|VERIFIED_BY|ENCODES ← … ← Symptom 2단계)을 먼저, 그다음 점수",
         keep="AI DB events(agent_tool_result)",
         ref="fault_ontology.py:111-131; agent.py:345-348"),
    dict(branch="문서 근거", step="8", where="knowledge · evidence.incident_evidence → agent get_asset_documents",
         how="Cypher 읽기 전용: 경보 태그 HAS_SENSOR 설비 + INSTALLED_IN|FEEDS 2단계·상위 설비 → HAS_PROCEDURE|GOVERNED_BY|DESCRIBED_BY Document",
         fmt="dict",
         fields="documents[{document_id(=name), content(전문), source_path, sha256, version}], assets, sensors{tag, unit, lsl, usl, source_sha256}",
         change="절이 아니라 문서 전문. 대응안 citations 는 이 document_id 집합 안에서만(Literal 스키마), 승인 시 지식 지문(assets·documents·sensors 정렬 sha256) 비교",
         keep="AI DB proposals.evidence",
         ref="evidence.py:95-139; actions.py:96-104, 176-179; agent.py:105-129"),
    dict(branch="온톨로지 추적", step="9", where="fault_ontology.trace · decision.load_decisions",
         how="Cypher 읽기 전용",
         fmt="dict",
         fields="investigation·sections·actions.procedure·options.procedure·rules.policy·recovery_section = '<document_id>#<section_key>' 참조 문자열",
         change="절 본문은 싣지 않고 참조만. build_plan 은 대안 procedure 문서 중 하나가 인용됐는지 검사",
         keep="없음",
         ref="fault_ontology.py:29-51; decision.py:111-146; actions.py:256-258"),
  ],
  ends=[
    "Neo4j Document·DocumentSection·온톨로지 노드(+벡터 색인 2개)",
    "에이전트 매뉴얼 검색 결과·문서 근거 → 대응안 summary·citations → 담당자 카드",
    "정비 계획 절차 참조(procedure)·규칙 정책 절(policy)·회복 기준 절(VERIFIED_BY)",
  ],
  loss=[
    "OPENAI_API_KEY 가 없으면 임베딩을 건너뜀 → section_embedding_v2 색인 없음 → search_manual_sections 실패 → 필수 도구 누락으로 분석 실패",
    "절 재임베딩 판정이 '내용 길이:이름' 이라 길이가 같은 수정은 다시 임베딩되지 않음. _Entity.embedding 은 한 번 만들면 내용이 바뀌어도 그대로",
    "매뉴얼에서 절을 줄이면 옛 '<doc>/section/<i>' 노드가 그래프·색인에 남음(정리는 v2/* 만)",
    "AR100-THERMAL-RESPONSE 는 어떤 설비와도 HAS_PROCEDURE/GOVERNED_BY/DESCRIBED_BY 로 이어지지 않아 문서 근거(get_asset_documents)에 나오지 않음 → 인용 불가",
    "문서 version 을 올리지 않거나 내리면 게시가 409 로 중단 → graph-seed 실패 → knowledge 서비스가 기동하지 않음(depends_on completed_successfully)",
    "0번 절 이름이 번들 A·B 에서 서로 다르게 쓰여 마지막 게시 번들 값이 남음",
  ],
)

NOTES = [
  "주의: 문서 · 주석과 코드가 다른 곳",
  "main.st 머리말 '%IW0..23 계측 12점'·project.json ioGroup 이름 '계측 12점'·values.js 주석 '0..27 = 값 12점'·flows.json 노드 이름 'FC4 0..27' ↔ 실제 17점, 읽기 길이 38워드(%IW0..37). OnnxScorer·AnomalyJob 주석 '12차원/12태그' ↔ 모델 태그 = plant.yaml tags 17개",
  "4_it/detection-flink/sql/01_sources.sql 'tag_limits … plant.yaml 에서 생성됨' ↔ shared/registry/generate.py 가 equipment.yaml 에서 생성",
  "Interpolator.java 주석 'RocksDB 백엔드' ↔ conf/config.yaml state.backend.type: hashmap",
  "plant.py 주석 'Telegraf 브리지가 BAD 센티널을 걸러낸다' ↔ Telegraf 없음, 엣지 values.js 가 null·BAD 로 바꿈",
  "10_schema.sql alert_group 주석 '열린 묶음이면 건수·마지막 시각만 올린다' ↔ alertmanager_to_display.yaml 은 last_ts 만 갱신(count 는 늘 1). suppressed_by·maint_operator 열은 쓰는 코드 없음",
  "equipment.yaml signal_classes(scan_s·deadband·max_interval_s) 의도 ↔ 배속 600 에서 max_interval 600 설비 초 = 1 스캔이라 모든 태그가 매 초 발행(deadband 효과 없음), wall_scan_s 는 쓰는 코드 없음",
  "business.py 주석 'COMMAND_DISAGREE 를 분석 alert 와 같은 길로 → Alertmanager 묶기' ↔ 태그가 '<설비>/<이름>' 이라 asset_of 가 null → asset 이 라인 이름이 되어 설비별 억제·묶기와 어긋남",
  "actions.py stop_mixer·enable_cooling 경로 ↔ 에이전트 구조화 출력 action 은 'maintenance_plan'|'inspect_only' 만 허용, THERMAL-RESPONSE 는 그래프 문서 근거에 안 잡힘 → AI 분석에서는 두 조치가 나오지 않음(코드는 남아 있음)",
  "작업 요청 필드 이름: 과제에 적힌 requester_id·issued_at 은 코드에 없음 → requester·created_at(게이트웨이가 expires_at 추가). approver 는 화면 승인자가 아니라 AI_APPROVER_ID 고정값(operator-01)",
  "mes_requester.yaml 주석 '202 (기록·승인 토픽 전달까지)' ↔ sync_response 가 Kafka 출력 앞에 있어 전달 확인 전 응답일 수 있음(미확인)",
  "create-topics.sh request.approved 주석 'AI 업무 도우미 → …' ↔ MES 흉내(⑧)도 같은 토픽에 냄. request.events·audit.copy 는 '사본'이라 적혀 있으나 소비 코드 없음",
]

if __name__ == "__main__":
    for k, v in LINEAGE.items():
        print(k, v["title"], len(v["hops"]), "hops")


# 빌드가 쓰는 이름: 첫 줄(머리말)을 뺀 목록
CAUTION = NOTES[1:]
