# -*- coding: utf-8 -*-
"""ceco_demo 기술 레이어 구조도 데이터(설계서 v2 「그림 1」 방식, hyd-iot-edu 와 같은 렌더러 arch_layers.py).
카드 = 논리 구성요소(컨테이너가 아님). box 칸에 실제로 그 일을 하는 컨테이너 · 포트를 적는다.
근거: compose.yml · 각 서비스 코드 · ACL · 토픽 생성 스크립트 · 등록부(2026-10-07 코드 감사 반영).
층 이름은 저장소 폴더(0_plant · 1_control · 2_ot · 3_dmz · 4_it · 5_ai)를 따른다. 라우터는 세 망을 잇는 경계라 따로 띠를 둔다.
화살표 번호는 이야기(guide_story.py)의 {a:N} 과 같다. 1~103 은 이전 판과 같은 뜻을 지키고, 새 화살표는 끝에만 붙인다.
그림에 보이는 글자에는 코드 수준(함수 · 파일 경로 · 레지스터 주소 · API 경로)을 쓰지 않는다. 화살표 5번째 칸(세부)은 그림에 그리지 않는 메모다.
"""
NCOL = 7

LAYERS = [  # id, 표시, 이름, 핵심 기능, 배경, 테두리, 글자
 ("L5a", "L5", "AI · 화면 · 분석 (5_ai)", "사건 조회 · 원인 분석 · 정비 판단 · 지식 게시", "#fff8eb", "#d97706", "#b45309"),
 ("L5b", "L5", "AI · 실행 · 업무 판정 (5_ai)", "근거 · 승인 재검사 · 정비 계획 · 사건 접수 · 응답 판정", "#fdf2f8", "#db2777", "#be185d"),
 ("L4s", "L4", "IT · 업무 정본 · 지식 지도 (4_it · 5_ai · shared)", "등록부 · 한 번 쓰면 고치지 않는 정본 · 온톨로지", "#faf5ff", "#a21caf", "#86198f"),
 ("L4m", "L4", "IT · 감시 · 이력 (감시 프로필)", "시스템 건강 · 결과 이력 그래프(기본 기동에는 없음)", "#f8fafc", "#94a3b8", "#64748b"),
 ("L4f", "L4", "IT · 실시간 분석 · 경보 묶기 (4_it)", "Flink 검사 · 모델 · Alertmanager", "#f5f3ff", "#7c3aed", "#6d28d9"),
 ("L4k", "L4", "IT · 번호 매긴 장부 (4_it)", "토픽 · 통로이자 사본", "#ecfeff", "#0e7490", "#0e7490"),
 ("L4c", "L4", "IT · 수집기 스트림 (4_it)", "DMZ ↔ Kafka ↔ Alertmanager ↔ DB 를 잇는 Bento 스트림 7개", "#ecfdf5", "#0f766e", "#0f766e"),
 ("L3", "L3", "DMZ · 완충지대 (3_dmz)", "공장 ↔ 사무실 우편함 · 원시 사본 · 요청 첫 겹 검사", "#eef2ff", "#4f46e5", "#4338ca"),
 ("R", "경계", "구역 라우터 (shared)", "세 망을 잇는 유일한 길 · 허용 경로 외 전부 차단", "#fef2f2", "#dc2626", "#b91c1c"),
 ("L2a", "L2", "OT · 게시판 · 요청 수용 · 화면 (2_ot)", "공장 게시판 · 둘째 겹 검사 · 운전원 화면", "#f8fafc", "#475569", "#334155"),
 ("L2b", "L2", "OT · 엣지 · 보조 (2_ot)", "PLC 읽기 · 쓰기 · 게시 · OT 감시", "#f1f5f9", "#64748b", "#475569"),
 ("L1", "L1", "제어 · PLC (1_control)", "입력 해독 · 인터록 · 명령 검사 · 출력", "#eef2f6", "#334155", "#1e293b"),
 ("L0", "L0", "현장 설비 (0_plant)", "물리 계산 · 고장 · 현장 패널 · 정비팀", "#f5f5f4", "#57534e", "#44403c"),
]

CARDS = {
 # ── L5 AI · 업무 ──
 "people": dict(layer="L5a", col=0, title="담당자 · 운전원 · 강사 · 시험 도구", tech="같은 PC 브라우저 · 사무실 망 안 시험 도구", kind="person",
                lines=["AI 화면 · FUXA · 현장 패널 · 강사 화면", "엣지 · PLC 편집기 · OT MQTT", "공개 포트는 모두 127.0.0.1"]),
 "web": dict(layer="L5a", col=1, title="AI 화면 (Vue 3)", tech="nginx 1.28 · /api/ 만 역프록시", box="web :8080 → 38180",
             lines=["공정 대시보드(첫 화면) · 이상 대응 · 지식 스튜디오", "폴링 · 실행 기록 스트림(SSE)",
                    "FUXA 창: 브라우저가 라우터로 직접 접속"]),
 "k_inc": dict(layer="L5a", col=2, title="사건 조회 · 자동 분석 선별", tech="knowledge 백그라운드", box="knowledge :8000",
               lines=["사건 · 이벤트 · 근거 조회", "조건 맞는 사건만 분석 시작"]),
 "k_agent": dict(layer="L5a", col=3, title="원인 분석 · 검토 (LangGraph)", tech="조사 → 사람 검토(멈춤) → 실행", box="knowledge",
                 lines=["분석 도구 · 구조화 출력(인용 필수)", "검토 대기 지점을 DB에 저장"]),
 "k_kg": dict(layer="L5a", col=4, title="고장 온톨로지 · 정비 판단 엔진", tech="결정론 계산(LLM 아님)", box="knowledge",
              lines=["증상 → 고장 모드 추적 · 매뉴얼 벡터 검색", "자격 · 규칙 제외 · 손익 순위 · 뒤집힘"]),
 "k_act": dict(layer="L5b", col=3, title="승인 재검사 · 실행 넘김", tech="대응안 처리", box="knowledge",
               lines=["기한 · 사건 버전 · 설비 지문 · 지식 지문", "정비 계획은 판단 엔진 다시 계산 → 실행기",
                      "한 건 조치(정지 · 냉각) 길은 지금 안 쓰임"]),
 "llm": dict(layer="L5a", col=6, title="OpenAI (밖)", tech="api.openai.com 직접 호출", kind="ext",
             lines=["gpt-6-luna · Responses API · 재시도 없음", "임베딩 text-embedding-3-small"]),
 "k_evid": dict(layer="L5b", col=1, title="설비 근거 · 파이프라인 상태", tech="근거 조회", box="knowledge",
                lines=["DMZ 사본 InfluxQL(읽기 전용)", "Neo4j 설비 · 문서 · 상하한", "화면용 파이프라인 상태(Flink 잡 수)"]),
 "k_maint": dict(layer="L5b", col=4, title="정비 계획 실행기", tech="상태 기계", box="knowledge",
                 lines=["단계별 작업 요청 → 결과 판정", "회복 판정 → 보고서 → CMMS 작업 이력"]),
 "k_thermal": dict(layer="L5b", col=2, title="냉각 조치 후 온도 관측", tech="관측만 · 명령 없음", box="knowledge",
                   lines=["TT-101이 목표 근처에 머무는지 판정", "냉각 대응안이 지금 안 나와 쉬는 중"]),
 "k_studio": dict(layer="L5a", col=5, title="지식 스튜디오", tech="업로드 · 구조 추출 · 의미 후보 · 검토 게시", box="knowledge",
                  lines=["YAML · Markdown · TXT만", "검토 묶음을 한 트랜잭션으로 병합 게시",
                         "후보 생성 기록은 PostgreSQL ai", "볼륨 knowledge-data · knowledge-uploads · knowledge-output"]),
 "bus_judge": dict(layer="L5b", col=6, title="업무 서비스: 응답 기록 · 시간 판정", tech="business 판정 루프", box="business",
                   lines=["ACK · 만료 · 운전원 대기 · 정비 · 재관측", "명령 불일치면 COMMAND_DISAGREE 경보"]),
 "bus_intake": dict(layer="L5b", col=5, title="업무 서비스: AI 사건 접수", tech="business 컨테이너 접수 스레드", box="business",
                    lines=["sensor.alerts 처음부터 → 검증 · 원본 보관", "상관 묶기 · 저장 뒤 commit"]),
 # ── L4 IT 분석 · 정본 ──
 "f_sql": dict(layer="L4f", col=1, title="Flink SQL 잡 3개", tech="Flink 2.2.1 · 체크포인트(내부 상태)", box="flink-jobmanager · taskmanager",
               lines=["규격: 상하한 넘으면 → CRITICAL", "Z-Score: 최근 값 대비 급변 반복 → WARNING", "CEP: 교반기 전류 상한 뒤 진동 상한",
                      "출력은 최소 1회"]),
 "f_onnx": dict(layer="L4f", col=2, title="Flink ONNX 잡 (오토인코더)", tech="Java DataStream · 출력 최소 1회", box="flink-taskmanager",
                lines=["중복 제거 · 결측 보간 → clean", "센서 전체 창 → 재구성 오차", "임계 초과 → ML 경보"]),
 "trainer": dict(layer="L4f", col=3, title="모델 학습기", tech="PyTorch → ONNX", box="model-trainer (1회)", kind="once",
                 lines=["가상설비 물리로 정상 데이터 합성", "이상 기준을 모델과 함께 저장"]),
 "zk": dict(layer="L4f", col=4, title="ZooKeeper", tech="3.9.5 · Flink HA 메타데이터", box="zookeeper :2181",
            lines=["잡 목록 · 최신 체크포인트 위치", "볼륨 zookeeper-data · zookeeper-datalog"]),
 "am": dict(layer="L4f", col=5, span=2, title="Alertmanager (경보 묶기 · 억제)", tech="v0.34.1 · 기본 기동", box="alertmanager :9093",
            lines=["공정: asset · rule · alertname 으로 묶음", "정비 중 · PLC 정지 → 라인 전체 공정 경보 누름",
                   "설비 운전 꺼짐 → 그 설비 경보만 누름", "인프라 경보: 보낼 곳 없음(화면에서만)", "볼륨 alertmanager-data"]),
 "pg": dict(layer="L4s", col=1, span=3, title="업무 DB 정본 (PostgreSQL 18.6)", tech="DB plant · DB ai · 추가 전용 표 · 계정 분리", box="postgres :5432",
            lines=["workflow · alert · audit · enterprise · registry", "ai: 사건 · 분석 · 대응안 · 체크포인트 · 지식 후보", "볼륨 pg-data"]),
 "graph": dict(layer="L4s", col=4, span=2, title="지식 지도 Neo4j", tech="5.26 Community · 벡터 색인", box="graph :7687",
               lines=["신호 → 증상 → 고장 모드 → 원인 · 점검", "결정 · 대안 · 규칙 · KPI · 매뉴얼 절", "볼륨 graph-data · graph-logs"]),
 "reg": dict(layer="L4s", col=0, title="설비 등록부 (정본)", tech="등록부 파일 하나 → 생성기", kind="info",
             lines=["설비 · 신호 · 명령 · 작업 정의 · 요청자 · 승인자", "엣지 · PLC · 화면 · 허용 목록 · 규칙 범위 · DB 표를 만듦"]),
 "submit": dict(layer="L4f", col=0, title="잡 제출기", tech="제출 스크립트", box="flink-job-submitter (1회)", kind="once",
                lines=["SQL 잡 · ONNX 잡 제출", "모두 돌고 있으면 건너뜀"]),
 "hist": dict(layer="L4m", col=1, title="IT 이력 적재기", tech="Bento 1.21.2 · 감시 프로필", box="it-history", kind="opt",
              lines=["clean · score · alerts → 라인 프로토콜"]),
 "iti": dict(layer="L4m", col=2, title="IT 결과 기록장", tech="InfluxDB 2.9.1 · 감시 프로필", box="it-influx :8086", kind="opt",
             lines=["process · anomaly · alerts", "볼륨 it-influx-data · it-influx-config"]),
 "graf": dict(layer="L4m", col=3, title="Grafana", tech="13.2.3 · 익명 Viewer · 감시 프로필", box="grafana :3000", kind="opt",
              lines=["대시보드: 공정 · 이상 점수 · 경보 · 인프라", "DMZ 원천은 연결만(쓰는 패널 없음)", "볼륨 grafana-data"]),
 "prom": dict(layer="L4m", col=4, title="IT Prometheus", tech="3.13.4 · 감시 프로필", box="prometheus :9090", kind="opt",
              lines=["IT 긁기 + DMZ federate", "규칙 경보 → Alertmanager", "볼륨 prometheus-data"]),
 "kx": dict(layer="L4m", col=5, title="kafka-exporter · cAdvisor", tech="1.10.0 · 0.60.6 · 감시 프로필", box=":9308 · cadvisor", kind="opt",
            lines=["소비 랙 · 컨테이너 자원", "cAdvisor는 특권 실행"]),
 "seed": dict(layer="L4s", col=6, title="그래프 채우기", tech="묶음 A · B · C + 임베딩", box="graph-seed (1회)", kind="once",
              lines=["성공해야 knowledge 기동", "키 없으면 임베딩 없이 성공"]),
 # ── L4 IT 수집 · 장부 ──
 "c1": dict(layer="L4c", col=0, title="① DMZ → Kafka", tech="it-collector 스트림", box="it-collector :4195",
            lines=["MQTT 구독(clean session) → 토픽 3갈래", "GOOD 계측만 raw", "메모리 버퍼"]),
 "c3": dict(layer="L4c", col=1, title="③ 표시 경보 → DMZ", tech="it-collector 스트림", box="it-collector",
            lines=["alerts.display → AR-100/alert/display", "retained · QoS 1"]),
 "c4": dict(layer="L4c", col=2, title="④ 분석 경보 → Alertmanager", tech="it-collector 스트림", box="it-collector",
            lines=["sensor.alerts → 꼬리표 · 설명", "같은 경보가 오면 끝 시각 연장"]),
 "c5": dict(layer="L4c", col=3, title="⑤ PLC 상태 → 억제 경보", tech="it-collector 스트림", box="it-collector",
            lines=["정비 → OutOfService · 정지 → PlantStopped", "운전 꺼짐 → SuppressedByDesign(설비)"]),
 "c6": dict(layer="L4c", col=4, title="⑥ Alertmanager → 기록 · 표시", tech="it-collector 스트림 (HTTP 수신)", box="it-collector",
            lines=["ISA-18.2 묶음 ACTIVE / CLEARED · 사건", "새로 뜬 공정 경보만 표시"]),
 "c7": dict(layer="L4c", col=5, title="⑦ 승인 요청 발송", tech="it-collector 스트림", box="it-collector",
            lines=["request.approved → 정본 조회", "→ 게이트웨이 1회(재시도 없음) → 결과 기록"]),
 "c8": dict(layer="L4c", col=6, title="⑧ MES 흉내 생산 지시", tech="it-collector 스트림 (HTTP 수신)", box="it-collector",
            lines=["주문 → 요청 · 승인 기록(mes-01)", "→ 받음 응답 · request.approved"]),
 "kinit": dict(layer="L4k", col=0, title="토픽 만들기", tech="토픽 생성 스크립트", box="kafka-init (1회)", kind="once",
               lines=["보존 · 압축 설정", "있으면 건너뜀"]),
 "kafka": dict(layer="L4k", col=1, span=6, title="번호 매긴 장부 Kafka 4.3.1 (KRaft 단일 노드)", tech="단일 노드 · 자동 생성 꺼짐 · 정본은 PostgreSQL, 장부는 통로 · 사본", box="kafka :9092",
               lines=["sensor.telemetry.raw · sensor.telemetry.clean · sensor.anomaly.score · sensor.alerts · plant.status · alerts.display — 짧게 보관",
                      "request.approved · request.events · request.responses · audit.copy — 길게 보관", "볼륨 kafka-data"]),
 # ── L3 DMZ ──
 "loader": dict(layer="L3", col=0, title="DMZ 적재기", tech="Bento 1.21.2 · 메모리 버퍼", box="dmz-loader",
                lines=["tag · status · state 구독 + 브로커 $SYS", "→ 라인 프로토콜 묶음"]),
 "dmzi": dict(layer="L3", col=1, title="DMZ 원시 사본", tech="InfluxDB 2.9.1 · plant_raw", box="dmz-influx :8086",
              lines=["쓰기: 초기 관리자 토큰(적재기)", "읽기: v1 it-reader (InfluxQL)", "볼륨 dmz-influx-data · dmz-influx-config"]),
 "dmzb": dict(layer="L3", col=2, span=2, title="DMZ 브로커 (우편함)", tech="Mosquitto 2.1.2 · 계정별 ACL · 익명 금지", box="dmz-broker :1883",
              lines=["bridge-ot: 계측 · 상태 · ACK · 응답 쓰기 / 요청 · 표시 읽기", "gateway: request/in 쓰기 · it-collector: 읽기 + alert/display 쓰기",
                     "dmz-loader · viewer · dmz-exporter", "볼륨 dmz-broker-data"]),
 "gw": dict(layer="L3", col=5, title="DMZ 요청 게이트웨이 (첫 겹 ⓐ)", tech="Node-RED 5.0.7 · 편집기 없음", box="dmz-gateway :8088",
            lines=["토큰 · 스키마 · 허용 목록 · 요청자 · 승인자", "나이 · 중복 · 발행 확인(PUBACK)", "통과 → 만료 붙여 발행 → 받음"]),
 "dmzp": dict(layer="L3", col=6, title="DMZ Prometheus", tech="3.13.4 · 감시 프로필", box="dmz-prom :9090", kind="opt",
              lines=["DMZ 긁기 + OT remote_write 수신", "볼륨 dmz-prom-data"]),
 # ── R 라우터 ──
 "r_base": dict(layer="R", col=0, span=2, title="기본 차단 · 기록", tech="iptables 기본 DROP · MASQUERADE", box="network-router",
                lines=["ESTABLISHED/RELATED만 되돌림 허용", "차단 카운터 변화 기록", "망 ot-net · dmz-net (둘 다 internal) · it-net"], kind="info"),
 "r_ot": dict(layer="R", col=2, span=2, title="OT → DMZ 허용", tech="DNAT · 이름은 라우터를 가리킴", box="network-router",
              lines=["MQTT → DMZ 브로커(브리지)", "remote_write → DMZ Prometheus"], kind="info"),
 "r_it": dict(layer="R", col=4, title="IT → DMZ 허용", tech="DNAT · 출발지는 라우터 주소로", box="network-router",
              lines=["MQTT 브로커 · InfluxQL 사본", "federate · 요청 창구 HTTP"], kind="info"),
 "r_host": dict(layer="R", col=5, span=2, title="호스트 → OT · DMZ", tech="127.0.0.1 → 라우터 DNAT(호스트 관문만)", box="network-router",
                lines=["FUXA · 강사 화면 · 현장 패널", "OT MQTT · 엣지 편집기 · PLC 편집기", "DMZ MQTT · DMZ 사본"], kind="info"),
 # ── L2 OT ──
 "e_col": dict(layer="L2b", col=1, title="엣지 수집 · 발행 탭", tech="Node-RED 5.0.7 · edge 계정 MQTT 3.1.1", box="edge :1880",
               lines=["폴링 · 새 스캔 · 품질 변화 · deadband · 최대 간격", "PLC 통신 상태 · 엣지 생존(LWT) · EdgeX 묶음",
                      "끊기면 디스크 큐(store-and-forward)", "볼륨 edge-data(디스크 큐)"]),
 "e_write": dict(layer="L2b", col=0, title="엣지 PLC 쓰기", tech="같은 탭 · Modbus/TCP", box="edge",
                 lines=["운전원 명령 1차 거름(나이 · retain · 모르는 명령)", "코드 · 값 먼저, 순번 마지막", "실제 시각 동기"]),
 "hub": dict(layer="L2a", col=1, span=2, title="OT 허브 · 공장 게시판 (UNS)", tech="Mosquitto 2.1.2 · 계정별 ACL · 디스크 영속", box="ot-hub :1883",
             lines=["AR-100/reaction/{line}/{asset}/tag · status · ack · state · cmd", "DMZ 브리지(MQTT 5): out 계측 · 응답 / in 요청 · 표시 경보",
                    "끊긴 세션의 몫은 대기열에", "볼륨 ot-hub-data"]),
 "recv": dict(layer="L2a", col=3, title="OT 작업 요청 수신기 (둘째 겹 ⓑ)", tech="Node-RED 엣지 둘째 탭 · MQTT 5 세션", box="edge",
              lines=["스키마 재검사 · 중복 · 허용 작업 · 범위 · 만료", "PLC 가동 · 현장 통신 · 모드 · 정비 → 자동 / 대기 / 거부", "운전원 대기 · 대기 목록(retain)"]),
 "fuxa": dict(layer="L2a", col=5, title="운전원 화면 FUXA 1.3.4", tech="SCADA/HMI · DAQ SQLite", box="fuxa :1881",
              lines=["P&ID 화면 · 알람 · 로그인(보기 · 운전 · 관리)", "요청 수락 · 거부(REMOTE_MANUAL)", "볼륨 fuxa-appdata · fuxa-db"]),
 "gate": dict(layer="L2a", col=6, title="화면 관문", tech="Caddy 2.11.4 · basic_auth", box="hmi-gate :1882",
              lines=["FUXA 게스트 토큰을 바깥에서 막음", "계정 없으면 화면 안 보임"]),
 "hubx": dict(layer="L2b", col=2, title="허브 지표 변환", tech="Bento · 감시 프로필", box="ot-hub-exporter", kind="opt",
              lines=["$SYS → 지표"]),
 "otag": dict(layer="L2b", col=3, title="OT 감시 에이전트", tech="Prometheus agent 모드 · 감시 프로필", box="ot-agent", kind="opt",
              lines=["OT 긁기 → DMZ로 밀어 보냄", "볼륨 ot-agent-data"]),
 "prov": dict(layer="L2b", col=5, title="화면 넣기", tech="계정 · 화면 설정", box="fuxa-provisioner (1회)", kind="once",
              lines=["관리자 비밀번호 교체 · 운전원 계정", "등록부에서 만든 화면 설정"]),
 # ── L1 PLC ──
 "p_slave": dict(layer="L1", col=0, title="Modbus 슬레이브 (엣지 쪽)", tech="OpenPLC v4.2.4 · :502", box="plc",
                 lines=["엣지가 읽는 계측 사본 · 상태 칸", "엣지가 쓰는 시각 · 명령 칸"]),
 "p_cmd": dict(layer="L1", col=1, title="명령 두 채널 검사 (마지막 겹 ⓒ)", tech="주기 안의 명령 검사 단계", box="plc",
               lines=["운전원 채널 · 외부 요청 채널", "코드 · 범위 · 시각 · 만료 · 중복 · 모드 · 비상정지 · 인터록 · 물리 → 응답 코드"]),
 "p_ilk": dict(layer="L1", col=3, title="고압 인터록", tech="트립 기억", box="plc",
               lines=["PT-101 트립 기준 이상 → 펌프 정지", "해제 기준 아래 + 사람 리셋 때만 해제"]),
 "p_in": dict(layer="L1", col=4, title="입력 해독 · 현장 스위치", tech="입력 · 감시 단계", box="plc",
              lines=["스캔 순번 · 시각 동기 정지 감시", "비상정지 · 모드 · 정비 · 현장 버튼"]),
 "p_out": dict(layer="L1", col=2, title="스케줄 · 출력 · 상태", tech="스케줄 · 출력 · 상태 단계 · RETAIN(정비 모드)", box="plc",
               lines=["생산 설정값 · 구동기 출력", "되읽기 감시 · 상태 · 하트비트", "볼륨 plc-data"]),
 "p_master": dict(layer="L1", col=5, title="Modbus 마스터 (설비 쪽)", tech="원격 장치 설정", box="plc",
                  lines=["계측 · 패널 읽기(오류 시 마지막 값)", "구동기 · 설정값 쓰기"]),
 "p_loader": dict(layer="L1", col=6, title="런타임 기동 · 적재기", tech="편집기 v4.3.2로 빌드 · REST :8443", box="plc", kind="once",
                  lines=["지문이 다르면 재적재 · RUN"]),
 # ── L0 설비 ──
 "s_instr": dict(layer="L0", col=2, title="강사 화면 · API", tech="HTTP :8080 · 계정", box="plant-sim",
                 lines=["고장 주입 · 해제 · 진값(정답)"]),
 "s_panel": dict(layer="L0", col=6, title="현장 패널", tech="HTTP :8081 · 계정", box="plant-sim",
                 lines=["LOCAL/REMOTE · 현장 기동정지 · 정비 켜기/해제 키", "비상정지(설비가 직접 읽음) · 리셋"]),
 "s_fault": dict(layer="L0", col=3, title="고장 · 열화 엔진", tech="설비 시계 · 실제 시계", box="plant-sim",
                 lines=["고장 만료 · 열화 진행 · 노이즈 · 결측"]),
 "s_plant": dict(layer="L0", col=4, title="반응기 물리 모델", tech="질량 · 에너지 · 압력 수지", box="plant-sim",
                 lines=["주기 스캔 · 배속 적분"]),
 "s_crew": dict(layer="L0", col=0, title="가상 정비팀", tech="HTTP :8082 · 계정(접수 담당만)", box="plant-sim",
                lines=["안전 확인 → 격리 → 대기 → 효과 → 해제 · 소견"]),
 "s_store": dict(layer="L0", col=5, title="Modbus 데이터 저장소", tech="pymodbus TCP :502 · 유닛 1", box="plant-sim",
                 lines=["코일 · 레지스터 · 접속자는 PLC 하나"]),
}

ARROWS = [  # (from, to, kind, label, detail[, {"g": gutter}])
 # 현장 · PLC
 ("s_plant", "s_store", "data", "스캔 결과", "물리 1스캔 뒤 계측값(순번 · 설비 시각 포함)을 저장소에 씀"),
 ("s_store", "s_plant", "cmd", "구동 읽기", "스캔 시작 때 구동기 4 · 설정값 3을 읽어 물리에 반영(범위로 자름)"),
 ("s_fault", "s_plant", "alert", "고장 효과", "주입된 고장 · 열화가 물리량과 계측(노이즈 · 결측)을 바꿈"),
 ("s_panel", "s_store", "human", "패널 레지스터", "현장 패널 동작(모드 · 현장 기동정지 · 정비 · 비상정지 · 리셋)을 레지스터에 씀"),
 ("s_instr", "s_fault", "human", "고장 주입", "강사 계정 — 고장 이름 · 기간"),
 ("p_master", "s_store", "data", "Modbus/TCP 읽기", "PLC 마스터가 계측 · 패널을 읽음, 오류 시 마지막 값 유지"),
 ("p_master", "s_store", "cmd", "Modbus/TCP 쓰기", "구동기 코일(FC15) · 설정값(FC16) 쓰기"),
 ("p_master", "p_in", "data", "입력 해독", "100 ms 태스크가 입력 워드를 실수로 해독, 순번 · 시각 정지 감시"),
 ("p_in", "p_ilk", "data", "PT-101", "압력 판정 입력"),
 ("p_in", "p_cmd", "data", "모드 · 정비", "현장 스위치가 정한 모드 · 정비 상태가 명령 검사 조건"),
 ("p_ilk", "p_out", "alert", "트립 → 펌프 정지", "인터록이 트립을 기억하면 펌프 출력이 막힘"),
 ("p_cmd", "p_out", "cmd", "검사 통과 값", "검사를 통과한 명령만 출력으로, 결과는 ACK"),
 ("p_out", "p_master", "cmd", "출력 쓰기", "프로그램 출력이 다음 주기에 마스터 쓰기 묶음으로"),
 ("p_out", "p_slave", "data", "상태 · ACK 칸", "모드 · 정비 · 인터록 · 운전 출력 · 설정값 · ACK 순번 · 하트비트"),
 ("p_slave", "p_cmd", "cmd", "명령 두 채널", "엣지가 쓴 운전원 채널 · 요청 채널, 순번 변화 = 새 명령"),
 # OT
 ("p_slave", "e_col", "data", "Modbus/TCP 읽기", "계측 사본 · 상태 · ACK 읽기, 끊기면 마지막 값을 STALE로"),
 ("e_write", "p_slave", "cmd", "Modbus/TCP 쓰기", "1 s 시각 동기 · 명령 코드 · 값 뒤 순번(마지막)"),
 ("e_col", "hub", "data", "MQTT tag · status · ack · state", "MQTT 3.1.1 QoS 1 · {ts, value, quality, seq, pts} · 상태 retain · 허브가 끊기면 디스크 큐"),
 ("hub", "e_write", "cmd", "cmd/operator · cmd/request", "edge 계정 명령 읽기 QoS 1 — 운전원 명령 · 수신기 요청 명령"),
 ("hub", "recv", "cmd", "request/in · decision · PLC 상태", "ot-receiver 계정 MQTT 5 세션 유지 — 요청(브리지 in) · FUXA 결정 · PLC 상태 · 요청 ACK"),
 ("recv", "hub", "cmd", "cmd/request · response/{id}", "자동 수용이면 설비 요청 명령, 단계별 응답, 대기 목록 request/pending(retain)"),
 ("recv", "s_crew", "cmd", "HTTP 작업 지시", "정비팀 계정 · 제한 60 s — 요청 번호 · 작업 · 정비 해제 여부 → 결과 · 소견"),
 ("hub", "fuxa", "data", "AR-100/reaction/# · alert/display", "fuxa 계정 읽기 — 계측 · 상태 · 대기 목록 · 분석 경고(참고)"),
 ("fuxa", "hub", "human", "cmd/operator · decision", "운전원 버튼 → 운전원 명령 · 요청 수락/거부 → 결정"),
 ("gate", "fuxa", "api", "역프록시", "basic_auth 통과 뒤에만 FUXA로 역프록시"),
 ("prov", "fuxa", "once", "계정 · 화면 설정", "기동 때 1회 — 보안 확인 · 관리자 비밀번호 교체 · 운전원 계정 · 화면"),
 ("hubx", "hub", "mon", "$SYS", "ot-exporter 계정으로 브로커 지표 구독"),
 ("otag", "hubx", "mon", "긁기", "허브 지표 긁기 15 s"),
 # 경계 넘기
 ("hub", "dmzb", "data", "MQTT 5 브리지 out", "bridge-ot · out QoS 1: tag · status · ack · state · response — 라우터 1883"),
 ("dmzb", "hub", "cmd", "브리지 in", "같은 브리지 in: request/in(QoS 1) · alert/display(QoS 0)"),
 ("otag", "dmzp", "mon", "remote_write", "OT가 먼저 연결해 밀어 보냄 — 라우터 9090"),
 # DMZ
 ("dmzb", "loader", "data", "MQTT 구독", "dmz-loader 계정 · clean session · QoS 1 · tag · status · state"),
 ("loader", "dmzi", "data", "HTTP write · 라인 프로토콜", "plant_raw · process_raw · plc_status · 500건/1 s · 재시도 1→10 s"),
 ("gw", "dmzb", "cmd", "MQTT 5 request/in", "통과한 요청만 QoS 1 · 만료 30 s · 발행 확인 뒤 202"),
 ("dmzp", "gw", "mon", "지표 긁기", "게이트웨이 지표"),
 # IT 수집 · 장부
 ("dmzb", "c1", "data", "MQTT 구독 (라우터)", "it-collector 계정 · clean session · QoS 1 · tag · status · state · ack · response"),
 ("c1", "kafka", "data", "raw · plant.status · responses", "GOOD 계측 → sensor.telemetry.raw(키 설비) · 상태 → plant.status · 응답 → request.responses(키 요청 번호)"),
 ("kinit", "kafka", "once", "토픽 만들기", "기동 때 1회 · 파티션 · 보존 · lz4 · 있으면 건너뜀"),
 ("kafka", "f_sql", "data", "telemetry.raw", "최신부터 · 워터마크 5 s · 파싱 오류 버림"),
 ("kafka", "f_onnx", "data", "telemetry.raw", "최신부터"),
 ("f_sql", "kafka", "alert", "sensor.alerts", "규격 · Z-Score · CEP 경보 JSON"),
 ("f_onnx", "kafka", "data", "clean · score · ML 경보", "sensor.telemetry.clean · sensor.anomaly.score · sensor.alerts(ML) · 최소 1회"),
 ("trainer", "f_onnx", "file", "model.onnx", "볼륨 model-store(읽기 전용) — 모델 · 태그 순서 · 평균 · 표준편차 · 임계"),
 ("submit", "f_sql", "once", "잡 제출", "SQL 3 + ONNX 1, 4개 RUNNING이면 건너뜀"),
 ("f_sql", "zk", "api", "HA 메타데이터", "잡 목록 · 최신 체크포인트 위치(본체는 볼륨 flink-checkpoints)"),
 ("kafka", "c4", "alert", "sensor.alerts", "최신부터"),
 ("c4", "am", "alert", "HTTP 경보 API", "100건/200 ms · source=plant · alertname · rule · asset · tag · severity · detector"),
 ("kafka", "c5", "data", "plant.status", "최신부터"),
 ("c5", "am", "alert", "억제 상태", "OutOfService · PlantStopped · SuppressedByDesign (source=plant-state)"),
 ("am", "c6", "alert", "webhook", "수신자 plant · firing · resolved"),
 ("c6", "pg", "data", "경보 묶음 · 사건", "계정 ops — 묶음 생성 · 갱신 · 해제, 표시 · 억제 사건"),
 ("c6", "kafka", "alert", "alerts.display", "새로 뜬 공정 경보만"),
 ("kafka", "c3", "alert", "alerts.display", "최신부터"),
 ("c3", "dmzb", "alert", "AR-100/alert/display", "QoS 1 retained → 브리지 in(QoS 0) → OT 허브 → FUXA 분석 경고"),
 ("kafka", "c7", "cmd", "request.approved", "요청 번호만(내용 정본은 PostgreSQL)"),
 ("c7", "pg", "data", "요청 사건 · 감사", "계정 dispatcher — 정본 조회 · 보냄 선기록 · 게이트웨이 결과 기록"),
 ("c7", "gw", "cmd", "HTTP 요청(1회)", "출입 토큰 · 제한 5 s · 재시도 0 — 라우터 8088"),
 ("c7", "kafka", "data", "request.events · audit.copy", "게이트웨이 수용 / 거부 사건 · 감사 사본"),
 ("people", "c8", "human", "HTTP 생산 주문", "시험 도구(사무실 망 안) — 작업 · 설비 · 값 · 계획 담당"),
 ("c8", "pg", "data", "요청 · 승인 · 감사", "계정 mes — 한 문장으로 기록(요청자 mes-01)"),
 ("c8", "kafka", "cmd", "request.approved", "HTTP 202 응답과 함께 발행"),
 ("kafka", "hist", "data", "clean · score · alerts", "최신부터"),
 ("hist", "iti", "data", "라인 프로토콜", "bucket process · 1000건/1 s"),
 ("iti", "graf", "api", "Flux", "공정 · 이상 점수 · 경보 대시보드"),
 ("graf", "dmzi", "api", "원천 연결만", "DMZ 원시 사본 데이터 원천(쓰는 패널 없음)"),
 ("prom", "dmzp", "mon", "federate (라우터)", "DMZ · OT 지표를 통째로 가져옴"),
 ("prom", "kx", "mon", "긁기", "kafka-exporter · cAdvisor"),
 ("prom", "am", "alert", "인프라 경보", "규칙 10개 — 기본 경로, 수신자에 보낼 곳 없음(화면에서만 보임)"),
 # 업무 서비스
 ("kafka", "bus_judge", "data", "plant.status · responses", "최신부터 · 메시지마다 수동 commit"),
 ("bus_judge", "pg", "data", "요청 사건 · 감사 (ops)", "응답 ⓑⓒ 기록, ACK · 만료 · 대기 · 정비 · 재관측 판정 · 정비 모드 변경 감사"),
 ("bus_judge", "kafka", "alert", "audit.copy · events · DISAGREE", "감사 사본 · 판정 사본 · COMMAND_DISAGREE 경보(sensor.alerts) · 전달 확인 없음"),
 ("kafka", "bus_intake", "alert", "sensor.alerts", "처음부터 · 저장 뒤 commit"),
 ("bus_intake", "pg", "data", "AI DB 받은 원본 · 사건", "원본 · 검증 · 상관 묶기(ai_app)"),
 # AI
 ("people", "web", "human", "브라우저 HTTP", "AI 화면"),
 ("web", "k_inc", "api", "사건 · 상태 조회", "nginx → knowledge · 사건 · 설비 · 모델 상태"),
 ("web", "k_agent", "ok", "분석 · 승인 / 반려", "분석 시작 · 결정(메모 필수) · 실행 기록 스트림"),
 ("k_inc", "pg", "data", "사건 조회 · 후보 선별", "AI DB 사건 · 이벤트 읽기, 자동 분석 건너뜀 사유 기록"),
 ("k_inc", "k_agent", "alert", "자동 분석 시작", "조건 맞는 사건을 골라 분석 시작(모델 설정 시)"),
 ("k_agent", "llm", "api", "HTTPS Responses", "gpt-6-luna · 도구 호출 · 구조화 출력"),
 ("k_agent", "k_kg", "api", "도구 호출", "같은 프로세스 — 고장 추적 · 매뉴얼 검색 · 정비 대안 평가"),
 ("k_agent", "k_evid", "api", "근거 도구", "센서 관측 · 설비 문서 · 상하한"),
 ("k_agent", "pg", "data", "분석 실행 · 체크포인트", "분석 실행 기록 · LangGraph 체크포인트(검토 대기)"),
 ("k_kg", "graph", "api", "Bolt · 벡터 검색", "신호 → 증상 → 고장 모드 → 점검 · 결정 · 대안 · 규칙 · 절 벡터"),
 ("k_kg", "pg", "api", "사실값 읽기", "MES · ERP · CMMS 사실값(정비 이력은 화면용 조회, 처음 0건)"),
 ("k_kg", "llm", "api", "임베딩", "질의 벡터 text-embedding-3-small"),
 ("k_evid", "dmzi", "api", "InfluxQL 읽기 (라우터)", "PLC 상태 1시간 · 계측 10 s · 사건 구간 이력 · 읽기 전용"),
 ("k_evid", "graph", "api", "Bolt 읽기", "경보 태그 설비 · 관련 설비 · 문서 전문 · 센서 상하한"),
 ("k_evid", "f_sql", "mon", "Flink 잡 상태(화면용)", "RUNNING 4개면 정상 — AI 분석 도구는 쓰지 않음"),
 ("k_agent", "k_act", "ok", "승인 → 재검사", "승인되면 재검사 → 정비 계획 시작 또는 점검 요청 기록"),
 ("k_act", "pg", "cmd", "요청 · 감사 (지금 안 쓰임)", "한 건 조치용 요청 정본 기록 길 — 지금 AI 출력 종류로는 닿지 않음"),
 ("k_act", "kafka", "cmd", "request.approved (지금 안 쓰임)", "한 건 조치용 번호 알림 길"),
 ("k_act", "k_maint", "ok", "정비 계획 시작", "카드를 만들 때 고정한 단계를 실행기에 넘김"),
 ("k_maint", "pg", "cmd", "단계 요청 · 작업 이력", "단계마다 요청 정본 · 틱마다 요청 사건 조회 · 끝나면 CMMS 작업 이력"),
 ("k_maint", "kafka", "cmd", "request.approved", "단계 작업 요청 번호"),
 ("k_maint", "k_evid", "api", "회복 판정", "매 틱 DMZ 사본 최신값 + 사실값으로 회복 기준 평가"),
 ("k_thermal", "pg", "data", "관측 기록", "냉각 조치 뒤 관측 트랙(지금 시작되지 않음)"),
 ("k_studio", "graph", "ok", "검토 게시", "쓰기 트랜잭션 — 병합만 · 제약 3은 따로"),
 ("k_studio", "llm", "api", "의미 후보", "선택 기능 · 인용 대조 · ID 오류 1회 수정"),
 ("seed", "graph", "once", "묶음 A · B · C + 벡터", "등록부 · 매뉴얼 10 · 온톨로지 게시, 바뀐 것만 임베딩"),
 ("seed", "llm", "once", "임베딩", "절 · 개체 벡터(키 있을 때)"),
 # 사람 → 공장 쪽(라우터 경유)
 ("people", "gate", "human", "FUXA (라우터)", "호스트 → 라우터 → hmi-gate 1882"),
 ("people", "s_panel", "human", "현장 패널 (라우터)", "호스트 → 라우터 → 가상설비 패널(계정)"),
 ("people", "s_instr", "human", "강사 화면 (라우터)", "호스트 → 라우터 → 가상설비 강사 화면(계정)"),
 # ── 2026-10-07 감사로 더한 화살표(104~) ──
 ("s_crew", "s_plant", "cmd", "격리 · 작업 · 효과", "안전 확인 뒤 격리(LOTO) · 설비 시간 대기 · 부품 상태 되돌림 · 격리 해제"),
 ("s_crew", "s_store", "cmd", "정비 해제 키", "잠금 해제 작업이면 정비 해제 키 카운터를 올림"),
 ("e_write", "hub", "data", "엣지 거부 ACK", "모양이 틀린 · 5 s 지난 · retain · 모르는 운전원 명령은 쓰지 않고 거부 ACK"),
 ("otag", "e_col", "mon", "엣지 지표", "엣지 지표 5종 긁기 15 s"),
 ("dmzb", "loader", "mon", "$SYS 지표", "적재기 둘째 스트림이 DMZ 브로커 $SYS를 지표로"),
 ("dmzp", "loader", "mon", "적재기 지표", "적재기 · DMZ 브로커 지표 긁기 15 s"),
 ("dmzp", "dmzi", "mon", "사본 지표", "DMZ InfluxDB 지표 긁기 15 s"),
 ("graf", "prom", "api", "PromQL", "인프라 대시보드"),
 ("prom", "f_sql", "mon", "Flink 지표", "JobManager · TaskManager 지표 9249"),
 ("prom", "c1", "mon", "수집기 지표", "it-collector 지표 4195"),
 ("prom", "iti", "mon", "기록장 지표", "it-influx 지표"),
 ("kx", "kafka", "mon", "소비 랙 조회", "그룹별 오프셋 · 랙"),
 ("web", "k_studio", "api", "지식 스튜디오", "업로드 · 추출 · 후보 · 검토 · 게시 · 관계 그래프"),
 ("k_studio", "pg", "data", "후보 생성 기록", "PostgreSQL ai 의 지식 후보 생성 표"),
 ("web", "k_evid", "api", "공정 대시보드 · 파이프라인", "DMZ 사본 최신값 · 센서 추세 · 수집 · 분석 연결 상태 15 s"),
 ("k_act", "k_evid", "api", "재검사: 근거 · 공정", "승인 순간 공정 상태 · 근거 다시 조회"),
 ("k_act", "k_kg", "api", "재검사: 판단 재계산", "고른 대안의 자격 · 제외 · 계산 가능 여부를 다시"),
 ("k_thermal", "k_evid", "api", "온도 관측", "냉각 조치 뒤 TT-101 관측(지금 시작되지 않음)"),
 ("reg", "e_col", "file", "엣지 흐름 · 태그", "등록부 생성물 — 신호 목록 · 엣지 흐름"),
 ("reg", "p_cmd", "file", "PLC 상수 · 주소", "등록부 생성물 — PLC 프로그램 상수 · 원격 장치 설정"),
 ("reg", "prov", "file", "FUXA 화면 설정", "등록부 생성물 — 화면 구성"),
 ("reg", "gw", "file", "허용 목록 · 스키마", "등록부 생성물 — 허용 작업 · 요청 서식"),
 ("reg", "pg", "file", "등록부 표", "등록부 생성물 — DB 등록부 표(빈 볼륨 첫 기동 때)"),
 ("reg", "f_sql", "file", "규격 상하한", "등록부 생성물 — 규칙 범위 표"),
 ("reg", "bus_judge", "file", "태그 · 작업 정의", "등록부 생성물 — 업무 서비스 · AI가 읽음"),
 ("reg", "seed", "file", "설비 · 센서 노드", "등록부 생성물 — 온톨로지 설비 · 센서"),
 ("people", "hub", "human", "OT MQTT (라우터)", "viewer 계정 읽기 전용"),
 ("people", "e_col", "human", "엣지 편집기 (라우터)", "로그인 · 읽기 전용"),
 ("people", "p_loader", "human", "PLC 편집기 (라우터)", "HTTPS REST"),
 ("k_studio", "graph", "api", "관계 그래프 · 누락 조회", "읽기 전용 · 이웃 깊이 1~3 · 경로 500 · 10 s"),
 ("reg", "c4", "file", "태그 → 설비 지도", "등록부 생성물 — 경보 꼬리표 asset"),
]
