// FUXA 1.3.4 설정(hmibench fuxa134·fuxa134-uns). v1.3.4 server/settings.default.js 와 같고 차이는 보안 3줄:
//   secureEnabled: true (인증 필수, CVE-2025-69970 계열 대응) · secretCode · tokenExpiresIn / nodeRedEnabled: false 유지
module.exports = {
    version: 1.4,
    language: 'en',
    hideEditorOnboarding: false,
    editorSectionMessages: { hideDevicePluginsNotice: false },
    uiPort: process.env.PORT || 1881,
    logDir: '_logs',
    logApiLevel: 'tiny',
    dbDir: '_db',
    daqEnabled: true,
    daqTokenizer: 24,
    logs: { retention: 'none' },
    broadcastAll: false,
    lazyViewLoading: false,
    "allowedOrigins": ["http://localhost", "http://127.0.0.1", "http://192.168.*", "http://10.*", "http://localhost:4200"],
    apiRateLimitWindowMs: 5 * 60 * 1000,
    apiRateLimitMax: 1000,
    authRateLimitWindowMs: 5 * 60 * 1000,
    authRateLimitMax: 100,
    heartbeatIntervalSec: 10,
    webcamSnapShotsDir: '_webcam_snapshots',
    webcamSnapShotsCleanup: false,
    webcamSnapShotsRetain: 7,
    swaggerEnabled: false,
    nodeRedEnabled: false,
    nodeRedAuthMode: "secure",
    nodeRedUnsafeModules: false,
    secureEnabled: true,
    secretCode: 'bench-fuxa-secret',
    tokenExpiresIn: '1h',
}
