-- shared/registry/generate.py 가 shared/registry/equipment.yaml 에서 생성. 손으로 고치지 않는다.
-- 이미 있는 DB 에 다시 실행해도 된다(있는 행은 건너뛴다): 등록부에 추가한 설비·신호·작업 정의만 들어간다.
SET search_path TO registry;
INSERT INTO equipment(id, type, name, site, area, line) VALUES ('TK-101','Tank','원료탱크','AR-100','reaction','reactor-line-01') ON CONFLICT DO NOTHING;
INSERT INTO equipment(id, type, name, site, area, line) VALUES ('R-101','Reactor','반응기','AR-100','reaction','reactor-line-01') ON CONFLICT DO NOTHING;
INSERT INTO equipment(id, type, name, site, area, line) VALUES ('HX-101','Heater','재킷 히터','AR-100','reaction','reactor-line-01') ON CONFLICT DO NOTHING;
INSERT INTO equipment(id, type, name, site, area, line) VALUES ('HX-102','Cooler','냉각기','AR-100','reaction','reactor-line-01') ON CONFLICT DO NOTHING;
INSERT INTO equipment(id, type, name, site, area, line) VALUES ('ST-103','Strainer','냉각수 스트레이너','AR-100','reaction','reactor-line-01') ON CONFLICT DO NOTHING;
INSERT INTO equipment(id, type, name, site, area, line) VALUES ('P-101','Pump','공급 펌프','AR-100','reaction','reactor-line-01') ON CONFLICT DO NOTHING;
INSERT INTO equipment(id, type, name, site, area, line) VALUES ('CV-101','ControlValve','배출 밸브','AR-100','reaction','reactor-line-01') ON CONFLICT DO NOTHING;
INSERT INTO equipment(id, type, name, site, area, line) VALUES ('M-101','Agitator','교반기','AR-100','reaction','reactor-line-01') ON CONFLICT DO NOTHING;
INSERT INTO equipment(id, type, name, site, area, line) VALUES ('PLC-01','Controller','제어기','AR-100','reaction','reactor-line-01') ON CONFLICT DO NOTHING;
INSERT INTO signal(tag, equipment_id, class, unit, lsl, usl, deadband, scan_s, max_interval_s, topic) VALUES ('LT-101','TK-101','level','%',10.0,95.0,0.025,5,600,'AR-100/reaction/reactor-line-01/TK-101/tag/LT-101') ON CONFLICT DO NOTHING;
INSERT INTO signal(tag, equipment_id, class, unit, lsl, usl, deadband, scan_s, max_interval_s, topic) VALUES ('LT-102','R-101','level','%',15.0,90.0,0.025,5,600,'AR-100/reaction/reactor-line-01/R-101/tag/LT-102') ON CONFLICT DO NOTHING;
INSERT INTO signal(tag, equipment_id, class, unit, lsl, usl, deadband, scan_s, max_interval_s, topic) VALUES ('TT-101','R-101','temperature','degC',40.0,95.0,0.03,10,600,'AR-100/reaction/reactor-line-01/R-101/tag/TT-101') ON CONFLICT DO NOTHING;
INSERT INTO signal(tag, equipment_id, class, unit, lsl, usl, deadband, scan_s, max_interval_s, topic) VALUES ('TT-102','HX-101','temperature','degC',NULL,125.0,0.045,10,600,'AR-100/reaction/reactor-line-01/HX-101/tag/TT-102') ON CONFLICT DO NOTHING;
INSERT INTO signal(tag, equipment_id, class, unit, lsl, usl, deadband, scan_s, max_interval_s, topic) VALUES ('PT-101','R-101','pressure','barg',NULL,6.0,0.006,5,600,'AR-100/reaction/reactor-line-01/R-101/tag/PT-101') ON CONFLICT DO NOTHING;
INSERT INTO signal(tag, equipment_id, class, unit, lsl, usl, deadband, scan_s, max_interval_s, topic) VALUES ('FT-101','P-101','flow','m3/h',NULL,NULL,0.02,5,600,'AR-100/reaction/reactor-line-01/P-101/tag/FT-101') ON CONFLICT DO NOTHING;
INSERT INTO signal(tag, equipment_id, class, unit, lsl, usl, deadband, scan_s, max_interval_s, topic) VALUES ('FT-102','CV-101','flow','m3/h',NULL,NULL,0.02,5,600,'AR-100/reaction/reactor-line-01/CV-101/tag/FT-102') ON CONFLICT DO NOTHING;
INSERT INTO signal(tag, equipment_id, class, unit, lsl, usl, deadband, scan_s, max_interval_s, topic) VALUES ('IT-101','P-101','current','A',NULL,14.0,0.015,10,600,'AR-100/reaction/reactor-line-01/P-101/tag/IT-101') ON CONFLICT DO NOTHING;
INSERT INTO signal(tag, equipment_id, class, unit, lsl, usl, deadband, scan_s, max_interval_s, topic) VALUES ('IT-102','M-101','current','A',NULL,9.6,0.0125,10,600,'AR-100/reaction/reactor-line-01/M-101/tag/IT-102') ON CONFLICT DO NOTHING;
INSERT INTO signal(tag, equipment_id, class, unit, lsl, usl, deadband, scan_s, max_interval_s, topic) VALUES ('VT-101','M-101','vibration','mm/s',NULL,7.1,0.03,10,600,'AR-100/reaction/reactor-line-01/M-101/tag/VT-101') ON CONFLICT DO NOTHING;
INSERT INTO signal(tag, equipment_id, class, unit, lsl, usl, deadband, scan_s, max_interval_s, topic) VALUES ('pH-101','R-101','analytic','pH',6.2,8.4,0.003,10,600,'AR-100/reaction/reactor-line-01/R-101/tag/pH-101') ON CONFLICT DO NOTHING;
INSERT INTO signal(tag, equipment_id, class, unit, lsl, usl, deadband, scan_s, max_interval_s, topic) VALUES ('CT-101','R-101','analytic','mS/cm',NULL,NULL,0.006,10,600,'AR-100/reaction/reactor-line-01/R-101/tag/CT-101') ON CONFLICT DO NOTHING;
INSERT INTO signal(tag, equipment_id, class, unit, lsl, usl, deadband, scan_s, max_interval_s, topic) VALUES ('FT-103','HX-102','flow','m3/h',20.0,NULL,0.075,5,600,'AR-100/reaction/reactor-line-01/HX-102/tag/FT-103') ON CONFLICT DO NOTHING;
INSERT INTO signal(tag, equipment_id, class, unit, lsl, usl, deadband, scan_s, max_interval_s, topic) VALUES ('TT-103','HX-102','temperature','degC',NULL,28.0,0.025,10,600,'AR-100/reaction/reactor-line-01/HX-102/tag/TT-103') ON CONFLICT DO NOTHING;
INSERT INTO signal(tag, equipment_id, class, unit, lsl, usl, deadband, scan_s, max_interval_s, topic) VALUES ('TT-104','HX-102','temperature','degC',NULL,45.0,0.03,10,600,'AR-100/reaction/reactor-line-01/HX-102/tag/TT-104') ON CONFLICT DO NOTHING;
INSERT INTO signal(tag, equipment_id, class, unit, lsl, usl, deadband, scan_s, max_interval_s, topic) VALUES ('PDT-103','ST-103','pressure','bar',NULL,0.8,0.003,5,600,'AR-100/reaction/reactor-line-01/ST-103/tag/PDT-103') ON CONFLICT DO NOTHING;
INSERT INTO signal(tag, equipment_id, class, unit, lsl, usl, deadband, scan_s, max_interval_s, topic) VALUES ('PT-102','R-101','pressure','barg',NULL,6.0,0.006,5,600,'AR-100/reaction/reactor-line-01/R-101/tag/PT-102') ON CONFLICT DO NOTHING;
INSERT INTO work_master(id, equipment_id, parameters, description) VALUES ('WM-M101-STOP','M-101','[]'::jsonb,'교반기 정지(AI stop_mixer)') ON CONFLICT DO NOTHING;
INSERT INTO work_master(id, equipment_id, parameters, description) VALUES ('WM-HX102-ENABLE','HX-102','[]'::jsonb,'냉각기 기동(AI enable_cooling)') ON CONFLICT DO NOTHING;
INSERT INTO work_master(id, equipment_id, parameters, description) VALUES ('WM-R101-TEMPSP','R-101','[{"id": "temp_sp_c", "min": 60.0, "max": 80.0, "unit": "degC"}]'::jsonb,'반응기 온도 설정값 변경(운전 범위 안 조정)') ON CONFLICT DO NOTHING;
INSERT INTO work_master(id, equipment_id, parameters, description) VALUES ('WM-M101-START','M-101','[]'::jsonb,'교반기 재기동(정비 뒤)') ON CONFLICT DO NOTHING;
INSERT INTO work_master(id, equipment_id, parameters, description) VALUES ('WM-P101-SPEED','P-101','[{"id": "pump_speed_pct", "min": 20.0, "max": 80.0, "unit": "%"}]'::jsonb,'공급 펌프 속도 변경(부하 조정)') ON CONFLICT DO NOTHING;
INSERT INTO work_master(id, equipment_id, parameters, description) VALUES ('WM-P101-STOP','P-101','[]'::jsonb,'공급 펌프 정지') ON CONFLICT DO NOTHING;
INSERT INTO work_master(id, equipment_id, parameters, description) VALUES ('WM-P101-START','P-101','[]'::jsonb,'공급 펌프 재기동') ON CONFLICT DO NOTHING;
INSERT INTO work_master(id, equipment_id, parameters, description) VALUES ('WM-PLC-MAINT-ON','PLC-01','[]'::jsonb,'정비 모드 켜기(원격 명령 차단·정비팀 901 작업 시작)') ON CONFLICT DO NOTHING;
INSERT INTO work_master(id, equipment_id, parameters, description) VALUES ('WM-FLD-STRAINER-SWITCH','ST-103','[]'::jsonb,'냉각수 스트레이너 예비 바스켓 전환') ON CONFLICT DO NOTHING;
INSERT INTO work_master(id, equipment_id, parameters, description) VALUES ('WM-FLD-STRAINER-CLEAN','ST-103','[]'::jsonb,'대기 바스켓 분해 세척') ON CONFLICT DO NOTHING;
INSERT INTO work_master(id, equipment_id, parameters, description) VALUES ('WM-FLD-JACKET-DESCALE','HX-102','[]'::jsonb,'재킷 냉각 코일 화학 세정') ON CONFLICT DO NOTHING;
INSERT INTO work_master(id, equipment_id, parameters, description) VALUES ('WM-FLD-BEARING-REPLACE','M-101','[]'::jsonb,'교반기 베어링 점검·교체') ON CONFLICT DO NOTHING;
INSERT INTO work_master(id, equipment_id, parameters, description) VALUES ('WM-FLD-SHAFT-ALIGN','M-101','[]'::jsonb,'교반기 축 정렬 점검·조정') ON CONFLICT DO NOTHING;
INSERT INTO work_master(id, equipment_id, parameters, description) VALUES ('WM-FLD-PT101-CALIBRATE','R-101','[]'::jsonb,'PT-101 비교 교정(계기 격리)') ON CONFLICT DO NOTHING;
INSERT INTO work_master(id, equipment_id, parameters, description) VALUES ('WM-FLD-CV101-REPAIR','CV-101','[]'::jsonb,'배출 밸브 분해 정비') ON CONFLICT DO NOTHING;
INSERT INTO work_master(id, equipment_id, parameters, description) VALUES ('WM-FLD-LOTO-RELEASE','PLC-01','[]'::jsonb,'작업 완료 확인·격리 해제·정비 해제 키') ON CONFLICT DO NOTHING;
